package me.ulrich.clans.manager.EnumFiles.ru_ru;

import java.util.Arrays;
import me.ulrich.clans.packets.methods.enums.interfaces.ConfigurationEnum;

public enum Lang implements ConfigurationEnum  {
	
	LANGUAGE("LANGUAGE", " ", " ", " ", " # ПЕРЕВОДЫ ЯЗЫКОВЫХ И ДИАЛОГОВЫХ ФАЙЛОВ", " "),
	
	TAG("LANGUAGE.tag", "&6&lU&9&lКланы &r&7|"),
	COMMAND_BY_PLAYER("LANGUAGE.command by player","%tag% &cЭта команда должна использоваться игроком."),
	COMMAND_BY_CONSOLE("LANGUAGE.command by console","%tag% &cЭта команда должна использоваться КОНСОЛЬЮ."),

	EMPTY_CHAT_HELP("LANGUAGE.empty chat help","%tag% &cОшибка, Используйте &b/. <message>"),
	DISABLED_WORLD_COMMAND("LANGUAGE.disabled world command","%tag% &cКлановые команды выключены в этом мире."),
	ERROR_START_ACTION("LANGUAGE.error start action","%tag% &cВозникла ошибка при выполнении."),
	ERROR_CHARACTER("LANGUAGE.error character","%tag% &cЗначение содержит недопустимые символы."),
	ERROR_MOD_DESC("LANGUAGE.error mod desc","%tag% &cОшибка при изменении описания клана."),
	HAS_GLOBALFF("LANGUAGE.has globalff","%tag% &aГлобальный дружественный огонь теперь включен!"),
	NO_PERMISSION("LANGUAGE.no permission","%tag% &cУ вас нет прав доступа"), 
	CHEST_EXTRA_BUYED_UPDATE("LANGUAGE.chest extra buyed update","%tag% &b%player% &aприобрел новый сундук для клана."), 
	REGION_LIST_HEADER("LANGUAGE.region list header","&9&lСписок регионов:"), 
	REGION_LIST_EMPTY("LANGUAGE.region list empty","&8 - Нет сохраненный регионов"), 
	REGION_LIST_FORMAT("LANGUAGE.region list format"," &b%region_name% &7- %region_creator% &7- &b%region_firstpoint%&7/&b%region_secondpoint%"),
	REGION_NOT_EXISTS("LANGUAGE.region not exists","%tag% &cНет такого региона."),
	REGION_EXISTS("LANGUAGE.region exists","%tag% &cРегион с таким названием уже есть."),
	CLAN_TAG_IN_USE("LANGUAGE.tag in use","%tag% &cЭтот Тег уже используется."),
	CLAN_NOT_FOUND("LANGUAGE.clan not found","%tag% &cКлана с таким Тегом не существует."),
	CLAN_ALLY_HEADER("LANGUAGE.clan ally header","&9&lСписок союзников. &8(тег/kdr/участники)"), 
	CLAN_LIST_EMPTY("LANGUAGE.clan list empty"," &cВ этом списке нет Кланов."), 
	CLAN_IS_YOUR_CLAN("LANGUAGE.clan is your clan","%tag% &cЭто ваш Клан."), 
	CLAN_IS_RIVAL("LANGUAGE.clan is rival","%tag% &cЭтот Клан уже стал соперником."), 
	CLAN_ALREADY_ALLY("LANGUAGE.clan already ally","%tag% &cЭтот Клан уже стал союзником."), 
	CLAN_DONT_ALLY("LANGUAGE.clan dont ally","%tag% &cЭто не союзный Клан."), 
	CLAN_PLAYER_ISNOT_YOUR_CLAN("LANGUAGE.clan player isnot your clan","%tag% &cЭтот игрок не в вашем Клане."), 
	CLAN_MAX_MEMBERS("LANGUAGE.clan max members","&cЭтот Клан уже достиг лимита участников."), 
	CLAN_MAX_MEMBERS_LEVEL("LANGUAGE.clan max members level","%tag% &cЭтот Клан уже достиг лимита участников для своего уровня."), 
	CLAN_PLAYER_KICKED_OUT("LANGUAGE.clan player kicked out","%tag% &aВы были выгнаны из клана &b%clan% &c&a%clan_leader%"),
	CLAN_PLAYER_KICKED_OUTBY("LANGUAGE.clan player kicked outby","%tag% &4%player% &eбыл выгнан из клана &a%clan_leader%"), 
	CLAN_TAG_EQUALS("LANGUAGE.clan tag equals","%tag% &cТег не изменён. Видимо, он такой же."),
	CLAN_NAME_EQUALS("LANGUAGE.clan name equals","%tag% &cИмя не изменено. Видимо, оно такое же."), 
	CLAN_ALREADY_RIVAL("LANGUAGE.clan already rival","%tag% &cЭтот Клан уже стал соперником."), 
	CLAN_IS_ALLY("LANGUAGE.clan is ally","%tag% &cThis Этот Клан уже стал союзником."), 
	CLAN_RIVAL_ERROR_ADD("LANGUAGE.clan rival error add","%tag% &cОшибка при добавлении соперника."), 
	CLAN_RIVAL_ERROR_REMOVE("LANGUAGE.clan rival error remove","%tag% &cОшибка при удалении соперника."), 
	CLAN_DONT_RIVAL("LANGUAGE.clan dont rival","%tag% &cЭтот клан не соперник."), 
	CLAN_NEW_ALLY("LANGUAGE.clan new ally","%tag% &c&l! &eБыл сформирован новый альянс с &a%clan_tag%"), 
	CLAN_REMOVED_ALLY("LANGUAGE.clan removed ally","%tag% &c&l! &eАльянс с кланом &a%clan_tag% &eбыл разрушен."), 
	CLAN_ONE_REMOVED_ALLY("LANGUAGE.clan one removed ally","%tag% &c&l! &eСоюзник был удален."), 
	CLAN_ONE_REMOVED_RIVAL("LANGUAGE.clan one removed rival","%tag% &c&l! &eСоперник был удален."),
	CLAN_CREATED("LANGUAGE.clan created","%tag% &c&l! &eНовый Клан &b%clan_tag% &eбыл создан &a%player%."), 
	CLAN_DELETED("LANGUAGE.clan deleted","%tag% &c&l! &eКлан &b%clan_tag% &eбыл распущен &a%player%."), 
	CLAN_DELETED_SMALL("LANGUAGE.clan deleted small","&c&mУдалён"), 
	CLAN_FF_CHANGED("LANGUAGE.clan ff changed","%tag% &c&l! &eДружественный урон &b%value%."), 
	CLAN_GLOBALFF_CHANGED("LANGUAGE.clan globalff changed","%tag% &c&l! &eГлобальный дружественный урон &b%value%."), 
	CLAN_NEW_JOIN("LANGUAGE.clan new join","%tag% &c&l! &eИгрок &a%player% &eвступил в клан."),
	CLAN_NEW_KICK("LANGUAGE.clan new kick","%tag% &c&l! &eИгрок &a%player% &eбыл изгнан из клана."), 
	CLAN_NEW_RIVAL("LANGUAGE.clan new rival","%tag% &c&l! &eНовое соперничество с кланом &a%clan_tag%"), 
	CLAN_NEW_LEADER("LANGUAGE.clan new leader","%tag% &c&l! &eНовый лидер клана &a%clan_tag% &e- &a%player%"),
	CLAN_RIVAL_REMOVED("LANGUAGE.clan rival removed","%tag% &c&l! &eСоперничество с кланом &a%clan_tag% &eбыло отменено."), 
	CLAN_VERIFY_CHANGED("LANGUAGE.clan verify changed","%tag% &c&l! &eКлан был изменен на &a%value%."), 
	CLAN_NEW_PROMOTE("LANGUAGE.clan new promote","%tag% &c&l! &eИгрок &a%player% &eбыл повышен."), 
	CLAN_NEW_DEMOTE("LANGUAGE.clan new demote","%tag% &c&l! &cИгрок &a%player% &eбыл понижен."), 
	CLAN_PVP_DISABLED("LANGUAGE.clan pvp disabled","%tag% &cКлановое PVP теперь выключено."),
	CLAN_ALLYPVP_DISABLED("LANGUAGE.clan allypvp disabled","%tag% &cPVP между союзниками выключено."),
	CLAN_TAG_BLACKLIST("LANGUAGE.clan tag blacklist","%tag% &cЭтот Тег нельзя использовать в Кланах."),
	CLAN_CHANGED_SETTINGS("LANGUAGE.clan changed settings","%tag% &aНастройки клана были изменены."),
	
	CLAN_SETTINGS_WARINVITE("LANGUAGE.clan settings warinvite","&bПриглашение на войну"),
	CLAN_SETTINGS_ALLYSHAREDCHAT("LANGUAGE.clan settings allysharedchat","&bСовместный чат союзников"),
	CLAN_SETTINGS_JOINLEAVE("LANGUAGE.clan settings joinleave","&bВход и Выход"),
	CLAN_SETTINGS_ALLYSHAREDHOME("LANGUAGE.clan settings allysharedhome","&bТочки дома союзников"),
	CLAN_SETTINGS_CLANFF("LANGUAGE.clan settings clanff","&bДружественный урон клана"),
	
	CLAN_DELETE_ERROR_GUI("LANGUAGE.clan delete error gui","&4Ошибка удаляется!"), 
	CLAN_NO_ACTIONS("LANGUAGE.clan no actions","%tag% &cНет действий для отмены."), 
	HELP_UCLAN_HEADER("LANGUAGE.help uclan header","&4&lАдмин | Помощь по кланам:"), 
	HELP_CLAN_HEADER("LANGUAGE.help clan header","&9&lПомощь с Кланом:"), 
	HELP_INFO_HEADER("LANGUAGE.help info header","&9&lИнформация о клане &8%clan_tag%&9&l:"), 
	HELP_INFO_EMPTY("LANGUAGE.help info empty","&cНичего"), 
	HELP_CLANLIST("LANGUAGE.help clanlist","&9&lСписок кланов: &8(rank/tag/desc/kdr/members)"),
	HELP_CLANLIST_SUBHEADER("LANGUAGE.help clanlist subheader"," &8Отображается %cur%/%amount% из %total% (Страница: %pag_cur%/%pag_max%)"),
	HELP_PROFILE_HEADER("LANGUAGE.help profile header","&9&lПрофиль &a%player%&9&l:"),

	HELP_RIVAL_HEADER("LANGUAGE.help rival header","&9&lСписок соперников. &8(tag/kdr/members)"), 
	HELP_STATS_HEADER("LANGUAGE.help stats header","&9&lСтатус Клана &a%clan_tag%&9&l:"),
	HELP_STATS_FORMAT_PLAYER("LANGUAGE.help stats format player","  &7&a%list_player% &7- &b%list_player_role% &7- &b%list_player_kills%&8/&b%list_player_deaths% &8(%list_player_kdr%) &7[%list_player_seen_date%]"),
	
	TRANSLACTION_PLAYER("LANGUAGE.translaction players","игроки"), 
	TRANSLACTION_IS_ON("LANGUAGE.translaction is on","&a&lОнлайн"), 
	TRANSLACTION_IS_OFF("LANGUAGE.translaction is off","&c&lОффлайн"), 
	TRANSLACTION_YES("LANGUAGE.translaction yes","&b&lДА"),
	TRANSLACTION_NO("LANGUAGE.translaction no","&c&lНЕТ"),
	
	
	PLAYER_DONT_LEADER("LANGUAGE.clan dont leader","%tag% &cВы не являетесь лидером Клана."),
	PLAYER_DONT_PERMISSION_TO_DEMOTE("LANGUAGE.clan dont permission top demote","%tag% &cВы не можете понижать игроков."), 
	PLAYER_DONT_PERMISSION_TO_PROMOTE("LANGUAGE.clan dont permission top promote","%tag% &cВы не можете повышать игроков."),
	PLAYER_NO_INVITATIONS("LANGUAGE.player no invitation","%tag% &cУ вас нет приглашений."), 
	PLAYER_DONT_MOD_AND_LEADER("LANGUAGE.clan dont mod and leader","%tag% &cВы не Лидер или Модератор Клана."), 
	PLAYER_DONT_MOD_AND_LEADER_GUI("LANGUAGE.clan dont mod and leader gui","&cТребуется &4&lЛидер &cили &4&lМодератор&c!"), 
	PLAYER_DONT_MOD("LANGUAGE.player dont mod","%tag% &cЭтот игрок не модератор."), 
	PLAYER_IS_MOD("LANGUAGE.player is mod","%tag% &cЭтот игрок уже модератор."), 
	PLAYER_OFFLINE("LANGUAGE.player offline","%tag% &cЭтот игрок оффлайн или не существует!"),
	PLAYER_CANNOT_EXPEL_LEADER("LANGUAGE.player cannot expel leader","%tag% &cВы не можете изгнать лидера Клана."), 
	PLAYER_CANNOT_EXPEL_MOD("LANGUAGE.player cannot expel mod","%tag% &cМодератор не может исключить другого с той же должности."),
	PLAYER_IS_CLAN_LEADER("LANGUAGE.player is clan leader","%tag% &cВы лидер Клана, чтобы выйти используйте &b/clan disband&c и вы удалите клан ..."), 
	YOU_DONT_HAVE_CLAN("LANGUAGE.you donthave clan","%tag% &cУ вас нет Клана."),
	PLAYER_DONT_HAVE_CLAN("LANGUAGE.player donthave clan","%tag% &cУ этого игрока нет Клана."),
	PLAYER_HAVE_CLAN("LANGUAGE.player have clan","%tag% &cУ вас уже есть Клан."), 
	PLAYER_HAS_CLAN("LANGUAGE.player has clan","%tag% &cЭтот игрок уже в Клане."), 
	PLAYER_IS_YOU("LANGUAGE.player is you","%tag% &cЭтот игрок - вы."), 
	PLAYER_DONT_HAVE_MONEY("LANGUAGE.player dont have money","%tag% &cВам нужно &a$%amount% &cдля этого."), 
	PLAYER_DONT_HAVE_MONEY_GUI("LANGUAGE.player dont have money gui","&cВам нужно &a$%amount%"), 
	PLAYER_DEBITED_MONEY("LANGUAGE.player debited money","%tag% &aС вашего счета было списано &a%amount%."), 
	PLAYER_DEPOSITED_MONEY("LANGUAGE.player deposited money","%tag% &a$%amount% &eбыло начислено на ваш счет."), 

	PLAYER_INVITATION_EXPIRED("LANGUAGE.player invitation expired","%tag% &cВаше приглашение в Клан &f%clan_tag% &ceистекло."), 
	PLAYER_INVITATION_DANIED("LANGUAGE.player invitation daniel","%tag% &cИгрок отклонил ваше приглашение."), 

	PLAYER_ALREADY_INVITED("LANGUAGE.player already invited","%tag% &cДля этого игрока уже есть приглашение!"), 

	GUI_ERROR("LANGUAGE.gui error","%tag% &cЭто меню содержит ошибку и не может быть открыто"), 
	PLAYER_TELEPORT_DONT_MOVE("LANGUAGE.player teleport dont move","%tag% &aПодготовка к телепортации, не двигайтесь %sec% сек."), 
	PLAYER_TELEPORT_MOVED("LANGUAGE.player teleport moved","%tag% &cВы двигались и телепортация была отменена!!!"), 
	PLAYER_TELEPORT_TRUE("LANGUAGE.player teleport true","%tag% &aВы были телепортированы!"),
	PLAYER_TELEPORT_FALSE("LANGUAGE.player teleport false","%tag% &cВы не были телепортированы из-за какой-то ошибки!"), 
	UNKNOWN_ERROR("LANGUAGE.unknown error","%tag% &cПроизошла неизвестная ошибка, пожалуйста, попробуйте еще раз!"),
	NOTHING_HERE("LANGUAGE.nothing here","&cЗдесь ничего."), 
	CLAN_EMPTY_NAME("LANGUAGE.clan empty name","&c<Без имени!>"),
	CLAN_EMPTY_DESC("LANGUAGE.clan empty desc","&c<Без описания!>"),
	
	JSON_ADVANCED_ACTION_CREATE("LANGUAGE.json advanced action create","%tag% &7Введите в чате название нового клана, который вы хотите создать или используйте &c/clan cancel &r&7для отмены!"),
	JSON_ADVANCED_ACTION_DISBAND("LANGUAGE.json advanced action disband","%tag% &7Введите &b&l%confirm_action% &r&7в чат для подтверждения или используйте &c/clan cancel &r&7для отмены!"),
	JSON_ADVANCED_ACTION_CHANGELEADER("LANGUAGE.json advanced action changeleder","%tag% &7Введите &b&l%confirm_action% &r&7в чат для подтверждения или используйте &c/clan cancel &r&7для отмены!"),
	JSON_ADVANCED_ACTION_MODTAG("LANGUAGE.json advanced action modtag","%tag% &7Введите в чат новый Тег Клана или используйте &c/clan cancel &r&7для отмены!"),
	JSON_ADVANCED_ACTION_DESC("LANGUAGE.json advanced action desc","%tag% &7Введите в чат описание клана или используйте &c/clan cancel &r&7для отмены!"),
	JSON_ADVANCED_ACTION_NAME("LANGUAGE.json advanced action name","%tag% &7Введите в чат новое название клана или используйте &c/clan cancel &r&7для отмены!"),
	JSON_ADVANCED_ACTION_INVITE("LANGUAGE.json advanced action invite","%tag% &7Напишите в чат кого вы хотите пригласить или используйте &c/clan cancel &r&7для отмены!"),
	JSON_ADVANCED_INVITE_RECEIVED("LANGUAGE.json simple invite received"," &c&l! &eВы получили приглашение вступить в Клан &f%clan_tag%&e, приглашение истечет через &b%sec_expires% сек&e. &eИспользуйте &b/clan join %clan_tag_nocolor% &eили &b/clan deny %clan_tag_nocolor%"),
	JSON_ADVANCED_HELP_PAGINATION("LANGUAGE.json advanced help pagination"," &cДля следующей страницы используйте: &b/clan help [страница]"),
	
	JSON_SIMPLE_UNKNOWN_COMMAND("LANGUAGE.json simple command unknown","%tag% &cНеизвестная команда, используйте &b/uclan help &cчтобы увидеть список доступных команд."),
	JSON_SIMPLE_UNKNOWN_COMMAND_PLAYER("LANGUAGE.json simple command unknown player","%tag% &cНеизвестная команда, используйте &b/clan help &cчтобы увидеть список доступных команд."),
	JSON_SIMPLE_CLAN_ALLY_RIVAL_LIST_FORMAT("LANGUAGE.json simple clan ally rival list format"," &8%clan_tag% &7- &b%clan_kdr% &7- &b%clan_members_count%"),
	JSON_SIMPLE_CLAN_LISt_FORMAT("LANGUAGE.json simple clan list format"," &a%clan_rank%° &7- &8%clan_tag% &7- &f%clan_desc% &7- &b%clan_kdr% &7- &b%clan_members_count%"),
	JSON_SIMPLE_LIST_NEXT("LANGUAGE.json simple list next"," &bСледующая страница >>"),
	JSON_SIMPLE_LIST_PREV("LANGUAGE.json simple list prev"," << &bПредыдущая страница"),
	JSON_SIMPLE_LIST_CONTROLER("LANGUAGE.json simple list controler"," << &bПредыдущая страница"),
	JSON_SIMPLE_CLAN_DELETED("LANGUAGE.json simple clan deleted"," &a%clan_rank%° &7- &c&mУдалить клан!"), 

	DISABLED_FUNCTION("LANGUAGE.disabled function","%tag% &cЭта функция/аддон, похоже, отключена."), 

	ADMIN_OPENED_CLANCHEST("LANGUAGE.admin opened clanchest","%tag% &cАдмин открыл клановый сундук."),
	TOP_KDR_FORMAT("LANGUAGE.top kdr format","&b%num%º &7| &a%uclans_tag_color% &7| &fKdr: &b%uclans_clan_kdr%"),
	TOP_KILL_FORMAT("LANGUAGE.top kill format","&b%num%º &7| &a%uclans_tag_color% &7| &fУбийств: &b%uclans_clan_kills%"),
	TOP_DEATH_FORMAT("LANGUAGE.top death format","&b%num%º &7| &a%uclans_tag_color% &7| &fСмертей: &b%uclans_clan_deaths%"),
	TOP_MEMBER_FORMAT("LANGUAGE.top member format","&b%num%º &7| &a%uclans_tag_color% &7| &fУчастников: &b%uclans_count_members%"), 
	TOP_BANK_FORMAT("LANGUAGE.top bank format","&b%num%º &7| &a%uclans_tag_color% &7| &fБанк: &b%uclans_bank_balance%"), 
	TOP_LEVEL_FORMAT("LANGUAGE.top level format","&b%num%º &7| &a%uclans_tag_color% &7| &fУровень: &b%uclans_level%"), 
	TOP_WAR_FORMAT("LANGUAGE.top war format","&b%num%º &7| &a%uclans_tag_color% &7| &a%uclans_clan_war_win%&7/&4%uclans_clan_war_lose%"), 
	CLAN_NEW_BALANCE("LANGUAGE.clan new balance","%tag% &aНовйы баланс банка &a$%uclans_bank_balance%&e, изменил &a%uclans_player%"),
	CLAN_QUEST_CHANGE("LANGUAGE.clan quest change","%tag% &aГостевые баллы Клана теперь &b%uclans_quest_points%&e, всего завершено &b%uclans_quest_finished%"), 
	PLAYER_RESETED_KDR("LANGUAGE.player reseted kdr","%tag% &aУ игрока &a%player% &eбыл сброшен KDR!"),
	CLAN_RESETED_KDR("LANGUAGE.clan reseted kdr","%tag% &aУ Клана &a%uclans_tag_color% &eбыл сброшен KDR!"),
	VALUE_GREATER_THAN_ZERO("LANGUAGE.value greater than zero","%tag% &cЗначение должно быть больше чем 0"), 
	CLAN_LEVEL_CHANGE("LANGUAGE.clan level change","%tag% &a&bКлан %clan% &eтеперь на уровне &b%num%"),
	CLAN_NOT_HAVE_LEVELS("LANGUAGE.clan not have levels","%tag% &cУ Клана нет уровней для удаления"), 
	CLAN_HAS_ONLY_LEVELS("LANGUAGE.clan has only levels","%tag% &cУ Клана всего &b%num% &cур."), 
	COMMAND_IN_COOLDOWN("LANGUAGE.command in cooldown","%tag% &cПодождите &b%sec% &cчтобы использовать команду снова."), 

	ERROR_LENGTH("LANGUAGE.error length","%tag% &cЗначение должно иметь длину между &b%min% &cи &b%max%"), 
	KITS_LIST_HEADER("LANGUAGE.kits list header","&9&lСписок наборов:"), 
	KITS_LIST_EMPTY("LANGUAGE.kits list empty"," &c- Нет наборов для отображения"), 
	KITS_LIST_FORMAT("LANGUAGE.kits list format"," &a%kit_name% &7- &7%kit_desc% &7- &fДата: &b%kit_creation_date%"), 
	KIT_NOT_EXISTS("LANGUAGE.kit not exists","%tag% &cНет набора с таким названием."), 
	KIT_ALREADY_EXISTS("LANGUAGE.kit already exists","%tag% &cНабор с таким названием уже есть."), 
	EMPTY_INVENTORY("LANGUAGE.empty inventory","%tag% &cВаш инвентарь не может быть пустым."),
	STATE_TRUE("LANGUAGE.state true","&aENABLED"),
	STATE_FALSE("LANGUAGE.state false","&cDISABLED"), 
	ACCEPTED_VALUES("LANGUAGE.accept type","%tag% &cНедопустимый тип, используйте: &b%types%"), 

	CLAN_REGROUP_INVITE_EXPIRED("LANGUAGE.clan regroup invite expired","%tag% &cСрок приглашения к перегруппировке истек!"), 
	CLAN_REGROUP_INVITE_DOESNOT_EXIST("LANGUAGE.clan regroup invite doesnot exists","%tag% &cЗапрос на перегруппировку не отправлен."), 
	CLAN_REGROUP_INVITE_ALREADY_EXIST("LANGUAGE.clan regroup invite already exists","%tag% &cУже отправлен запрос на перегруппировку."), 
	CLAN_REGROUP_INVITE_DENY("LANGUAGE.clan regroup invite deny","%tag% &cИгрок &a%player% &cотклонил ваш запрос!"), 
	CLAN_REGROUP_INVITE_ACCEPT("LANGUAGE.clan regroup invite accept","%tag% &cИгрок &a%player% &eпринял ваш запрос!"), 
	CLAN_REGROUP_INVITE_ALREADY_DENIED("LANGUAGE.clan regroup invite already denied","%tag% &cВы уже отменили запрос."),
	CLAN_REGROUP_INVITE_ALREADY_ACCEPTED("LANGUAGE.clan regroup invite already accepted","%tag% &cВы уже приняли запрос."), 
	CLAN_HAS_NO_MEMBERS("LANGUAGE.clan has no members","%tag% &cВ вашем клане нет участников."), 
	
	DISABLED_WORLD_REGROUP("LANGUAGE.disabled world regroup","%tag% &cВы не можете отправлять запросы на перегруппировку в этом мире."),
	DISABLED_REGION_REGROUP("LANGUAGE.disabled region regroup","%tag% &cВы не можете отправлять запросы на перегруппировку в этом регионе."), 
	DISABLED_REGION_COMMAND("LANGUAGE.disabled region command","%tag% &cВы не можете использовать эти команды в этом регионе."), 
	
	CLAN_RIVAL_REMOVE_ALREADY_INVITED("LANGUAGE.clan rival remove already invited","%tag% &cУже есть запрос о мире от вашего клана или другого клана, находящегося в процессе, к этому клану, подождите и повторите попытку.!"),  
	CLAN_RIVAL_REMOVE_ERROR("LANGUAGE.clan rival remove error","%tag% &cПроизошла ошибка при отправке запроса!"),  
	CLAN_RIVAL_REMOVE_MODERATION_OFFLINE("LANGUAGE.clan rival remove moderation offline","%tag% &cВ клане нет модераторов или лидеров онлайн."),
	CLAN_RIVAL_REMOVE_SENDED("LANGUAGE.clan rival remove sended","%tag% &aЗапрос на мир отправлен, ждите, пока клан примет или отклонит его."), 
	CLAN_RIVAL_REMOVE_NOT_FOUND("LANGUAGE.clan rival remove not found","%tag% &cПросьбы о мире не поступали."),
	CLAN_RIVAL_REMOVE_DENY("LANGUAGE.clan rival remove deny","%tag% &cВы отклонили просьбу об отмене соперничества."), 
	CLAN_RIVAL_REMOVE_DENY_RECEIVED("LANGUAGE.clan rival remove deny received","%tag% &cКлан отклонил просьбу о мире.."),
	CLAN_RIVAL_REMOVE_EXPIRED("LANGUAGE.clan rival remove expired","%tag% &cСрок действия приглашения к миру истек!"),
	
	CLAN_ALLY_INVITE_NOT_FOUND("LANGUAGE.clan ally invite not found","%tag% &cПредложений о союзе не поступало."),
	CLAN_ALLY_INVITE_DENY("LANGUAGE.clan ally invite deny","%tag% &cВы отклонили предложение о союзе."), 
	CLAN_ALLY_INVITE_ALREADY_INVITED("LANGUAGE.clan ally invite already invited","%tag% &cВ этот клан уже поступило приглашение от вашего или другого клана, подождите и повторите попытку!"), 
	CLAN_ALLY_INVITE_ERROR("LANGUAGE.clan ally invite error","%tag% &cПроизошла ошибка при отправке запроса!"), 
	CLAN_ALLY_INVITE_MODERATION_OFFLINE("LANGUAGE.clan ally invite moderation offline","%tag% &cВ клане нет модераторов или лидеров онлайн."), 
	CLAN_ALLY_INVITE_SENDED("LANGUAGE.clan ally invite sended","%tag% &aПредложение отправлено, ждите, пока клан примет или отклонит его."),
	CLAN_ALLY_INVITE_EXPIRED("LANGUAGE.clan ally invite expired","%tag% &cПриглашение в альянс истекло!"), 
	CLAN_ALLY_INVITE_DENY_RECEIVED("LANGUAGE.clan ally invite deny received","%tag% &cКлан отклонил запрос на союз."), 
	
	CLAN_NOT_HAVE_POINTS("LANGUAGE.clan not have points","%tag% &cКлан не имеет очков для удаления"), 
	CLAN_HAS_ONLY_POINTS("LANGUAGE.clan has only points","%tag% &cУ Клана есть только &b%num% &cочков"), 
	CLAN_ALLY_IN_LIMIT("LANGUAGE.clan ally in limit","%tag% &cВаш клан достиг лимита союзников и должен набрать уровни, чтобы разблокировать больше союзников, Текущий лимит вашего клана составляет &b&l%uclans_limit_ally%"),
	CLAN_RIVAL_IN_LIMIT("LANGUAGE.clan rival in limit","%tag% &cВаш клан достиг лимита соперников и должен набрать уровни, чтобы разблокировать больше соперников, Текущий лимит вашего клана составляет &b&l%uclans_limit_rival%"),
	COMMAND_DEPRECATED("LANGUAGE.command deprecated","%tag% &cЭта команда устарела и может быть удалена из настроек"), 
	CLAN_DOES_NOT_EXISTS("LANGUAGE.chan does not exists", "%tag% &cЭтот клан не существует"),
	NEED_LEVEL_MIN("LANGUAGE.need level min","%tag% &cВаш клан должен иметь как минимум &b&l%level% &cур. для этого!"), 
	DISABLED_REGION_CHEST("LANGUAGE.disabled region chest","%tag% &cВы не можете использовать сундуки в этом регионе.."), 
	PLAYER_LEAVE("LANGUAGE.player_leave","%tag% &cУчастник &b&l%player% &cвышел из сети."), 
	PLAYER_JOIN("LANGUAGE.player_join","%tag% &aУчастник &b&l%player% &aвошёл в сеть."),

	HOME_ALREADY_EXISTS("LANGUAGE.home already exists","%tag% &cУже есть игрок с таким именем."), 
	HOME_CREATE_ERROR("LANGUAGE.home create error","%tag% &cОшибка при создании."), 
	HOME_CREATE_SUCCESS("LANGUAGE.home create success","%tag% &aНовая точка дома создана успешно!"), 
	HOME_NOT_EXISTS("LANGUAGE.home no exists","%tag% &cИгрока с таким именем не существует."), 
	HOME_NOT_EXISTS_GUI("LANGUAGE.home no exists gui","&cС этим домом произошла ошибка."), 
	HOME_DELETE_ERROR("LANGUAGE.home delete error","%tag% &cПроизошла ошибка при удалении."), 
	HOME_DELETE_ERROR_GUI("LANGUAGE.home delete error gui","&cПроизошла ошибка при удалении."), 
	HOME_DELETE_SUCCESS("LANGUAGE.home delete success","%tag% &aТочка дома успешно удален!"), 
	HOME_DELETE_SUCCESS_GUI("LANGUAGE.home delete success gui","&aУспешно удалено!"), 
	HOME_NEW_CREATE("LANGUAGE.new create home","%tag% &aНовая клановая точка успешно создана на сервере &b%server% &aс именем &b%name%"), 
	HOME_REMOVED("LANGUAGE.home removed","%tag% &cТочка дома &b%name% &cсервера &b%server% &cклана была удалена"), 
	DISABLED_WORLD_HOME("LANGUAGE.disabled world command","%tag% &cТочки домов для клановы выключены для этого мира."),
	DISABLED_REGION_HOME("LANGUAGE.disabled region home","%tag% &cТочки домов для клановы выключены для этого региона."), 
	HOME_LIMIT("LANGUAGE.home limit","&cЭто лимит (%limit%) для вашего Клана!"),
	HOME_LIMIT_REACHED("LANGUAGE.home limit reached","%tag% &cЛими для вашего клана - %homes% точек дома."), 
	BANNER_DELETE_ERROR_GUI("LANGUAGE.banner delete error gui","&cОшибка при удалении!"), 
	BANNER_DELETE_SUCCESS_GUI("LANGUAGE.banner delete success gui","&bУспешно удалено!"), 
	BANNER_DELETE_ERROR("LANGUAGE.banner delete error","%tag% &cВозникла ошибка при удалении."), 
	BANNER_DELETE_SUCCESS("LANGUAGE.banner delete success","%tag% &aБаннер успешно удалён!"), 
	BANNER_EMPTY("LANGUAGE.banner empty","%tag% &cУ вашего клана нет Баннера!"), 
	BANNER_EMPTY_GUI("LANGUAGE.banner empty gui","&cУ вашего клана нет Баннера!"),
	BANNER_EMPTY_ITEM("LANGUAGE.banner empty item","&cПредметом должен быть баннер!"), 
	BANNER_NOT_ITEMSTACK("LANGUAGE.banner not itemstack","&cПредметом должен быть Баннер."), 
	BANNER_NOT_BANNER("LANGUAGE.banner not banner","%tag% &cПредметом который вы держите должен быть Баннер"), 
	BANNER_HAND_EMPTY("LANGUAGE.banner hand empty","%tag% &cВам нужно держать баннер в руке."), 
	BANNER_UPLOAD_ERROR_GUI("LANGUAGE.banner upload error gui","&cОшибка при сохранении баннера."), 
	BANNER_UPLOAD_SUCCESS_GUI("LANGUAGE.banner upload success gui","&bНовый баннер сохранён!"),  
	NEW_POINT_RECEIVED("LANGUAGE.new point received","%tag% &aВаш клан получил &b%points% очков&a, и теперь имеет &b%totalpoints% очков"),
	NEW_POINT_REMOVED("LANGUAGE.new point removed","%tag% &cВаш клан потерял &b%points% очков&c, и теперь имеет &b%totalpoints% очков"),
	NEW_POINT_SET("LANGUAGE.new point set","%tag% &aОчки вашего клана были изменены на &b%totalpoints%"), 


	

	GUI("GUI", " ", " ", "# ПЕРЕВОД ФАЙЛОВ ГРАФИЧЕСКОГО ИНТЕРФЕСА МЕНЮ", " "),
	
	
	General_disband_confirm_title("GUI.General disband_confirm title", "&c&lПодтвердите удаление Клана?"),
	General_disband_confirm_items_fill_name("GUI.General disband_confirm items fill name", " "),
	General_disband_confirm_items_fill_lore("GUI.General disband_confirm items fill lore", Arrays.asList()),
	General_disband_confirm_items_confirm_name("GUI.General disband_confirm items confirm name", "&aПодтвердить"),
	General_disband_confirm_items_confirm_lore("GUI.General disband_confirm items confirm lore", Arrays.asList("", " &cНажмите, чтобы подтвердить.")),
	General_disband_confirm_items_cancel_name("GUI.General disband_confirm items cancel name", "&aОтмена"),
	General_disband_confirm_items_cancel_lore("GUI.General disband_confirm items cancel lore", Arrays.asList("", " &eНажмите для отмены.")),
	
	General_changeleader_confirm_title("GUI.General changeleader_confirm title", "&c&lПодтвердите смену лидера Клана?"),
	General_changeleader_confirm_items_fill_name("GUI.General changeleader_confirm items fill name", " "),
	General_changeleader_confirm_items_fill_lore("GUI.General changeleader_confirm items fill lore", Arrays.asList()),
	General_changeleader_confirm_items_confirm_name("GUI.General changeleader_confirm items confirm name", "&aПодтвердить"),
	General_changeleader_confirm_items_confirm_lore("GUI.General changeleader_confirm items confirm lore", Arrays.asList("", " &cНажмите, чтобы подтвердить.")),
	General_changeleader_confirm_items_cancel_name("GUI.General changeleader_confirm items cancel name", "&aCancel"),
	General_changeleader_confirm_items_cancel_lore("GUI.General changeleader_confirm items cancel lore", Arrays.asList("", " &eНажмите для отмены.")),
	
	Home_clan_home_title("GUI.Home clan_home title", "&9&lКлановый Дом"),
	Home_clan_home_items_fill_name("GUI.Home clan_home items fill name", " "),
	Home_clan_home_items_fill_lore("GUI.Home clan_home items fill lore", Arrays.asList()),
	Home_clan_home_items_ally_homes_name("GUI.Home clan_home items ally_homes name", "&aПросмотреть дома союзников"),
	Home_clan_home_items_ally_homes_lore("GUI.Home clan_home items ally_homes lore", Arrays.asList("", " &eНажмите, чтобы открыть.")),
	Home_clan_home_items_create_name("GUI.Home clan_home items create name", "&aСоздать новый дом"),
	Home_clan_home_items_create_lore("GUI.Home clan_home items create lore", Arrays.asList("", " &eНажмите, чтобы создать.")),
	Home_clan_home_items_back_name("GUI.Home clan_home items back name", "&cНазад"),
	Home_clan_home_items_back_lore("GUI.Home clan_home items back lore", Arrays.asList("", " &eНажмите, чтобы вернуться.")),
	Home_clan_home_items_next_name("GUI.Home clan_home items next name", "&aСледующая страница"),
	Home_clan_home_items_next_lore("GUI.Home clan_home items next lore", Arrays.asList("", " &eНажмите, чтобы продолжить.")),
	Home_clan_home_items_previous_name("GUI.Home clan_home items previous name", "&aПредыдущая страница"),
	Home_clan_home_items_previous_lore("GUI.Home clan_home items previous lore", Arrays.asList("", " &eНажмите, чтобы вернуться.")),
	Home_clan_home_items_current_name("GUI.Home clan_home items current name", "&aДом %uclans_home:<num>:name%"),
	Home_clan_home_items_current_lore("GUI.Home clan_home items current lore", Arrays.asList("", " &eИнформация о точке Дома", " &7", " &7Сервер: &a%uclans_home:<num>:server%", " &7Имя: &b%uclans_home:<num>:name%", "", " &eЛевый-Клик для телепортации ", " &cПравый-Клик для удаления.")),
	

	Home_clan_delhome_confirm_title("GUI.Home clan_delhome_confirm title", "&c&lПодтвердите удаление дома &4&l%home_name% &c?"),
	Home_clan_delhome_confirm_items_fill_name("GUI.Home clan_delhome_confirm items fill name", " "),
	Home_clan_delhome_confirm_items_fill_lore("GUI.Home clan_delhome_confirm items fill lore", Arrays.asList()),
	Home_clan_delhome_confirm_items_confirm_name("GUI.Home clan_delhome_confirm items confirm name", "&aПодтвердить"),
	Home_clan_delhome_confirm_items_confirm_lore("GUI.Home clan_delhome_confirm items confirm lore", Arrays.asList(" ", " &eНажмите, чтобы подтвердить.")),
	Home_clan_delhome_confirm_items_cancel_name("GUI.Home clan_delhome_confirm items cancel name", "&aНажмите, чтобы cancel"),
	Home_clan_delhome_confirm_items_cancel_lore("GUI.Home clan_delhome_confirm items cancel lore", Arrays.asList(" ", " &eНажмите для отмены.")),
	
	General_noclan_home_title("GUI.General noclan_home title", "&9&lКлан &7| &cБез клана"),
	General_noclan_home_items_fill_name("GUI.General noclan_home items fill name", " "),
	General_noclan_home_items_fill_lore("GUI.General noclan_home items fill lore", Arrays.asList()),
	General_noclan_home_items_fill2_name("GUI.General noclan_home items fill2 name", " "),
	General_noclan_home_items_fill2_lore("GUI.General noclan_home items fill2 lore", Arrays.asList()),
	General_noclan_home_items_commands_name("GUI.General noclan_home items commands name", "&aСписок Команд и Помощь"),
	General_noclan_home_items_commands_lore("GUI.General noclan_home items commands lore", Arrays.asList(" &eНажмите, чтобы увидеть полный список", "&eдля Кланов и Территорий.")),
	General_noclan_home_items_clans_name("GUI.General noclan_home items clans name", "&aВсе Кланы"),
	General_noclan_home_items_clans_lore("GUI.General noclan_home items clans lore", Arrays.asList(" &eНажмите, чтобы открыть клан-меню.")),
	General_noclan_home_items_create_name("GUI.General noclan_home items create name", "&cYou dont have a Clan"),
	General_noclan_home_items_create_lore("GUI.General noclan_home items create lore", Arrays.asList(" &eНажмите, чтобы создать Клан.")),
	
	General_clan_home_title("GUI.General clan_home title", "&9&lМеню Клана"),
	General_clan_home_items_fill_name("GUI.General clan_home items fill name", " "),
	General_clan_home_items_fill_lore("GUI.General clan_home items fill lore", Arrays.asList()),
	General_clan_home_items_fill2_name("GUI.General clan_home items fill2 name", " "),
	General_clan_home_items_fill2_lore("GUI.General clan_home items fill2 lore", Arrays.asList()),
	
	General_clan_home_items_info_name("GUI.General clan_home items info name", "&aКлан %uclans_tag_color%"),
	General_clan_home_items_info_lore("GUI.General clan_home items info lore", Arrays.asList(" &eИнформация о клане", " &7", " &7Уровень: &a%uclans_level%"," &7Очки: &a%uclans_points%", " &7Банк: &a$%uclans_bank_balance%", " &7", " &7Тег: &b%uclans_tag_color%", " &7Описание: &b%uclans_desc_color%", " ", " &eНажмите, чтобы открыть статус-лист.")),
	General_clan_home_items_banner_name("GUI.General clan_home items banner name", "&aClan Banner"),
	General_clan_home_items_banner_lore("GUI.General clan_home items banner lore", Arrays.asList(" ", " &eИнформация о баннере:", "", " &fЕсть баннер: &b%uclans_hasbanner_formated%"," "," &eБаннер клана - это ваш бренд", "&eи ваш &b&lNEXUS &eиспользует, чтобы отметить территорию!", " &eТолько Лидер или Модераторы могут","&eизменить баннер Клана" )),
	General_clan_home_items_clans_name("GUI.General clan_home items clans name", "&aВсе Кланы"),
	General_clan_home_items_clans_lore("GUI.General clan_home items clans lore", Arrays.asList(" &eНажмите чтобы открыть список кланов.")),
	General_clan_home_items_commands_name("GUI.General clan_home items commands name", "&aСписок Команд и Помощь"),
	General_clan_home_items_commands_lore("GUI.General clan_home items commands lore", Arrays.asList(" &eНажмите, чтобы увидеть полный список", "&eкоманд Кланов и Территорий.")),
	General_clan_home_items_settings_name("GUI.General clan_home items settings name", "&aНастройки Клана"),
	General_clan_home_items_settings_lore("GUI.General clan_home items settings lore", Arrays.asList(" &eНажмите, чтобы открыть.")),
	General_clan_home_items_home_name("GUI.General clan_home items home name", "&aОткрыть меню домов."),
	General_clan_home_items_home_lore("GUI.General clan_home items home lore", Arrays.asList(" &eНажмите, чтобы открыть.")),
	General_clan_home_items_ally_name("GUI.General clan_home items ally name", "&aСоюзы"),
	General_clan_home_items_ally_lore("GUI.General clan_home items ally lore", Arrays.asList(" ", " &7Союзников: &b%uclans_clan_count_ally%", " "," &eНажмите, чтобы открыть меню союзов.")),
	General_clan_home_items_rival_name("GUI.General clan_home items rival name", "&aRivalries"),
	General_clan_home_items_rival_lore("GUI.General clan_home items rival lore", Arrays.asList(" ", " &7Соперников: &b%uclans_clan_count_rival%", " " ," &eНажмите, чтобы открыть меню соперников.")),
	General_clan_home_items_members_name("GUI.General clan_home items members name", "&aClan Members"),
	General_clan_home_items_members_lore("GUI.General clan_home items members lore", Arrays.asList(" "," &7Участников: &b%uclans_count_members%", " ", " &eНажмите, чтобы открыть меню участников.")),

	General_player_profile_title("GUI.General player_profile title", "&9&lПрофиль &7| &a%uclans_player%"),
	General_player_profile_items_head_name("GUI.General player_profile items head name", "&a%uclans_player%"),
	General_player_profile_items_head_lore("GUI.General player_profile items head lore", Arrays.asList("", " &7Клан: &b%uclans_tag_color%", " &7Лидер: &b%uclans_leader%", " ", " &7Никнейм: &b%uclans_player%", " &7KDR: &b%uclans_player_kills%&8/&b%uclans_player_deaths% &8(%uclans_player_kdr%)", " &7Вступил: &b%uclans_player_joindate_formated%", " &7Заходит последний раз: &b%uclans_player_lastsee_formated%" )),
	General_player_profile_items_back_name("GUI.General player_profile items back name", "&cВернуться обратно"),
	General_player_profile_items_back_lore("GUI.General player_profile items back lore", Arrays.asList(" &eНажмите, чтобы вернуться обратно" )),
	General_player_profile_items_fill_name("GUI.General player_profile items fill name", " "),
	General_player_profile_items_fill_lore("GUI.General player_profile items fill lore", Arrays.asList()),
	
	General_clan_stats_title("GUI.General clan_stats title", "&9&lСтатистика &7| %uclans_tag_color%"),
	General_clan_stats_items_fill_name("GUI.General clan_stats items fill name", " "),
	General_clan_stats_items_fill_lore("GUI.General clan_stats items fill lore", Arrays.asList()),
	General_clan_stats_items_back_name("GUI.General clan_stats items back name", "&cВернуться"),
	General_clan_stats_items_back_lore("GUI.General clan_stats items back lore", Arrays.asList(" &eНажмите, чтобы вернуться обратно" )),
	General_clan_stats_items_limits_name("GUI.General clan_stats items limits name", "&aЛимиты Клана:"),
	General_clan_stats_items_limits_lore("GUI.General clan_stats items limits lore", Arrays.asList(" ", "&eПро Лимиты:", " ", " &7Домов: &b%uclans_limit_home%", " &7Союзников: &b%uclans_limit_ally%", " &7Соперников: &b%uclans_limit_rival%", " &7Мест: &b%uclans_slots_total%", " ", " &eЛимиты увеличиваются, когда", "&eклан получает уровни.")),
	General_clan_stats_items_member_rival_ally_name("GUI.General clan_stats items member_rival_ally name", "&aУчастники, Соперники и Союзники:"),
	General_clan_stats_items_member_rival_ally_lore("GUI.General clan_stats items member_rival_ally lore", Arrays.asList(" ", "&eПро участников, соперников и союзников:", " ", " &7Участники: &b%uclans_count_members%", " &7Участников в сети: &b%uclans_count_onlinemembers%", " &7Союзников: &b%uclans_clan_count_ally%", " &7Соперников: &b%uclans_clan_count_rival%")),
	General_clan_stats_items_others_name("GUI.General clan_stats items others name", "&aДругая статистика:"),
	General_clan_stats_items_others_lore("GUI.General clan_stats items others lore", Arrays.asList(" ", "&eДругая:", " ", " &7Участников Вступило: &b%uclans_clan_member_joined%", " &7Участников Покинуло: &b%uclans_clan_member_leave%", " &7Участников Выгнали: &b%uclans_clan_member_kicked%", " &7Изменения тега: &b%uclans_clan_tag_changed%")),
	General_clan_stats_items_status_name("GUI.General clan_stats items status name", "&aСостояние:"),
	General_clan_stats_items_status_lore("GUI.General clan_stats items status lore", Arrays.asList(" ", "&eПро Состояние:", " "," &7Банк: &a$%uclans_bank_balance%", " &7Уровень: &b%uclans_level%", " &7Макс. достигнуый уровень: &b%uclans_max_level_reached%", " &7Очки: &b%uclans_points%", " &7Завершено заданий: &b%uclans_quest_finished%")),
	General_clan_stats_items_war_name("GUI.General clan_stats items war name", "&aWar stats:"),
	General_clan_stats_items_war_lore("GUI.General clan_stats items war lore", Arrays.asList(" ", "&eВойны:", " ", " &7Войн выиграно: &b%uclans_clan_war_win%", " &7Войн проиграно: &b%uclans_clan_war_lose%", " &7Войн всего: &b%uclans_clan_war_total%")),
	General_clan_stats_items_kdr_name("GUI.General clan_stats items kdr name", "&aKDR:"),
	General_clan_stats_items_kdr_lore("GUI.General clan_stats items kdr lore", Arrays.asList(" ", "&eKDR:", " ", " &7Убийств: &b%uclans_clan_kills%", " &7Смертей: &b%uclans_clan_deaths%", " &7KDR: &b%uclans_clan_kdr%")),
	General_clan_stats_items_banner_name("GUI.General clan_stats items banner name", "&aClan Banner"),
	General_clan_stats_items_banner_lore("GUI.General clan_stats items banner lore", Arrays.asList(" ", " &eБаннеры:", "", " &fЕсть Баннер: &b%uclans_hasbanner_formated%" )),
	General_clan_stats_items_foundation_name("GUI.General clan_stats items foundation name", "&aFoundation:"),
	General_clan_stats_items_foundation_lore("GUI.General clan_stats items foundation lore", Arrays.asList(" ", "&eПро основание:", " ", " &7Лидер: &b%uclans_leader%", " &7Дата создания: &b%uclans_creation_date_formated%", " &7Верифицирован: &f%uclans_verified%", " &7Мест: &f%uclans_slots% &8(+%uclans_slots_extra%)", " ", " &7Модероторов (%uclans_count_moderators%):", "  &a%uclans_moderators%" )),
	
	General_clan_settings_title("GUI.General clan_settings title", "&9&lНастройки"),
	General_clan_settings_items_fill_name("GUI.General clan_settings items fill name", " "),
	General_clan_settings_items_fill_lore("GUI.General clan_settings items fill lore", Arrays.asList()),
	General_clan_settings_items_back_name("GUI.General clan_settings items back name", "&cНазад"),
	General_clan_settings_items_back_lore("GUI.General clan_settings items back lore", Arrays.asList(" &eНажмите, чтобы вернуться" )),
	General_clan_settings_items_actions_name("GUI.General clan_settings items actions name", "&aДействия"),
	General_clan_settings_items_actions_lore("GUI.General clan_settings items actions lore", Arrays.asList(" &eНажмите, чтобы открыть.")),
	General_clan_settings_items_delete_name("GUI.General clan_settings items delete name", "&c&lУдалить Клан"),
	General_clan_settings_items_delete_lore("GUI.General clan_settings items delete lore", Arrays.asList(" &eНажмите, чтобы удалить Клан", " &cТолько лидер может сделать это!", " &cЭто удалит защиту с вашей территории", " &cЭто требует подтверждения в ЧАТе!", " ", " &cОсторожно, это действие необратимо!" )),
	General_clan_settings_items_make_banner_name("GUI.General clan_settings items make_banner name", "&aСоздать или Удалить баннер"),
	General_clan_settings_items_make_banner_lore("GUI.General clan_settings items make_banner lore", Arrays.asList(" ", " &eНажмите, чтобы открыть.")),
	General_clan_settings_items_join_leave_name("GUI.General clan_settings items join_leave name", "&aВступить и Покинуть"),
	General_clan_settings_items_join_leave_lore("GUI.General clan_settings items join_leave lore", Arrays.asList(" ", " &fСостояние: %uclans_settings_state:JOINLEAVE%", ""," &eНажмите, чтобы переключить ", " ", " &cКогда отключено, ваш клан больше не будет", "&cвидеть сообщений когда кто-то", "&cвступает или покидает клан.")),
	General_clan_settings_items_ff_name("GUI.General clan_settings items ff name", "&aУрон по своим"),
	General_clan_settings_items_ff_lore("GUI.General clan_settings items ff lore", Arrays.asList(" ", " &fСостояние: %uclans_settings_state:CLANFF%", ""," &eНажмите чтобы переключить ", " ", " &cКогда включено, участники могут", "&cатаковать друг друга.")),
	General_clan_settings_items_allysharedhome_name("GUI.General clan_settings items allysharedhome name", "&aДома Союзников"),
	General_clan_settings_items_allysharedhome_lore("GUI.General clan_settings items allysharedhome lore", Arrays.asList(" ", " &fСостояние: %uclans_settings_state:ALLYSHAREDHOME%", ""," &eНажмите, чтобы переключить ", " ", " &cКогда отключено, дома вашего клана", "&cне появятся в списке у союзников.")),
	General_clan_settings_items_allysharedchat_name("GUI.General clan_settings items allysharedchat name", "&aЧат с союзниками"),
	General_clan_settings_items_allysharedchat_lore("GUI.General clan_settings items allysharedchat lore", Arrays.asList(" ", " &fСостояние: %uclans_settings_state:ALLYSHAREDCHAT%", ""," &eНажмите, чтобы переключить ", " ", " &cКогда отключено, ваш клан не сможет", "&cполучать или отправлять сообщения союзникам.")),
	General_clan_settings_items_warinvite_name("GUI.General clan_settings items warinvite name", "&aПриглашения на Войну"),
	General_clan_settings_items_warinvite_lore("GUI.General clan_settings items warinvite lore", Arrays.asList(" ", " &fСостояние: %uclans_settings_state:WARINVITE%", ""," &eНажмите, чтобы переключить ", " ", " &cКогда отключено, ваш клан", "&cне сможет получать приглашения на Войну" )),

	
	General_clan_actions_title("GUI.General clan_actions title", "&9&lМеню Действий"),
	General_clan_actions_items_fill_name("GUI.General clan_actions items fill name", " "),
	General_clan_actions_items_fill_lore("GUI.General clan_actions items fill lore", Arrays.asList()),
	General_clan_actions_items_back_name("GUI.General clan_actions items back name", "&cНазад"),
	General_clan_actions_items_back_lore("GUI.General clan_actions items back lore", Arrays.asList(" &eНажмите, чтобы вернуться обратно" )),
	General_clan_actions_items_sethome_name("GUI.General clan_actions items sethome name", "&aУстановить клановый Дом"),
	General_clan_actions_items_sethome_lore("GUI.General clan_actions items sethome lore", Arrays.asList(" &eНажмите, чтобы установить клановый дом" )),
	General_clan_actions_items_name_name("GUI.General clan_actions items name name", "&aИзменить название Клана"),
	General_clan_actions_items_name_lore("GUI.General clan_actions items name lore", Arrays.asList(" &eНажмите, чтобы изменить название Клана.")),
	General_clan_actions_items_desc_name("GUI.General clan_actions items desc name", "&aИзменить описание Клана"),
	General_clan_actions_items_desc_lore("GUI.General clan_actions items desc lore", Arrays.asList(" &eНажмите, чтобы изменить описание Клана.")),
	General_clan_actions_items_modtag_name("GUI.General clan_actions items modtag name", "&aИзменить тег Клана"),
	General_clan_actions_items_modtag_lore("GUI.General clan_actions items modtag lore", Arrays.asList(" &eНажмите, чтобы изменить тег Клана" )),
	
	General_clan_top_title("GUI.General clan_top title", "&9&lСписок Кланов &7| %current%"),
	General_clan_top_items_fill_name("GUI.General clan_top items fill name", " "),
	General_clan_top_items_fill_lore("GUI.General clan_top items fill lore", Arrays.asList()),
	General_clan_top_items_active_name("GUI.General clan_top items active name", " &aТекущий"),
	General_clan_top_items_active_lore("GUI.General clan_top items active lore", Arrays.asList()),
	General_clan_top_items_kdr_name("GUI.General clan_top items kdr name", "&cТоп KDR"),
	General_clan_top_items_kdr_lore("GUI.General clan_top items kdr lore", Arrays.asList(" &eClick to order", "&eот лучших по KDR ", " ")),
	General_clan_top_items_kill_name("GUI.General clan_top items kill name", "&cТоп по УБИЙСТВАМ"),
	General_clan_top_items_kill_lore("GUI.General clan_top items kill lore", Arrays.asList(" &eClick to order", "&eот лучших по Убийствам ", " ")),
	General_clan_top_items_death_name("GUI.General clan_top items death name", "&cТоп по СМЕРТЯМ"),
	General_clan_top_items_death_lore("GUI.General clan_top items death lore", Arrays.asList(" &eClick to order", "&eот лучших по Смертям ", " ")),
	General_clan_top_items_bank_name("GUI.General clan_top items bank name", "&cТоп по БАНКУ"),
	General_clan_top_items_bank_lore("GUI.General clan_top items bank lore", Arrays.asList(" &eClick to order", "&eот лучших по Банку ", " ")),
	General_clan_top_items_member_name("GUI.General clan_top items member name", "&cТоп по УЧАСТНИКАМ"),
	General_clan_top_items_member_lore("GUI.General clan_top items member lore", Arrays.asList(" &eClick to order", "&eот лучших по Участникам ", " ")),
	General_clan_top_items_level_name("GUI.General clan_top items level name", "&cТоп по УРОВНЮ"),
	General_clan_top_items_level_lore("GUI.General clan_top items level lore", Arrays.asList(" &eClick to order", "&eот лучших по Уровню ", " ")),
	General_clan_top_items_current_all_name("GUI.General clan_top items current_all name", "&aКлан %uclans_tag_color%"),
	General_clan_top_items_current_all_lore("GUI.General clan_top items current_all lore", Arrays.asList("", " &eИнформация о клане", " &7", " &7Дата создания: &a%uclans_creation_date_formated%", " &7", " &7Тег: &b%uclans_tag_color%", " &7Лидер: &b%uclans_leader%", " &7Участники: &b%uclans_count_members%", "", " &eПравый-Клик для просмотра информации.")),
	General_clan_top_items_current_war_name("GUI.General clan_top items current_war name", "&aClan %uclans_tag_color%"),
	General_clan_top_items_current_war_lore("GUI.General clan_top items current_war lore", Arrays.asList("", " &eИнформация о клане", " &7", " &7Войн выиграно: &a%uclans_clan_war_win%", " &7", " &7Тег: &b%uclans_tag_color%", " &7Лидер: &b%uclans_leader%", " &7Участники: &b%uclans_count_members%", "", " &eПравый-Клик для просмотра информации.")),
	General_clan_top_items_current_bank_name("GUI.General clan_top items current_bank name", "&aClan %uclans_tag_color%"),
	General_clan_top_items_current_bank_lore("GUI.General clan_top items current_bank lore", Arrays.asList("", " &eИнформация о клане", " &7", " &7Bank: &a$%uclans_bank_balance%", " &7", " &7Тег: &b%uclans_tag_color%", " &7Лидер: &b%uclans_leader%", " &7Участники: &b%uclans_count_members%", "", " &eПравый-Клик для просмотра информации.")),
	General_clan_top_items_current_member_name("GUI.General clan_top items current_member name", "&aClan %uclans_tag_color%"),
	General_clan_top_items_current_member_lore("GUI.General clan_top items current_member lore", Arrays.asList("", " &eИнформация о клане", " &7", " &7Участников: &a%uclans_count_members%", " &7", " &7Тег: &b%uclans_tag_color%", " &7Лидер: &b%uclans_leader%", " &7Участники: &b%uclans_count_members%", "", " &eПравый-Клик для просмотра информации.")),
	General_clan_top_items_current_death_name("GUI.General clan_top items current_death name", "&aClan %uclans_tag_color%"),
	General_clan_top_items_current_death_lore("GUI.General clan_top items current_death lore", Arrays.asList("", " &eИнформация о клане", " &7", " &7Deaths: &a%uclans_clan_deaths%", " &7", " &7Тег: &b%uclans_tag_color%", " &7Лидер: &b%uclans_leader%", " &7Участники: &b%uclans_count_members%", "", " &eПравый-Клик для просмотра информации.")),
	General_clan_top_items_current_kill_name("GUI.General clan_top items current_kill name", "&aClan %uclans_tag_color%"),
	General_clan_top_items_current_kill_lore("GUI.General clan_top items current_kill lore", Arrays.asList("", " &eИнформация о клане", " &7", " &7Kills: &a%uclans_clan_kills%", " &7", " &7Тег: &b%uclans_tag_color%", " &7Лидер: &b%uclans_leader%", " &7Участники: &b%uclans_count_members%", "", " &eПравый-Клик для просмотра информации.")),
	General_clan_top_items_current_kdr_name("GUI.General clan_top items current_kdr name", "&aClan %uclans_tag_color%"),
	General_clan_top_items_current_kdr_lore("GUI.General clan_top items current_kdr lore", Arrays.asList("", " &eИнформация о клане", " &7", " &7KDR: &a%uclans_clan_kdr%", " &7", " &7Тег: &b%uclans_tag_color%", " &7Лидер: &b%uclans_leader%", " &7Участники: &b%uclans_count_members%", "", " &eПравый-Клик для просмотра информации.")),
	General_clan_top_items_current_level_name("GUI.General clan_top items current_level name", "&aClan %uclans_tag_color%"),
	General_clan_top_items_current_level_lore("GUI.General clan_top items current_level lore", Arrays.asList("", " &eИнформация о клане", " &7", " &7Уровень: &a%uclans_level%", " &7", " &7Тег: &b%uclans_tag_color%", " &7Лидер: &b%uclans_leader%", " &7Участники: &b%uclans_count_members%", "", " &eПравый-Клик для просмотра информации.")),
	General_clan_top_items_current_name("GUI.General clan_top items current name", "&aClan %uclans_tag_color%"),
	General_clan_top_items_current_lore("GUI.General clan_top items current lore", Arrays.asList("", " &eИнформация о клане", " &7", " &7Уровень: &a%uclans_level%", " &7", " &7Тег: &b%uclans_tag_color%", " &7Лидер: &b%uclans_leader%", " &7Участники: &b%uclans_count_members%", "", " &eПравый-Клик для просмотра информации.")),
	General_clan_top_items_war_name("GUI.General clan_top items war name", "&cТоп по Войнам"),
	General_clan_top_items_war_lore("GUI.General clan_top items war lore", Arrays.asList(" &eНажмите, чтобы упорядочить", "&eсписок по войнам ", " ")),
	General_clan_top_items_all_name("GUI.General clan_top items all name", "&cAll Verified"),
	General_clan_top_items_all_lore("GUI.General clan_top items all lore", Arrays.asList(" &eНажмите, чтобы упорядочить", "&eсписок по Всем кланам ", " ")),
	General_clan_top_items_next_name("GUI.General clan_top items next name", "&aСлед."),
	General_clan_top_items_next_lore("GUI.General clan_top items next lore", Arrays.asList(" &eНажмите, чтобы перейти дальше" )),
	General_clan_top_items_previous_name("GUI.General clan_top items previous name", "&aПред."),
	General_clan_top_items_previous_lore("GUI.General clan_top items previous lore", Arrays.asList(" &eНажмите, чтобы перейти назад" )),
	General_clan_top_items_back_name("GUI.General clan_top items back name", "&cНазад"),
	General_clan_top_items_back_lore("GUI.General clan_top items back lore", Arrays.asList(" &eНажмите, чтобы вернуться обратно" )),

	General_clan_members_title("GUI.General clan_members title", "&9&lМеню Участников"),
	General_clan_members_items_fill_name("GUI.General clan_members items fill name", " "),
	General_clan_members_items_fill_lore("GUI.General clan_members items fill lore", Arrays.asList()),
	General_clan_members_items_fill2_name("GUI.General clan_members items fill2 name", " "),
	General_clan_members_items_fill2_lore("GUI.General clan_members items fill2 lore", Arrays.asList()),
	General_clan_members_items_back_name("GUI.General clan_members items back name", "&cНазад"),
	General_clan_members_items_back_lore("GUI.General clan_members items back lore", Arrays.asList(" &eНажмите, чтобы вернуться обратно" )),
	General_clan_members_items_invite_name("GUI.General clan_members items invite name", "&aПригласить игроков"),
	General_clan_members_items_invite_lore("GUI.General clan_members items invite lore", Arrays.asList(" &eНажмите, чтобы пригласить игроков" )),
	General_clan_members_items_list_name("GUI.General clan_members items list name", "&aСписок Участников"),
	General_clan_members_items_list_lore("GUI.General clan_members items list lore", Arrays.asList(" "," &7Участников: &b%uclans_count_members%", " ", " &eНажмите, чтобы просмотреть участников" )),
	
	General_clan_ally_title("GUI.General clan_ally title", "&9&lМеню Союзов"),
	General_clan_ally_items_fill_name("GUI.General clan_ally items fill name", " "),
	General_clan_ally_items_fill_lore("GUI.General clan_ally items fill lore", Arrays.asList()),
	General_clan_ally_items_fill2_name("GUI.General clan_ally items fill2 name", " "),
	General_clan_ally_items_fill2_lore("GUI.General clan_ally items fill2 lore", Arrays.asList()),
	General_clan_ally_items_back_name("GUI.General clan_ally items back name", "&cНазад"),
	General_clan_ally_items_back_lore("GUI.General clan_ally items back lore", Arrays.asList(" &eНажмите, чтобы вернуться обратно" )),
	General_clan_ally_items_invite_name("GUI.General clan_ally items invite name", "&aДобавить или Удалить союзников"),
	General_clan_ally_items_invite_lore("GUI.General clan_ally items invite lore", Arrays.asList(" &eНажмите, чтобы добавить или удалить союзников" )),
	General_clan_ally_items_list_name("GUI.General clan_ally items list name", "&aСписок Союзов"),
	General_clan_ally_items_list_lore("GUI.General clan_ally items list lore", Arrays.asList(" ", " &7Союзников: &b%uclans_clan_count_ally%", " " ," &eНажмите, чтобы просмотреть список союзов" )),
	
	General_clan_rival_title("GUI.General clan_rival title", "&9&lМеню Соперников"),
	General_clan_rival_items_fill_name("GUI.General clan_rival items fill name", " "),
	General_clan_rival_items_fill_lore("GUI.General clan_rival items fill lore", Arrays.asList()),
	General_clan_rival_items_fill2_name("GUI.General clan_rival items fill2 name", " "),
	General_clan_rival_items_fill2_lore("GUI.General clan_rival items fill2 lore", Arrays.asList()),
	General_clan_rival_items_back_name("GUI.General clan_rival items back name", "&cНазад"),
	General_clan_rival_items_back_lore("GUI.General clan_rival items back lore", Arrays.asList(" &eНажмите, чтобы вернуться обратно" )),
	General_clan_rival_items_invite_name("GUI.General clan_rival items invite name", "&aДобавить или Удалить соперников"),
	General_clan_rival_items_invite_lore("GUI.General clan_rival items invite lore", Arrays.asList(" &eНажмите, чтобы добавить или удалить соперников" )),
	General_clan_rival_items_list_name("GUI.General clan_rival items list name", "&aСписок Соперников"),
	General_clan_rival_items_list_lore("GUI.General clan_rival items list lore", Arrays.asList(" ", " &7Соперников: &b%uclans_clan_count_rival%", " " ," &eНажмите, чтобы просмотреть список соперников" )),

	Pagination_rival_title("GUI.Pagination rival title", "&9&lСписок Соперников."),
	Pagination_rival_items_fill_name("GUI.Pagination rival items fill name", " "),
	Pagination_rival_items_fill_lore("GUI.Pagination rival items fill lore", Arrays.asList()),
	Pagination_rival_items_back_name("GUI.Pagination rival items back name", "&cНазад"),
	Pagination_rival_items_back_lore("GUI.Pagination rival items back lore", Arrays.asList("", " &eНажмите, чтобы вернуться обратно.")),
	Pagination_rival_items_next_name("GUI.Pagination rival items next name", "&aСледующая страница"),
	Pagination_rival_items_next_lore("GUI.Pagination rival items next lore", Arrays.asList("", " &eНажмите, чтобы перейти на следующую страницу.")),
	Pagination_rival_items_previous_name("GUI.Pagination rival items previous name", "&aПредыдущая страница"),
	Pagination_rival_items_previous_lore("GUI.Pagination rival items previous lore", Arrays.asList("", " &eНажмите, чтобы вернуться обратно.")),
	Pagination_rival_items_current_name("GUI.Pagination rival items current name", "&aКлан %uclans_tag_color%"),
	Pagination_rival_items_current_lore("GUI.Pagination rival items current lore", Arrays.asList("", " &eИнформация о клане", " &7", " &7Уровень: &a%uclans_level%", " &7", " &7Тег: &b%uclans_tag_color%", " &7Лидер: &b%uclans_leader%", " &7Участники: &b%uclans_count_members%", "", " &eПравый-Клик чтобы посмотреть информацию.")),
	
	Pagination_ally_title("GUI.Pagination ally title", "&9&lСписок Союзников."),
	Pagination_ally_items_fill_name("GUI.Pagination ally items fill name", " "),
	Pagination_ally_items_fill_lore("GUI.Pagination ally items fill lore", Arrays.asList()),
	Pagination_ally_items_back_name("GUI.Pagination ally items back name", "&cНазад"),
	Pagination_ally_items_back_lore("GUI.Pagination ally items back lore", Arrays.asList("", " &eНажмите, чтобы вернуться обратно.")),
	Pagination_ally_items_next_name("GUI.Pagination ally items next name", "&aСледующая страница"),
	Pagination_ally_items_next_lore("GUI.Pagination ally items next lore", Arrays.asList("", " &eНажмите, чтобы перейти на следующую страницу.")),
	Pagination_ally_items_previous_name("GUI.Pagination ally items previous name", "&aПредыдущая страница"),
	Pagination_ally_items_previous_lore("GUI.Pagination ally items previous lore", Arrays.asList("", " &eНажмите, чтобы вернуться обратно.")),
	Pagination_ally_items_current_name("GUI.Pagination ally items current name", "&aClan %uclans_tag_color%"),
	Pagination_ally_items_current_lore("GUI.Pagination ally items current lore", Arrays.asList("", " &eИнформация о клане", " &7", " &7Уровень: &a%uclans_level%", " &7", " &7Тег: &b%uclans_tag_color%", " &7Лидер: &b%uclans_leader%", " &7Участников: &b%uclans_count_members%", "", " &eПравый-Клик чтобы посмотреть информацию.")),
	
	Pagination_members_title("GUI.Pagination members title", "&9&lСписок Участников."),
	Pagination_members_items_fill_name("GUI.Pagination members items fill name", " "),
	Pagination_members_items_fill_lore("GUI.Pagination members items fill lore", Arrays.asList()),
	Pagination_members_items_back_name("GUI.Pagination members items back name", "&cНазад"),
	Pagination_members_items_back_lore("GUI.Pagination members items back lore", Arrays.asList("", " &eНажмите, чтобы вернуться обратно.")),
	Pagination_members_items_next_name("GUI.Pagination members items next name", "&aСледующая страница"),
	Pagination_members_items_next_lore("GUI.Pagination members items next lore", Arrays.asList("", " &eНажмите, чтобы перейти на следующую страницу.")),
	Pagination_members_items_previous_name("GUI.Pagination members items previous name", "&aПредыдущая страница"),
	Pagination_members_items_previous_lore("GUI.Pagination members items previous lore", Arrays.asList("", " &eНажмите, чтобы вернуться обратно")),
	Pagination_members_items_current_name("GUI.Pagination members items current name", "&a%uclans_player%"),
	Pagination_members_items_current_lore("GUI.Pagination members items current lore", Arrays.asList("", " &7Лидер: &b%uclans_player_leader_yes_no%", " &7Модераторы: &b%uclans_player_mod_yes_no%", " &7Никнейм: &b%uclans_player%", " &7Kdr: &b%uclans_player_kills%&8/&b%uclans_player_deaths% &8(%uclans_player_kdr%)", " &7Вступил: &b%uclans_player_joindate_formated%", " &7Последний раз заходил: &b%uclans_player_lastsee_formated%", " ", " &eНажмите, чтобы увидеть информацию.")),
	
	Pagination_clans_title("GUI.Pagination clans title", "&9&lВерифицированные кланы."),
	Pagination_clans_items_fill_name("GUI.Pagination clans items fill name", " "),
	Pagination_clans_items_fill_lore("GUI.Pagination clans items fill lore", Arrays.asList()),
	Pagination_clans_items_back_name("GUI.Pagination clans items back name", "&cНазад"),
	Pagination_clans_items_back_lore("GUI.Pagination clans items back lore", Arrays.asList("", " &eНажмите, чтобы вернуться обратно.")),
	Pagination_clans_items_next_name("GUI.Pagination clans items next name", "&aСледующая страница"),
	Pagination_clans_items_next_lore("GUI.Pagination clans items next lore", Arrays.asList("", " &eНажмите, чтобы перейти дальше.")),
	Pagination_clans_items_previous_name("GUI.Pagination clans items previous name", "&aПредыдущая страница"),
	Pagination_clans_items_previous_lore("GUI.Pagination clans items previous lore", Arrays.asList("", " &eНажмите, чтобы вернуться обратно.")),
	Pagination_clans_items_current_name("GUI.Pagination clans items current name", "&aКлан %uclans_tag_color%"),
	Pagination_clans_items_current_lore("GUI.Pagination clans items current lore", Arrays.asList("", " &eИнформация о клане", " &7", " &7Уровень: &a%uclans_level%", " &7", " &7Тег: &b%uclans_tag_color%", " &7Лидер: &b%uclans_leader%", " &7Участников: &b%uclans_count_members%", "", " &eПравый-Клик для просмотра инфомарции.")),

	Home_clan_allyhome_title("GUI.Home clan_allyhome title", "&9&lДома Союзников"),
	Home_clan_allyhome_items_back_name("GUI.Home clan_allyhome items back name", "&cНазад"),
	Home_clan_allyhome_items_back_lore("GUI.Home clan_allyhome items back lore", Arrays.asList("", " &eНажмите, чтобы вернуться обратно.")),
	Home_clan_allyhome_items_next_name("GUI.Home clan_allyhome items next name", "&aСледующая страница"),
	Home_clan_allyhome_items_next_lore("GUI.Home clan_allyhome items next lore", Arrays.asList("", " &eНажмите, чтобы перейти дальше.")),
	Home_clan_allyhome_items_previous_name("GUI.Home clan_allyhome items previous name", "&aПредыдущая страница"),
	Home_clan_allyhome_items_previous_lore("GUI.Home clan_allyhome items previous lore", Arrays.asList("", " &eНажмите, чтобы вернуться обратно.")),
	Home_clan_allyhome_items_current_name("GUI.Home clan_allyhome items current name", "&aHome %uclans_home:<num>:name% of clan %uclans_tag_color%."),
	Home_clan_allyhome_items_current_lore("GUI.Home clan_allyhome items current lore", Arrays.asList("", " &eИнформация о домах", " &7", " &7Клан: &b%uclans_tag_color%", " &7Сервер: &a%uclans_home:<num>:server%", " &7Название: &b%uclans_home:<num>:name%", "", " &eЛевый-Клик для телепортации.")),
	Home_clan_allyhome_items_fill_name("GUI.Home clan_allyhome items fill name", " "),
	Home_clan_allyhome_items_fill_lore("GUI.Home clan_allyhome items fill lore", Arrays.asList()),
	
	Banner_banner_home_title("GUI.Banner banner_home title", "&9&lМеню Баннера"),
	Banner_banner_home_items_fill_name("GUI.Banner banner_home items fill name", " "),
	Banner_banner_home_items_fill_lore("GUI.Banner banner_home items fill lore", Arrays.asList()),
	Banner_banner_home_items_fill2_name("GUI.Banner banner_home items fill2 name", " "),
	Banner_banner_home_items_fill2_lore("GUI.Banner banner_home items fill2 lore", Arrays.asList()),
	Banner_banner_home_items_current_name("GUI.Banner banner_home items current name", "&aТекущий Баннер"),
	Banner_banner_home_items_current_lore("GUI.Banner banner_home items current lore", Arrays.asList(" "," &eБаннер Клана - это ваш бренд","&eи ваш &b&lNEXUS &eиспользует его для маркировки территории!","", " &b&l<< &cИспользуй кнопки по бокам &b&l>>" )),
	Banner_banner_home_items_upload_name("GUI.Banner banner_home items upload name", "&aЗагрузить"),
	Banner_banner_home_items_upload_lore("GUI.Banner banner_home items upload lore", Arrays.asList("", " &eНажмите, чтобы открыть меню загрузки.")),
	Banner_banner_home_items_delete_name("GUI.Banner banner_home items delete name", "&aУдалить Баннер"),
	Banner_banner_home_items_delete_lore("GUI.Banner banner_home items delete lore", Arrays.asList("", " &eНажмите, чтобы удалить баннер.")),
	Banner_banner_home_items_pre_name("GUI.Banner banner_home items pre name", "&aЗаготовленные баннеры."),
	Banner_banner_home_items_pre_lore("GUI.Banner banner_home items pre lore", Arrays.asList("", " &eНажмите, чтобы открыть список.")),
	Banner_banner_home_items_back_name("GUI.Banner banner_home items back name", "&cНазад"),
	Banner_banner_home_items_back_lore("GUI.Banner banner_home items back lore", Arrays.asList("", " &eНажмите, чтобы вернуться обратно.")),
	
	Banner_banner_delete_title("GUI.Banner banner_delete title", "&cПодтвердите удаление текущего баннера?"),
	Banner_banner_delete_items_fill_name("GUI.Banner banner_delete items fill name", " "),
	Banner_banner_delete_items_fill_lore("GUI.Banner banner_delete items fill lore", Arrays.asList()),
	Banner_banner_delete_items_confirm_name("GUI.Banner banner_delete items confirm name", "&aПодтвердить"),
	Banner_banner_delete_items_confirm_lore("GUI.Banner banner_delete items confirm lore", Arrays.asList("", " &cНажмите, чтобы подтвердить.")),
	Banner_banner_delete_items_cancel_name("GUI.Banner banner_delete items cancel name", "&aCancel"),
	Banner_banner_delete_items_cancel_lore("GUI.Banner banner_delete items cancel lore", Arrays.asList("", " &eНажмите для отмены.")),
	
	Banner_banner_upload_title("GUI.Banner banner_upload title", "&9&lЗагрузка Баннера"),
	Banner_banner_upload_items_fill_name("GUI.Banner banner_upload items fill name", " "),
	Banner_banner_upload_items_fill_lore("GUI.Banner banner_upload items fill lore", Arrays.asList()),
	Banner_banner_upload_items_fill2_name("GUI.Banner banner_upload items fill2 name", "&cПоместите баннер здесь!"),
	Banner_banner_upload_items_fill2_lore("GUI.Banner banner_upload items fill2 lore", Arrays.asList(" ", " &cПоместите свой новый баннер здесь!")),
	Banner_banner_upload_items_back_name("GUI.Banner banner_upload items back name", "&cНазад"),
	Banner_banner_upload_items_back_lore("GUI.Banner banner_upload items back lore", Arrays.asList("", " &cНажмите, чтобы вернуться обратно.")),
	Banner_banner_upload_items_confirm_name("GUI.Banner banner_upload items confirm name", "&aНажмите, чтобы сохранить."),
	Banner_banner_upload_items_confirm_lore("GUI.Banner banner_upload items confirm lore", Arrays.asList("", " &eНажмите, чтобы сохранить баннер.")),
	
	
	
	COMMANDS("COMMANDS", " ", " ", " ", " # ПЕРЕВОДЫ КОМАНД", " "),

	//CLAN COMMANDS
	
	COMMANDS_clan_help_show_on_help("COMMANDS.clan help show on_help", " &b/clan help &7-&e Показать меню помощи."),
	COMMANDS_clan_help_show_on_help_json_hover_text("COMMANDS.clan help show on_help_json hover_text", "&aНажмите, чтобы увидеть меню помощи."),
	COMMANDS_clan_help_show_on_success("COMMANDS.clan help show on_success", "%tag% &aВы видите помощь!"),
	COMMANDS_clan_help_show_on_error("COMMANDS.clan help show on_error", "%tag%&cОшибка при отображении текста."),
	COMMANDS_clan_help_show_on_usage("COMMANDS.clan help show on_usage", "%tag% &cИспользуй &b/clan help"),
	
	COMMANDS_clan_create_show_on_help_json_hover_text("COMMANDS.clan create show on_help_json hover_text", "&aНажмите, чтобы создать новый клан."),
	COMMANDS_clan_create_show_on_help("COMMANDS.clan create show on_help", " &b/clan create &7-&e Создать новый Клан."),
	COMMANDS_clan_create_show_on_success("COMMANDS.clan create show on_success", "%tag% &aВы создали новый клан!"),
	COMMANDS_clan_create_show_on_error("COMMANDS.clan create show on_error", "%tag% &cОшибка при создании клана, попробуйте еще раз."),
	COMMANDS_clan_create_show_on_usage("COMMANDS.clan create show on_usage", "%tag% &cИспользуйте &b/clan create <тег>"),
	
	COMMANDS_clan_cancel_show_on_help_json_hover_text("COMMANDS.clan cancel show on_help_json hover_text", "&aНажмите, чтобы отменить ожидающие действия."),
	COMMANDS_clan_cancel_show_on_help("COMMANDS.clan cancel show on_help", " &b/clan cancel &7-&e Отменить ожидающие действия."),
	COMMANDS_clan_cancel_show_on_success("COMMANDS.clan cancel show on_success", "%tag% &aУспешно отменено!!"),
	COMMANDS_clan_cancel_show_on_error("COMMANDS.clan cancel show on_error", "%tag% &cОшибка при отмене"),
	COMMANDS_clan_cancel_show_on_usage("COMMANDS.clan cancel show on_usage", "%tag% &cИспользуйте &b/clan cancel"),
	
	COMMANDS_clan_changeleader_show_on_help_json_hover_text("COMMANDS.clan changeleader show on_help_json hover_text", "&aНажмите, чтобы передать лидерство."),
	COMMANDS_clan_changeleader_show_on_help("COMMANDS.clan changeleader show on_help", " &b/clan changeleader <игрок> &7-&e Передать лидерство."),
	COMMANDS_clan_changeleader_show_on_success("COMMANDS.clan changeleader show on_success", "%tag% &aВы изменили лидерство клана %clan_leader%"),
	COMMANDS_clan_changeleader_show_on_error("COMMANDS.clan changeleader show on_error", "%tag% &cОшибка при передаче лидерства."),
	COMMANDS_clan_changeleader_show_on_usage("COMMANDS.clan changeleader show on_usage", "%tag% &cИспользуйте &b/clan changeleader <игрок>"),
	
	COMMANDS_clan_desc_show_on_help("COMMANDS.clan desc show on_help", " &b/clan desc &7-&e Добавить описание для Клана."),
	COMMANDS_clan_desc_show_on_help_json_hover_text("COMMANDS.clan desc show on_help_json hover_text", "&aНажмите, чтобы добавить/изменить описание клана."),
	COMMANDS_clan_desc_show_on_success("COMMANDS.clan desc show on_success", "%tag% &aВы изменили описание клана!"),
	COMMANDS_clan_desc_show_on_error("COMMANDS.clan desc show on_error", "%tag% &cОшибка при изменении описания клана."),
	COMMANDS_clan_desc_show_on_usage("COMMANDS.clan desc show on_usage", "%tag% &cИспользуйте &b/clan desc <description>"),
	
	COMMANDS_clan_disband_show_on_help("COMMANDS.clan disband show on_help", " &b/clan disband &7-&e Удалить ваш Клан."),
	COMMANDS_clan_disband_show_on_help_json_hover_text("COMMANDS.clan disband show on_help_json hover_text", "&aНажмите, чтобы удалить ваш Клан."),
	COMMANDS_clan_disband_show_on_success("COMMANDS.clan disband show on_success", "%tag% &aВы удалили ваш Клан!"),
	COMMANDS_clan_disband_show_on_error("COMMANDS.clan disband show on_error", "%tag% &cОшибка при удалении, попробуйте ещё раз."),
	COMMANDS_clan_disband_show_on_usage("COMMANDS.clan disband show on_usage", "%tag% &cИспользуйте &b/clan disband CONFIRM"),
	
	COMMANDS_clan_leave_show_on_help("COMMANDS.clan leave show on_help", " &b/clan leave &7-&e Покинуть Клан."),
	COMMANDS_clan_leave_show_on_help_json_hover_text("COMMANDS.clan leave show on_help_json hover_text", "&aНажмите, чтобы покинуть клан."),
	COMMANDS_clan_leave_show_on_success("COMMANDS.clan leave show on_success", "%tag% &aВы покинули клан!"),
	COMMANDS_clan_leave_show_on_error("COMMANDS.clan leave show on_error", "%tag% &cОшибка при покидании клана, попробуйте еще раз."),
	COMMANDS_clan_leave_show_on_usage("COMMANDS.clan leave show on_usage", "%tag% &cИспользуйте &b/clan leave"),
	
	COMMANDS_clan_invite_show_on_help("COMMANDS.clan invite show on_help", " &b/clan invite <игрок> &7-&e Пригласить Игрока в ваш клан."),
	COMMANDS_clan_invite_show_on_help_json_hover_text("COMMANDS.clan invite show on_help_json hover_text", "&aНажмите, чтобы отправить приглашение игроку"),
	COMMANDS_clan_invite_show_on_success("COMMANDS.clan invite show on_success", "%tag% &aПриглашение было отправлено игроку, ожидайте!"),
	COMMANDS_clan_invite_show_on_error("COMMANDS.clan invite show on_error", "%tag% &cОшибка при приглашении игрока."),
	COMMANDS_clan_invite_show_on_usage("COMMANDS.clan invite show on_usage", "%tag% &cИспользуйте &b/clan invite <игрок>"),
	

	COMMANDS_clan_join_show_on_help("COMMANDS.clan join show on_help", " &b/clan join <тег> &7- &eПринять приглашение в клан."),
	COMMANDS_clan_join_show_on_help_json_hover_text("COMMANDS.clan join show on_help_json hover_text", "&aНажмите, чтобы принять приглашение."),
	COMMANDS_clan_join_show_on_success("COMMANDS.clan join show on_success", "%tag% &aВы приняли приглашение в клан!"),
	COMMANDS_clan_join_show_on_error("COMMANDS.clan join show on_error", "%tag% &cОшибка при входе в клан, попробуйте еще раз."),
	COMMANDS_clan_join_show_on_usage("COMMANDS.clan join show on_usage", "%tag% &cИспользуйте &b/clan join <тег>"),
	
	COMMANDS_clan_deny_show_on_help("COMMANDS.clan deny show on_help", " &b/clan deny <тег> &7- &eОтклонить приглашение в клан."),
	COMMANDS_clan_deny_show_on_help_json_hover_text("COMMANDS.clan deny show on_help_json hover_text", "&aНажмите, чтобы cancel invite."),
	COMMANDS_clan_deny_show_on_success("COMMANDS.clan deny show on_success", "%tag% &aВы отклонили приглашение в клан!"),
	COMMANDS_clan_deny_show_on_error("COMMANDS.clan deny show on_error", "%tag% &cОшибка при попытке отклонить приглашение в клан."),
	COMMANDS_clan_deny_show_on_usage("COMMANDS.clan deny show on_usage", "%tag% &cИспользуйте &b/clan deny <тег>"),
	
	COMMANDS_clan_kick_show_on_help("COMMANDS.clan kick show on_help", " &b/clan kick <игрок> &7-&e Выгнать игрока из клана."),
	COMMANDS_clan_kick_show_on_help_json_hover_text("COMMANDS.clan kick show on_help_json hover_text", "&aНажмите, чтобы выгнать игрока из клана."),
	COMMANDS_clan_kick_show_on_success("COMMANDS.clan kick show on_success", "%tag% &aИгрок был выгнан из клана."),
	COMMANDS_clan_kick_show_on_error("COMMANDS.clan kick show on_error", "%tag% &cОшибка при попытке выгнать игрока из клана."),
	COMMANDS_clan_kick_show_on_usage("COMMANDS.clan kick show on_usage", "%tag% &cИспользуйте &b/clan kick <игрок>"),
	
	COMMANDS_clan_promote_show_on_help("COMMANDS.clan promote show on_help", " &b/clan promote <игрок> &7-&e Повысить игрока до модератора клана."),
	COMMANDS_clan_promote_show_on_help_json_hover_text("COMMANDS.clan promote show on_help_json hover_text", "&aНажмите, чтобы повысить игрока."),
	COMMANDS_clan_promote_show_on_success("COMMANDS.clan promote show on_success", "%tag% &aИгрок повышен до модератора клана."),
	COMMANDS_clan_promote_show_on_error("COMMANDS.clan promote show on_error", "%tag% &cОшибка при повышении игрока, попробуйте еще раз."),
	COMMANDS_clan_promote_show_on_usage("COMMANDS.clan promote show on_usage", "%tag% &cИспользуйте &b/clan promote <игрок>"),
	
	COMMANDS_clan_demote_show_on_help("COMMANDS.clan demote show on_help", " &b/clan demote <игрок> &7-&e понизить игрока из клана."),
	COMMANDS_clan_demote_show_on_help_json_hover_text("COMMANDS.clan demote show on_help_json hover_text", "&aНажмите, чтобы понизить игрока."),
	COMMANDS_clan_demote_show_on_success("COMMANDS.clan demote show on_success", "%tag% &aИгрок в клане был понижен."),
	COMMANDS_clan_demote_show_on_error("COMMANDS.clan demote show on_error", "%tag% &cОшибка при понижении игрока, попробуйте еще раз"),
	COMMANDS_clan_demote_show_on_usage("COMMANDS.clan demote show on_usage", "%tag% &cИспользуйте &b/clan demote <игрок>"),
	
	COMMANDS_clan_home_show_on_help("COMMANDS.clan home show on_help", " &b/clan home <create|delete|list|teleport> <название> &7-&e Телепортироваться в клановый дом."),
	COMMANDS_clan_home_show_on_help_json_hover_text("COMMANDS.clan home show on_help_json hover_text", "&aНажмите, чтобы телепортироваться в клановый дом."),
	COMMANDS_clan_home_show_on_success("COMMANDS.clan home show on_success", "%tag% &aВы были телепортированы в клановый дом!"),
	COMMANDS_clan_home_show_on_error("COMMANDS.clan home show on_error", "%tag% &cОшибка при телепортировании в клановый дом."),
	COMMANDS_clan_home_show_on_usage("COMMANDS.clan home show on_usage", "%tag% &cИспользуйте &b/clan home <create|delete|list|teleport> <название>"),
	
	COMMANDS_clan_chat_show_on_help("COMMANDS.clan chat show on_help", " &b/clan chat &7-&e Переключите чат на клановый или используйте &b/  <сообщение>"),
	COMMANDS_clan_chat_show_on_help_json_hover_text("COMMANDS.clan chat show on_help_json hover_text", "&aНажмите, чтобы переключить чат на клановый."),
	COMMANDS_clan_chat_show_on_success("COMMANDS.clan chat show on_success", "%tag% &aЧат переключен на: &b%player_chat%"),
	COMMANDS_clan_chat_show_on_error("COMMANDS.clan chat show on_error", "%tag% &cОшибка при использовании чата."),
	COMMANDS_clan_chat_show_on_usage("COMMANDS.clan chat show on_usage", "%tag% &cИспользуйте &b/clan chat"),
	
	COMMANDS_clan_ff_show_on_help("COMMANDS.clan ff show on_help", " &b/clan ff &7-&e переключить урон по своим в клане."),
	COMMANDS_clan_ff_show_on_help_json_hover_text("COMMANDS.clan ff show on_help_json hover_text", "&aНажмите, чтобы переключить урон по своим в клане."),
	COMMANDS_clan_ff_show_on_success("COMMANDS.clan ff show on_success", "%tag% &aУрон по своим был изменен на &b%clan_ff%"),
	COMMANDS_clan_ff_show_on_error("COMMANDS.clan ff show on_error", "%tag% &cОшибка при попытке переключить огонь по своим."),
	COMMANDS_clan_ff_show_on_usage("COMMANDS.clan ff show on_usage", "%tag% &cИспользуйте &b/clan ff"),

	COMMANDS_clan_modtag_show_on_help("COMMANDS.clan modtag show on_help", " &b/clan modtag <новыйТег> &7-&e Изменить тег клана."),
	COMMANDS_clan_modtag_show_on_help_json_hover_text("COMMANDS.clan modtag show on_help_json hover_text", "&aНажмите, чтобы change Tag."),
	COMMANDS_clan_modtag_show_on_success("COMMANDS.clan modtag show on_success", "%tag% &aТег клана изменен на &b%clan_tag%"),
	COMMANDS_clan_modtag_show_on_error("COMMANDS.clan modtag show on_error", "%tag% &cОшибка при попытке изменить название клана."),
	COMMANDS_clan_modtag_show_on_usage("COMMANDS.clan modtag show on_usage", "%tag% &cИспользуйте &b/clan modtag <новыйТег>"),
	
	COMMANDS_clan_list_show_on_help("COMMANDS.clan list show on_help", " &b/clan list &7-&e Список всех Кланов."),
	COMMANDS_clan_list_show_on_help_json_hover_text("COMMANDS.clan list show on_help_json hover_text", "&aНажмите, чтобы увидеть все кланы."),
	COMMANDS_clan_list_show_on_success("COMMANDS.clan list show on_success", "%tag% &aСписок успешно открыт."),
	COMMANDS_clan_list_show_on_error("COMMANDS.clan list show on_error", "%tag% &cОшибка при попытке открыть список кланов."),
	COMMANDS_clan_list_show_on_usage("COMMANDS.clan list show on_usage", "%tag% &cИспользуйте &b/clan list"),
	
	COMMANDS_clan_info_show_on_help("COMMANDS.clan info show on_help", " &b/clan info [тег] &7-&e Показать информацию о клане."),
	COMMANDS_clan_info_show_on_help_json_hover_text("COMMANDS.clan info show on_help_json hover_text", "&aНажмите, чтобы показать информацию о клане."),
	COMMANDS_clan_info_show_on_success("COMMANDS.clan info show on_success", ""),
	COMMANDS_clan_info_show_on_error("COMMANDS.clan info show on_error", "%tag% &cОшибка при просмотре информации о клане."),
	COMMANDS_clan_info_show_on_usage("COMMANDS.clan info show on_usage", "%tag% &cИспользуйте &b/clan info [тег]"),
	
	COMMANDS_clan_profile_show_on_help("COMMANDS.clan profile show on_help", " &b/clan profile [игрок] &7-&e Показать профиль игрока в клане."),
	COMMANDS_clan_profile_show_on_help_json_hover_text("COMMANDS.clan profile show on_help_json hover_text", "&aНажмите, чтобы показать профиль."),
	COMMANDS_clan_profile_show_on_success("COMMANDS.clan profile show on_success", "%tag% &aПрофиль успешно открыт."),
	COMMANDS_clan_profile_show_on_error("COMMANDS.clan profile show on_error", "%tag% &cОшибка при попытке просмотра профиля игрока."),
	COMMANDS_clan_profile_show_on_usage("COMMANDS.clan profile show on_usage", "%tag% &cИспользуйте &b/clan profile [игрок]"),
	
	COMMANDS_clan_rival_show_on_help("COMMANDS.clan rival show on_help", " &b/clan rival <add/remove> <тег> &7-&e Добавить клан в соперники."),
	COMMANDS_clan_rival_show_on_help_json_hover_text("COMMANDS.clan rival show on_help_json hover_text", "&aНажмите, чтобы добавить/удалить клан из соперников."),
	COMMANDS_clan_rival_show_on_success("COMMANDS.clan rival show on_success", "%tag% &aСписок соперников обновлен."),
	COMMANDS_clan_rival_show_on_error("COMMANDS.clan rival show on_error", "%tag% &cОшибка при попытке обновить статус соперника."),
	COMMANDS_clan_rival_show_on_usage("COMMANDS.clan rival show on_usage", "%tag% &cИспользуйте &b/clan rival <add/remove> <тег>."),
	
	COMMANDS_clan_rivalries_show_on_help("COMMANDS.clan rivalries show on_help", " &b/clan rivalries &7-&e Список соперников"),
	COMMANDS_clan_rivalries_show_on_help_json_hover_text("COMMANDS.clan rivalries show on_help_json hover_text", "&aНажмите, чтобы показать список соперников."),
	COMMANDS_clan_rivalries_show_on_success("COMMANDS.clan rivalries show on_success", "%tag% &aСписок успешно открыт."),
	COMMANDS_clan_rivalries_show_on_error("COMMANDS.clan rivalries show on_error", "%tag% &cОшибка при попытке показать список соперников."),
	COMMANDS_clan_rivalries_show_on_usage("COMMANDS.clan rivalries show on_usage", "%tag% &cИспользуйте &b/clan rivalries"),
	
	COMMANDS_clan_ally_show_on_help("COMMANDS.clan ally show on_help", " &b/clan ally <add/remove/accept/deny> <тег> &7-&e союзники клана (добавить/удалить/принять/отклонить)."),
	COMMANDS_clan_ally_show_on_help_json_hover_text("COMMANDS.clan ally show on_help_json hover_text", "&aНажмите, чтобы добавить/удалить клан как союзный."),
	COMMANDS_clan_ally_show_on_success("COMMANDS.clan ally show on_success", "%tag% &aСписок союзников обновлен."),
	COMMANDS_clan_ally_show_on_error("COMMANDS.clan ally show on_error", "%tag% &cОшибка при использовании /clan ally."),
	COMMANDS_clan_ally_show_on_usage("COMMANDS.clan ally show on_usage", "%tag% &cИспользуйте &b/clan ally <add/remove/accept/deny> <тег>."),
	
	COMMANDS_clan_alliances_show_on_help("COMMANDS.clan alliances show on_help", " &b/clan alliances &7-&e Список союзников."),
	COMMANDS_clan_alliances_show_on_help_json_hover_text("COMMANDS.clan alliances show on_help_json hover_text", "&aНажмите, чтобы показать список союзных кланов."),
	COMMANDS_clan_alliances_show_on_success("COMMANDS.clan alliances show on_success", "%tag% &aСписок успешно открыт."),
	COMMANDS_clan_alliances_show_on_error("COMMANDS.clan alliances show on_error", "%tag% &cОшибка при использовании списка союзников."),
	COMMANDS_clan_alliances_show_on_usage("COMMANDS.clan alliances show on_usage", "%tag% &cИспользуйте &b/clan alliances."),
	
	COMMANDS_clan_members_show_on_help("COMMANDS.clan members show on_help", " &b/clan members &7-&e Показать список участников."),
	COMMANDS_clan_members_show_on_help_json_hover_text("COMMANDS.clan members show on_help_json hover_text", "&aНажмите, чтобы показать список участников клана."),
	COMMANDS_clan_members_show_on_success("COMMANDS.clan members show on_success", "%tag% &aСписок участников открыт."),
	COMMANDS_clan_members_show_on_error("COMMANDS.clan members show on_error", "%tag% &cОшибка при попытке показать список участников."),
	COMMANDS_clan_members_show_on_usage("COMMANDS.clan members show on_usage", "%tag% &cИспользуйте &6/clan members"),
	
	COMMANDS_clan_settings_show_on_help("COMMANDS.clan settings show on_help", " &b/clan settings <ТИП> <ЗНАЧЕНИЕ> &7-&e Изменить клановые параметры."),
	COMMANDS_clan_settings_show_on_help_json_hover_text("COMMANDS.clan settings show on_help_json hover_text", "&aНажмите, чтобы изменить клановые настройки"),
	COMMANDS_clan_settings_show_on_success("COMMANDS.clan settings show on_success", "%tag% &aКлановые настройки изменены &b%type%&7:&b%value%"),
	COMMANDS_clan_settings_show_on_error("COMMANDS.clan settings show on_error", "%tag% &cВозникла ошибка при попытке изменить настройки клана."),
	COMMANDS_clan_settings_show_on_usage("COMMANDS.clan settings show on_usage", "%tag% &cИспользуйте &b/clan settings <ТИП> <ЗНАЧЕНИЕ>"),
	
	COMMANDS_clan_regroup_show_on_help("COMMANDS.clan regroup show on_help", " &b/clan regroup <send/accept/deny> &7-&e Регруппировать клан"),
	COMMANDS_clan_regroup_show_on_help_json_hover_text("COMMANDS.clan regroup show on_help_json hover_text", "&aНажмите, чтобы регруппировать клан"),
	COMMANDS_clan_regroup_show_on_success("COMMANDS.clan regroup show on_success", "%tag% &aЗапрос на регруппировку был отправлен."),
	COMMANDS_clan_regroup_show_on_error("COMMANDS.clan regroup show on_error", "%tag% &cВозникла ошибка при попытке регруппировать клан."),
	COMMANDS_clan_regroup_show_on_usage("COMMANDS.clan regroup show on_usage", "%tag% &cИспользуйте &b/clan regroup <send/accept/deny>"),
	
	COMMANDS_clan_banner_show_on_help("COMMANDS.clan banner show on_help", " &b/clan banner <open|send|delete> &7-&e баннер клана"),
	COMMANDS_clan_banner_show_on_help_json_hover_text("COMMANDS.clan banner show on_help_json hover_text", "&aНажмите, чтобы изменить клановый баннер"),
	COMMANDS_clan_banner_show_on_success("COMMANDS.clan banner show on_success", "%tag% &aНовый баннер успешно применен!"),
	COMMANDS_clan_banner_show_on_error("COMMANDS.clan banner show on_error", "%tag% &cОшибка при сохранении баннера."),
	COMMANDS_clan_banner_show_on_usage("COMMANDS.clan banner show on_usage", "%tag% &cИспользуйте &b/clan banner <open|send|delete>"),
	
	// UCLANS COMMANDS
	COMMANDS_uclan_help_show_on_help("COMMANDS.uclan help show on_help", " &4/uclan help &7-&e Показать меню помощи."),
	COMMANDS_uclan_help_show_on_help_json_hover_text("COMMANDS.uclan help show on_help_json hover_text", "&aНажмите, чтобы показать помощь по Кланам."),
	COMMANDS_uclan_help_show_on_success("COMMANDS.uclan help show on_success", "%tag% &aПомощь успешно открыта."),
	COMMANDS_uclan_help_show_on_error("COMMANDS.uclan help show on_error", "%tag% &cОшибка при попытке получить помощь по кланам"),
	COMMANDS_uclan_help_show_on_usage("COMMANDS.uclan help show on_usage", "%tag% &cИспользуйте &b/uclan help"),
	
	COMMANDS_uclan_chatspy_show_on_help("COMMANDS.uclan chatspy show on_help", " &4/uclan chatspy &7-&e Подглядывать сообщения в клан-чатах"),
	COMMANDS_uclan_chatspy_show_on_help_json_hover_text("COMMANDS.uclan chatspy show on_help_json hover_text", "&aНажмите, чтобы подглядывать в клан-чатах"),
	COMMANDS_uclan_chatspy_show_on_success("COMMANDS.uclan chatspy show on_success", "%tag% &aШпионство в кланах: %state%"),
	COMMANDS_uclan_chatspy_show_on_error("COMMANDS.uclan chatspy show on_error", "%tag% &cОшибка при попытке переключить шпионство в клан-чатах."),
	COMMANDS_uclan_chatspy_show_on_usage("COMMANDS.uclan chatspy show on_usage", "%tag% &cИспользуйте &4/uclan chatspy"),
	
	COMMANDS_uclan_addslot_show_on_help("COMMANDS.uclan addslot show on_help", " &4/uclan addslot <игрок|тег> <кол-во> &7-&e Добавить места для клана."),
	COMMANDS_uclan_addslot_show_on_help_json_hover_text("COMMANDS.uclan addslot show on_help_json hover_text", "&aНажмите, чтобы добавить места для клана"),
	COMMANDS_uclan_addslot_show_on_success("COMMANDS.uclan addslot show on_success", "%tag% &aВы добавили места (%num%) в %clan% клан"),
	COMMANDS_uclan_addslot_show_on_error("COMMANDS.uclan addslot show on_error", "%tag% &cВозникла ошибка при попытке добавить места клану."),
	COMMANDS_uclan_addslot_show_on_usage("COMMANDS.uclan addslot show on_usage", "%tag% &cИспользуйте &4/uclan addslot <игрок|тег> <кол-во>"),
	
	COMMANDS_uclan_setslot_show_on_help("COMMANDS.uclan setslot show on_help", " &4/uclan setslot <игрок|тег> <кол-во> &7-&e Установить кол-во мест для клана."),
	COMMANDS_uclan_setslot_show_on_help_json_hover_text("COMMANDS.uclan setslot show on_help_json hover_text", "&aНажмите, чтобы установить кол-во мест для клана"),
	COMMANDS_uclan_setslot_show_on_success("COMMANDS.uclan setslot show on_success", "%tag% &aВы установили места (%num%) клану %clan%"),
	COMMANDS_uclan_setslot_show_on_error("COMMANDS.uclan setslot show on_error", "%tag% &cВозникла ошибка при попытке установить кол-во мест клану."),
	COMMANDS_uclan_setslot_show_on_usage("COMMANDS.uclan setslot show on_usage", "%tag% &cИспользуйте &4/uclan setslot <игрок|тег> <кол-во>"),
	
	COMMANDS_uclan_removeslot_show_on_help("COMMANDS.uclan removeslot show on_help", " &4/uclan removeslot <игрок|тег> <кол-во> &7-&e Удалить места в клане."),
	COMMANDS_uclan_removeslot_show_on_help_json_hover_text("COMMANDS.uclan removeslot show on_help_json hover_text", "&aНажмите, чтобы удалить места в клане"),
	COMMANDS_uclan_removeslot_show_on_success("COMMANDS.uclan removeslot show on_success", "%tag% &aВы удалили места (%num%) клану %clan%"),
	COMMANDS_uclan_removeslot_show_on_error("COMMANDS.uclan removeslot show on_error", "%tag% &cВозникла ошибка при попытке удалить места клану."),
	COMMANDS_uclan_removeslot_show_on_usage("COMMANDS.uclan removeslot show on_usage", "%tag% &cИспользуйте &4/uclan removeslot <игрок|тег> <кол-во>"),
	
	COMMANDS_uclan_addpoints_show_on_help("COMMANDS.uclan addpoints show on_help", " &4/uclan addpoints <игрок|тег> <кол-во> &7-&e Добавить очки для клана."),
	COMMANDS_uclan_addpoints_show_on_help_json_hover_text("COMMANDS.uclan addpoints show on_help_json hover_text", "&aНажмите, чтобы добавить очки для клана"),
	COMMANDS_uclan_addpoints_show_on_success("COMMANDS.uclan addpoints show on_success", "%tag% &aВы добавили очки (%num%) клану %clan%"),
	COMMANDS_uclan_addpoints_show_on_error("COMMANDS.uclan addpoints show on_error", "%tag% &cОшибка при попытке добавить очки клану."),
	COMMANDS_uclan_addpoints_show_on_usage("COMMANDS.uclan addpoints show on_usage", "%tag% &cИспользуйте &4/uclan addpoints <игрок|тег> <кол-во>"),
	
	COMMANDS_uclan_setpoints_show_on_help("COMMANDS.uclan setpoints show on_help", " &4/uclan setpoints <игрок|тег> <кол-во> &7-&e установить очки для клана."),
	COMMANDS_uclan_setpoints_show_on_help_json_hover_text("COMMANDS.uclan setpoints show on_help_json hover_text", "&aНажмите, чтобы установить очки для клана"),
	COMMANDS_uclan_setpoints_show_on_success("COMMANDS.uclan setpoints show on_success", "%tag% &aYou have set %num% points to the %clan% clan"),
	COMMANDS_uclan_setpoints_show_on_error("COMMANDS.uclan setpoints show on_error", "%tag% &cThere was an error adding."),
	COMMANDS_uclan_setpoints_show_on_usage("COMMANDS.uclan setpoints show on_usage", "%tag% &cИспользуйте &4/uclan setpoints <игрок|тег> <кол-во>"),
	
	COMMANDS_uclan_removepoints_show_on_help("COMMANDS.uclan removepoints show on_help", " &4/uclan removepoints <игрок|тег> <кол-во> &7-&e Удалить очки клану."),
	COMMANDS_uclan_removepoints_show_on_help_json_hover_text("COMMANDS.uclan removepoints show on_help_json hover_text", "&aНажмите, чтобы удалить очки клану"),
	COMMANDS_uclan_removepoints_show_on_success("COMMANDS.uclan removepoints show on_success", "%tag% &aВы удалили очки (%num%) клану %clan%"),
	COMMANDS_uclan_removepoints_show_on_error("COMMANDS.uclan removepoints show on_error", "%tag% &cОшибка при попытке удалить очки клану."),
	COMMANDS_uclan_removepoints_show_on_usage("COMMANDS.uclan removepoints show on_usage", "%tag% &cИспользуйте &4/uclan removepoints <игрок|тег> <кол-во>"),
	
	
	COMMANDS_uclan_changetag_show_on_help("COMMANDS.uclan changetag show on_help", " &4/uclan changetag <тег> <новыйТег> &7-&e Изменить клану тег."),
	COMMANDS_uclan_changetag_show_on_help_json_hover_text("COMMANDS.uclan changetag show on_help_json hover_text", "&aНажмите, чтобы изменить клану тег."),
	COMMANDS_uclan_changetag_show_on_success("COMMANDS.uclan changetag show on_success", "%tag% &aКлановый тег &b%clan% &aбыл изменен на &b%newtag%"),
	COMMANDS_uclan_changetag_show_on_error("COMMANDS.uclan changetag show on_error", "%tag% &cОшибка при попытке изменить клан тег."),
	COMMANDS_uclan_changetag_show_on_usage("COMMANDS.uclan changetag show on_usage", "%tag% &cИспользуйте &4/uclan changetag <тег> <новыйТег>"),
	
	COMMANDS_uclan_resetplayerkdr_show_on_help("COMMANDS.uclan resetplayerkdr show on_help", " &4/uclan resetplayerkdr <игрок> &7-&e Сбросить KDR для игрока."),
	COMMANDS_uclan_resetplayerkdr_show_on_help_json_hover_text("COMMANDS.uclan resetplayerkdr show on_help_json hover_text", "&aНажмите, чтобы сброить игроку KDR"),
	COMMANDS_uclan_resetplayerkdr_show_on_success("COMMANDS.uclan resetplayerkdr show on_success", "%tag% &aВы сбросили KDR для игрока &a%player%"),
	COMMANDS_uclan_resetplayerkdr_show_on_error("COMMANDS.uclan resetplayerkdr show on_error", "%tag% &cОшибка при попытке сбросить KDR игроку"),
	COMMANDS_uclan_resetplayerkdr_show_on_usage("COMMANDS.uclan resetplayerkdr show on_usage", "%tag% &cИспользуйте &4/uclan resetplayerkdr <игрок>"),
	
	COMMANDS_uclan_resetclankdr_show_on_help("COMMANDS.uclan resetclankdr show on_help", " &4/uclan resetclankdr <тег> &7-&e Сбросить KDR клану."),
	COMMANDS_uclan_resetclankdr_show_on_help_json_hover_text("COMMANDS.uclan resetclankdr show on_help_json hover_text", "&aНажмите, чтобы сбросить KDR для клана"),
	COMMANDS_uclan_resetclankdr_show_on_success("COMMANDS.uclan resetclankdr show on_success", "%tag% &aВы бросили KDR для клана &a%uclans_tag_color%"),
	COMMANDS_uclan_resetclankdr_show_on_error("COMMANDS.uclan resetclankdr show on_error", "%tag% &cОшибка при попытке сбросить KDR для клана"),
	COMMANDS_uclan_resetclankdr_show_on_usage("COMMANDS.uclan resetclankdr show on_usage", "%tag% &cИспользуйте &4/uclan resetclankdr <тег>"),
	
	COMMANDS_uclan_globalff_show_on_help("COMMANDS.uclan globalff show on_help", " &4/uclan globalff &7-&e Изменить глобальный урон по игрокам."),
	COMMANDS_uclan_globalff_show_on_help_json_hover_text("COMMANDS.uclan globalff show on_help_json hover_text", "&aНажмите, чтобы переключить глобальный урон по игрокам"),
	COMMANDS_uclan_globalff_show_on_success("COMMANDS.uclan globalff show on_success", "%tag% &aВы изменили глобальный урон по игрокам на &b%globalff%"),
	COMMANDS_uclan_globalff_show_on_error("COMMANDS.uclan globalff show on_error", "%tag% &cОшибка при попытке переключить глобальный урон по игрокам."),
	COMMANDS_uclan_globalff_show_on_usage("COMMANDS.uclan globalff show on_usage", "%tag% &cИспользуйте &4/uclan globalff"),
	
	COMMANDS_uclan_delete_show_on_help("COMMANDS.uclan delete show on_help", " &4/uclan delete <тег> &7-&e Удалить клан."),
	COMMANDS_uclan_delete_show_on_help_json_hover_text("COMMANDS.uclan delete show on_help_json hover_text", "&aНажмите, чтобы удалить клан."),
	COMMANDS_uclan_delete_show_on_success("COMMANDS.uclan delete show on_success", "%tag% &aВы удалили клан!"),
	COMMANDS_uclan_delete_show_on_error("COMMANDS.uclan delete show on_error", "%tag% &cОшибка при удалении клана."),
	COMMANDS_uclan_delete_show_on_usage("COMMANDS.uclan delete show on_usage", "%tag% &cИспользуйте &4/uclan delete <тег>"),
	
	COMMANDS_uclan_forcejoin_show_on_help("COMMANDS.uclan forcejoin show on_help", " &4/uclan forcejoin <игрок> <тег> &7-&e Добавить игрока в клан."),
	COMMANDS_uclan_forcejoin_show_on_help_json_hover_text("COMMANDS.uclan forcejoin show on_help_json hover_text", "&aНажмите, чтобы добавить игрока в клан."),
	COMMANDS_uclan_forcejoin_show_on_success("COMMANDS.uclan forcejoin show on_success", "%tag% &aВы добавили игрока в клан!"),
	COMMANDS_uclan_forcejoin_show_on_error("COMMANDS.uclan forcejoin show on_error", "%tag% &cОшибка при попытке добавить игрока в клан."),
	COMMANDS_uclan_forcejoin_show_on_usage("COMMANDS.uclan forcejoin show on_usage", "%tag% &cИспользуйте &4/uclan forcejoin <игрок> <тег>"),
	
	COMMANDS_uclan_verify_show_on_help("COMMANDS.uclan verify show on_help", " &4/uclan verify <тег> &7-&e Верифицировать клан."),
	COMMANDS_uclan_verify_show_on_help_json_hover_text("COMMANDS.uclan verify show on_help_json hover_text", "&aНажмите, чтобы верифицировать клан."),
	COMMANDS_uclan_verify_show_on_success("COMMANDS.uclan verify show on_success", "%tag% &aВы переключили верификацию для клана!"),
	COMMANDS_uclan_verify_show_on_error("COMMANDS.uclan verify show on_error", "%tag% &cError checking the clan."),
	COMMANDS_uclan_verify_show_on_usage("COMMANDS.uclan verify show on_usage", "%tag% &cИспользуйте &4/uclan verify <тег>"),
	
	COMMANDS_uclan_reload_show_on_help("COMMANDS.uclan reload show on_help", " &4/uclan reload &7-&e Перезагрузить плагин."),
	COMMANDS_uclan_reload_show_on_help_json_hover_text("COMMANDS.uclan reload show on_help_json hover_text", "&aНажмите, чтобы перезагрузить плагин."),
	COMMANDS_uclan_reload_show_on_success("COMMANDS.uclan reload show on_success", "%tag% &aПлагин успешно перезагружен &7(%time%)."),
	COMMANDS_uclan_reload_show_on_error("COMMANDS.uclan reload show on_error", "%tag% &cОшибка при попытке перезагрузить плагин."),
	COMMANDS_uclan_reload_show_on_usage("COMMANDS.uclan reload show on_usage", "%tag% &cИспользуйте &4/uclan reload"), 
	
	COMMANDS_uclan_reloadaddons_show_on_help("COMMANDS.uclan reloadaddons show on_help", " &4/uclan reloadaddons &7-&e Перезагрузить аддоны."),
	COMMANDS_uclan_reloadaddons_show_on_help_json_hover_text("COMMANDS.uclan reloadaddons show on_help_json hover_text", "&aНажмите, чтобы перезагрузить аддоны."),
	COMMANDS_uclan_reloadaddons_show_on_success("COMMANDS.uclan reloadaddons show on_success", "%tag% &aАддоны успешно перезагружены! &7(%time%)."),
	COMMANDS_uclan_reloadaddons_show_on_error("COMMANDS.uclan reloadaddons show on_error", "%tag% &cОшибка при перезагрузке аддонов."),
	COMMANDS_uclan_reloadaddons_show_on_usage("COMMANDS.uclan reloadaddons show on_usage", "%tag% &cИспользуйте &4/uclan reloadaddons"), 

	;
	
	private String path;
    private Object defaultValue;
    private String[] comments; 

    Lang(String path, Object defaultValue, String... comments) {
        this.path = path;
        this.defaultValue = defaultValue;
        this.comments = comments;
    }

    @Override
    public String getPath() {
    	
        return path;
    }

    @Override
    public Object getDefaultValue() {
        return defaultValue;
    }

    @Override
    public String[] getComments() {
        return comments;
    }

    
}