package me.ulrich.clans.manager.EnumFiles.es_us;

import java.util.Arrays;
import me.ulrich.clans.packets.methods.enums.interfaces.ConfigurationEnum;

public enum Lang implements ConfigurationEnum  {
	
	LANGUAGE("LANGUAGE", " ", " ", " ", " # TRANSLATIONS OF THE LANGUAGE AND DIALOGUE FILES", " "),
	
	TAG("LANGUAGE.tag", "&6&lU&9&lClanes &r&7|"),
	COMMAND_BY_PLAYER("LANGUAGE.command by player","%tag% &cEste comando debe ser utilizado por un jugador."),
	COMMAND_BY_CONSOLE("LANGUAGE.command by console","%tag% &cEste comando debe ser utilizado por la CONSOLA."),

	EMPTY_CHAT_HELP("LANGUAGE.empty chat help","%tag% &cError, Usa &b/. <mensaje>"),
	DISABLED_WORLD_COMMAND("LANGUAGE.disabled world command","%tag% &cLos comandos del clan están desactivados en este mundo."),
	ERROR_START_ACTION("LANGUAGE.error start action","%tag% &cHubo un error al ejecutar esto."),
	ERROR_CHARACTER("LANGUAGE.error character","%tag% &cEsto contiene caracteres inválidos."),
	ERROR_MOD_DESC("LANGUAGE.error mod desc","%tag% &cError al cambiar la descripción del clan."),
	HAS_GLOBALFF("LANGUAGE.has globalff","%tag% &a¡El fuego amigo global está activo!"),
	NO_PERMISSION("LANGUAGE.no permission","%tag% &cNo tienes permiso"), 
	CHEST_EXTRA_BUYED_UPDATE("LANGUAGE.chest extra buyed update","%tag% &b%player% &aha comprado un nuevo cofre para el clan."), 
	REGION_LIST_HEADER("LANGUAGE.region list header","&9&lLista de regiones:"), 
	REGION_LIST_EMPTY("LANGUAGE.region list empty","&8 - No hay regiones guardadas"), 
	REGION_LIST_FORMAT("LANGUAGE.region list format"," &b%region_name% &7- %region_creator% &7- &b%region_firstpoint%&7/&b%region_secondpoint%"),
	REGION_NOT_EXISTS("LANGUAGE.region not exists","%tag% &cNo hay ninguna región con este nombre."),
	REGION_EXISTS("LANGUAGE.region exists","%tag% &cYa existe una región con este nombre."),
	CLAN_TAG_IN_USE("LANGUAGE.tag in use","%tag% &cEsta etiqueta ya está en uso."),
	CLAN_NOT_FOUND("LANGUAGE.clan not found","%tag% &cClan con este ETIQUETA no existe."),
	CLAN_ALLY_HEADER("LANGUAGE.clan ally header","&9&lLista de aliados. &8(tag/kdr/members)"), 
	CLAN_LIST_EMPTY("LANGUAGE.clan list empty"," &cNo hay ningún clan en esta lista."), 
	CLAN_IS_YOUR_CLAN("LANGUAGE.clan is your clan","%tag% &cEste es tu clan."), 
	CLAN_IS_RIVAL("LANGUAGE.clan is rival","%tag% &cEste Clan ya es un rival."), 
	CLAN_ALREADY_ALLY("LANGUAGE.clan already ally","%tag% &cEste Clan ya es un aliado."), 
	CLAN_DONT_ALLY("LANGUAGE.clan dont ally","%tag% &cEste Clan no es un aliado."), 
	CLAN_PLAYER_ISNOT_YOUR_CLAN("LANGUAGE.clan player isnot your clan","%tag% &cEste jugador no está en tu clan."), 
	CLAN_MAX_MEMBERS("LANGUAGE.clan max members","&cEste Clan ya tiene el número máximo de jugadores."), 
	CLAN_MAX_MEMBERS_LEVEL("LANGUAGE.clan max members level","%tag% &cEste clan ya tiene el número máximo de jugadores para el nivel actual."), 
	CLAN_PLAYER_KICKED_OUT("LANGUAGE.clan player kicked out","%tag% &aHas sido expulsado del clan &b%clan% &cpor &a%clan_leader%"),
	CLAN_PLAYER_KICKED_OUTBY("LANGUAGE.clan player kicked outby","%tag% &4%player% &eHa sido expulsado del clan por &a%clan_leader%"), 
	CLAN_TAG_EQUALS("LANGUAGE.clan tag equals","%tag% &cETIQUETA sin cambios, parece ser la misma."),
	CLAN_NAME_EQUALS("LANGUAGE.clan name equals","%tag% &cNOMBRE SIN CAMBIAR, parece ser el mismo."), 
	CLAN_ALREADY_RIVAL("LANGUAGE.clan already rival","%tag% &cEste Clan ya es un rival."), 
	CLAN_IS_ALLY("LANGUAGE.clan is ally","%tag% &cEste Clan ya es un aliado."), 
	CLAN_RIVAL_ERROR_ADD("LANGUAGE.clan rival error add","%tag% &cError al añadir al rival."), 
	CLAN_RIVAL_ERROR_REMOVE("LANGUAGE.clan rival error remove","%tag% &cError al eliminar el rival."), 
	CLAN_DONT_RIVAL("LANGUAGE.clan dont rival","%tag% &cEste Clan no es un rival."), 
	CLAN_NEW_ALLY("LANGUAGE.clan new ally","%tag% &c&l! &eSe formó una nueva alianza con el clan &a%clan_tag%"), 
	CLAN_REMOVED_ALLY("LANGUAGE.clan removed ally","%tag% &c&l! &eLa alianza con el clan &a%clan_tag% &ese ha eliminado."), 
	CLAN_ONE_REMOVED_ALLY("LANGUAGE.clan one removed ally","%tag% &c&l! &eSe ha eliminado una alianza."), 
	CLAN_ONE_REMOVED_RIVAL("LANGUAGE.clan one removed rival","%tag% &c&l! &eSe ha eliminado a un rival."),
	CLAN_CREATED("LANGUAGE.clan created","%tag% &c&l! &eUn nuevo clan &b%clan_tag% &eha sido creado por &a%player%."), 
	CLAN_DELETED("LANGUAGE.clan deleted","%tag% &c&l! &eEl Clan &b%clan_tag% &efue eliminado por &a%player%."), 
	CLAN_DELETED_SMALL("LANGUAGE.clan deleted small","&c&mEliminado"), 
	CLAN_FF_CHANGED("LANGUAGE.clan ff changed","%tag% &c&l! &eEl fuego amigo es &b%value%."), 
	CLAN_GLOBALFF_CHANGED("LANGUAGE.clan globalff changed","%tag% &c&l! &eEl fuego amigo global es &b%value%."), 
	CLAN_NEW_JOIN("LANGUAGE.clan new join","%tag% &c&l! &eEl jugador &a%player% &eentró en el clan."),
	CLAN_NEW_KICK("LANGUAGE.clan new kick","%tag% &c&l! &eEl jugador &a%player% &efue expulsado del Clan."), 
	CLAN_NEW_RIVAL("LANGUAGE.clan new rival","%tag% &c&l! &eNueva rivalidad con el Clan &a%clan_tag%"), 
	CLAN_NEW_LEADER("LANGUAGE.clan new leader","%tag% &c&l! &eEl nuevo líder del clan &a%clan_tag% &ees &a%player%"),
	CLAN_RIVAL_REMOVED("LANGUAGE.clan rival removed","%tag% &c&l! &eLa rivalidad con el Clan &a%clan_tag% &eha sido eliminada."), 
	CLAN_VERIFY_CHANGED("LANGUAGE.clan verify changed","%tag% &c&l! &eEl clan fue cambiado a &a%value%."), 
	CLAN_NEW_PROMOTE("LANGUAGE.clan new promote","%tag% &c&l! &eEl jugador &a%player% &eha ascendido."), 
	CLAN_NEW_DEMOTE("LANGUAGE.clan new demote","%tag% &c&l! &cEl jugador &a%player% &efue degradado."), 
	CLAN_PVP_DISABLED("LANGUAGE.clan pvp disabled","%tag% &cEl PVP del clan ahora está desactivado."),
	CLAN_ALLYPVP_DISABLED("LANGUAGE.clan allypvp disabled","%tag% &cPVP entre aliados está desactivado."),
	CLAN_TAG_BLACKLIST("LANGUAGE.clan tag blacklist","%tag% &cEsta etiqueta no se puede usar en los clanes."),
	CLAN_CHANGED_SETTINGS("LANGUAGE.clan changed settings","%tag% &aSe ha cambiado la configuración del clan."),
	
	CLAN_SETTINGS_WARINVITE("LANGUAGE.clan settings warinvite","&bInvitación de guerra"),
	CLAN_SETTINGS_ALLYSHAREDCHAT("LANGUAGE.clan settings allysharedchat","&bChat aliado compartido"),
	CLAN_SETTINGS_JOINLEAVE("LANGUAGE.clan settings joinleave","&bÚnirse y salir"),
	CLAN_SETTINGS_ALLYSHAREDHOME("LANGUAGE.clan settings allysharedhome","&bHome aliado compartido"),
	CLAN_SETTINGS_CLANFF("LANGUAGE.clan settings clanff","&bClan FF"),
	
	CLAN_DELETE_ERROR_GUI("LANGUAGE.clan delete error gui","&4¡Error al eliminar!"), 
	CLAN_NO_ACTIONS("LANGUAGE.clan no actions","%tag% &cNo hay acciones pendientes para cancelar."), 
	HELP_UCLAN_HEADER("LANGUAGE.help uclan header","&4&lAyuda para el administrador del clan:"), 
	HELP_CLAN_HEADER("LANGUAGE.help clan header","&9&lAyuda con el clan:"), 
	HELP_INFO_HEADER("LANGUAGE.help info header","&9&lInformación del clan &8%clan_tag%&9&l:"), 
	HELP_INFO_EMPTY("LANGUAGE.help info empty","&cNada aquí"), 
	HELP_CLANLIST("LANGUAGE.help clanlist","&9&lLista de clanes: &8(rank/tag/desc/kdr/members)"),
	HELP_CLANLIST_SUBHEADER("LANGUAGE.help clanlist subheader"," &8Mostrar %cur%/%amount% de %total% (Página: %pag_cur%/%pag_max%)"),
	HELP_PROFILE_HEADER("LANGUAGE.help profile header","&9&lPerfil de &a%player%&9&l:"),

	HELP_RIVAL_HEADER("LANGUAGE.help rival header","&9&lLista de rivales &8(tag/kdr/members)"), 
	HELP_STATS_HEADER("LANGUAGE.help stats header","&9&lEstado del clan &a%clan_tag%&9&l:"),
	HELP_STATS_FORMAT_PLAYER("LANGUAGE.help stats format player","  &7&a%list_player% &7- &b%list_player_role% &7- &b%list_player_kills%&8/&b%list_player_deaths% &8(%list_player_kdr%) &7[%list_player_seen_date%]"),
	
	TRANSLACTION_PLAYER("LANGUAGE.translaction players","Jugadores"), 
	TRANSLACTION_IS_ON("LANGUAGE.translaction is on","&a&lEn línea"), 
	TRANSLACTION_IS_OFF("LANGUAGE.translaction is off","&c&lDesconectado"), 
	TRANSLACTION_YES("LANGUAGE.translaction yes","&b&lSÍ"),
	TRANSLACTION_NO("LANGUAGE.translaction no","&c&lNO"),
	
	
	PLAYER_DONT_LEADER("LANGUAGE.clan dont leader","%tag% &cNo eres el líder del clan."),
	PLAYER_DONT_PERMISSION_TO_DEMOTE("LANGUAGE.clan dont permission top demote","%tag% &cNo puedes degradar jugadores."), 
	PLAYER_DONT_PERMISSION_TO_PROMOTE("LANGUAGE.clan dont permission top promote","%tag% &cNo puedes promover jugadores."),
	PLAYER_NO_INVITATIONS("LANGUAGE.player no invitation","%tag% &cNo tienes invitaciones."), 
	PLAYER_DONT_MOD_AND_LEADER("LANGUAGE.clan dont mod and leader","%tag% &cNo eres el líder o moderador del clan."), 
	PLAYER_DONT_MOD_AND_LEADER_GUI("LANGUAGE.clan dont mod and leader gui","&cNecesitas ser &4&lLíder &co &4&lMod&c!"), 
	PLAYER_DONT_MOD("LANGUAGE.player dont mod","%tag% &cEste jugador no es moderador."), 
	PLAYER_IS_MOD("LANGUAGE.player is mod","%tag% &cEste jugador ya es moderador."), 
	PLAYER_OFFLINE("LANGUAGE.player offline","%tag% &c¡El jugador está desconectado o no existe!"),
	PLAYER_CANNOT_EXPEL_LEADER("LANGUAGE.player cannot expel leader","%tag% &cNo puedes expulsar al Líder del Clan."), 
	PLAYER_CANNOT_EXPEL_MOD("LANGUAGE.player cannot expel mod","%tag% &cUn moderador no puede expulsar a otro del mismo cargo."),
	PLAYER_IS_CLAN_LEADER("LANGUAGE.player is clan leader","%tag% &cEres el líder del clan, para borrar, usa &b/clan disband&c y borrarás el Clan."), 
	YOU_DONT_HAVE_CLAN("LANGUAGE.you donthave clan","%tag% &cNo tienes un clan."),
	PLAYER_DONT_HAVE_CLAN("LANGUAGE.player donthave clan","%tag% &cEste jugador no tiene clan."),
	PLAYER_HAVE_CLAN("LANGUAGE.player have clan","%tag% &cYa tienes un clan."), 
	PLAYER_HAS_CLAN("LANGUAGE.player has clan","%tag% &cEste jugador ya tiene un clan."), 
	PLAYER_IS_YOU("LANGUAGE.player is you","%tag% &cEste jugador eres tu."), 
	PLAYER_DONT_HAVE_MONEY("LANGUAGE.player dont have money","%tag% &cNecesitas &a$%amount% &cpara esto."), 
	PLAYER_DONT_HAVE_MONEY_GUI("LANGUAGE.player dont have money gui","&cNecesitas &a$%amount%"), 
	PLAYER_DEBITED_MONEY("LANGUAGE.player debited money","%tag% &aSe te ha cobrado &a%amount% &ede tu cuenta."), 
	PLAYER_DEPOSITED_MONEY("LANGUAGE.player deposited money","%tag% &a$%amount% &eha sido depositado en tu cuenta."), 

	PLAYER_INVITATION_EXPIRED("LANGUAGE.player invitation expired","%tag% &cTu invitación para unirte al clan &f%clan_tag% &ceha expirado."), 
	PLAYER_INVITATION_DANIED("LANGUAGE.player invitation daniel","%tag% &cEl jugador negó la invitación."), 

	PLAYER_ALREADY_INVITED("LANGUAGE.player already invited","%tag% &c¡Ya hay una invitación para este jugador en curso!"), 

	GUI_ERROR("LANGUAGE.gui error","%tag% &cEste menú contiene un error y no se puede abrir"), 
	PLAYER_TELEPORT_DONT_MOVE("LANGUAGE.player teleport dont move","%tag% &aPreparando el teletransporte, no te muevas %sec% seg."), 
	PLAYER_TELEPORT_MOVED("LANGUAGE.player teleport moved","%tag% &c¡Te moviste y el teletransporte fue cancelado!"), 
	PLAYER_TELEPORT_TRUE("LANGUAGE.player teleport true","%tag% &a¡Fuiste teletransportado!"),
	PLAYER_TELEPORT_FALSE("LANGUAGE.player teleport false","%tag% &c¡No te han teletransportado por ningún error!"), 
	UNKNOWN_ERROR("LANGUAGE.unknown error","%tag% &cSe produjo un error desconocido con esto, ¡inténtelo de nuevo!"),
	NOTHING_HERE("LANGUAGE.nothing here","&cNada aquí."), 
	CLAN_EMPTY_NAME("LANGUAGE.clan empty name","&c<¡Sin nombre!>"),
	CLAN_EMPTY_DESC("LANGUAGE.clan empty desc","&c<¡Sin descripción!>"),
	
	JSON_ADVANCED_ACTION_CREATE("LANGUAGE.json advanced action create","%tag% &7¡Escribe en el chat el nombre del nuevo clan que deseas crear o usar &c/clan cancel &r&7para cancelar!"),
	JSON_ADVANCED_ACTION_DISBAND("LANGUAGE.json advanced action disband","%tag% &7¡Escribe &b&l%confirm_action% &r&7en el chat para confirmar o usar &c/clan cancel &r&7para cancelar!"),
	JSON_ADVANCED_ACTION_CHANGELEADER("LANGUAGE.json advanced action changeleder","%tag% &7¡Escribe &b&l%confirm_action% &r&7en el chat para confirmar o usar &c/clan cancel &r&7para cancelar!"),
	JSON_ADVANCED_ACTION_MODTAG("LANGUAGE.json advanced action modtag","%tag% &7¡Escribe en el chat la nueva ETIQUETA del clan o usa &c/clan cancel &r&7para cancelar!"),
	JSON_ADVANCED_ACTION_DESC("LANGUAGE.json advanced action desc","%tag% &7¡Escribe en el chat la descripción del nuevo clan o usa &c/clan cancel &r&7para cancelar!"),
	JSON_ADVANCED_ACTION_NAME("LANGUAGE.json advanced action name","%tag% &7¡Escribe en el chat el nombre del nuevo clan o usa &c/clan cancel &r&7para cancelar!"),
	JSON_ADVANCED_ACTION_INVITE("LANGUAGE.json advanced action invite","%tag% &7¡Escribe en el chat a quién quieres invitar al clan o usa &c/clan cancel &r&7para cancelar!"),
	JSON_ADVANCED_INVITE_RECEIVED("LANGUAGE.json simple invite received"," &c&l! &eHas recibido una invitación para unirte al clan &f%clan_tag%&e, la invitación caduca en &b%sec_expires% seg&e. &eUsa &b/clan join %clan_tag_nocolor% &eo &b/clan deny %clan_tag_nocolor%"),
	JSON_ADVANCED_HELP_PAGINATION("LANGUAGE.json advanced help pagination"," &cPara seguir usa: &b/clan help [página]"),
	
	JSON_SIMPLE_UNKNOWN_COMMAND("LANGUAGE.json simple command unknown","%tag% &cComando desconocido, usa &b/uclan help &cpara ver la lista de comandos disponibles."),
	JSON_SIMPLE_UNKNOWN_COMMAND_PLAYER("LANGUAGE.json simple command unknown player","%tag% &cComando desconocido, usa &b/clan help &cpara ver la lista de comandos disponibles."),
	JSON_SIMPLE_CLAN_ALLY_RIVAL_LIST_FORMAT("LANGUAGE.json simple clan ally rival list format"," &8%clan_tag% &7- &b%clan_kdr% &7- &b%clan_members_count%"),
	JSON_SIMPLE_CLAN_LISt_FORMAT("LANGUAGE.json simple clan list format"," &a%clan_rank%° &7- &8%clan_tag% &7- &f%clan_desc% &7- &b%clan_kdr% &7- &b%clan_members_count%"),
	JSON_SIMPLE_LIST_NEXT("LANGUAGE.json simple list next"," &bPágina siguiente >>"),
	JSON_SIMPLE_LIST_PREV("LANGUAGE.json simple list prev"," << &bPágina anterior"),
	JSON_SIMPLE_LIST_CONTROLER("LANGUAGE.json simple list controler"," << &bPágina anterior"),
	JSON_SIMPLE_CLAN_DELETED("LANGUAGE.json simple clan deleted"," &a%clan_rank%° &7- &c&m¡Clan eliminado!"), 

	DISABLED_FUNCTION("LANGUAGE.disabled function","%tag% &cEsta función/addon parece estar desactivado."), 

	ADMIN_OPENED_CLANCHEST("LANGUAGE.admin opened clanchest","%tag% &cUn administrador abrió el cofre del clan."),
	TOP_KDR_FORMAT("LANGUAGE.top kdr format","&b%num%º &7| &a%uclans_tag_color% &7| &fKdr: &b%uclans_clan_kdr%"),
	TOP_KILL_FORMAT("LANGUAGE.top kill format","&b%num%º &7| &a%uclans_tag_color% &7| &fAsesinatos: &b%uclans_clan_kills%"),
	TOP_DEATH_FORMAT("LANGUAGE.top death format","&b%num%º &7| &a%uclans_tag_color% &7| &fMuertes: &b%uclans_clan_deaths%"),
	TOP_MEMBER_FORMAT("LANGUAGE.top member format","&b%num%º &7| &a%uclans_tag_color% &7| &fMiembros: &b%uclans_count_members%"), 
	TOP_BANK_FORMAT("LANGUAGE.top bank format","&b%num%º &7| &a%uclans_tag_color% &7| &fBanco: &b%uclans_bank_balance%"), 
	TOP_LEVEL_FORMAT("LANGUAGE.top level format","&b%num%º &7| &a%uclans_tag_color% &7| &fNvl: &b%uclans_level%"), 
	TOP_WAR_FORMAT("LANGUAGE.top war format","&b%num%º &7| &a%uclans_tag_color% &7| &a%uclans_clan_war_win%&7/&4%uclans_clan_war_lose%"), 
	CLAN_NEW_BALANCE("LANGUAGE.clan new balance","%tag% &aEl nuevo balance del banco es &a$%uclans_bank_balance%&e, cambiado por &a%uclans_player%"),
	CLAN_QUEST_CHANGE("LANGUAGE.clan quest change","%tag% &aLos puntos de invitado del clan son &b%uclans_quest_points%&e, Total terminado &b%uclans_quest_finished%"), 
	PLAYER_RESETED_KDR("LANGUAGE.player reseted kdr","%tag% &a¡Al jugador &a%player% &ese le ha reiniciado su KDR!"),
	CLAN_RESETED_KDR("LANGUAGE.clan reseted kdr","%tag% &a¡Al clan &a%uclans_tag_color% &ese le ha reiniciado su KDR!"),
	VALUE_GREATER_THAN_ZERO("LANGUAGE.value greater than zero","%tag% &cEl valor debe ser mayor que cero"), 
	CLAN_LEVEL_CHANGE("LANGUAGE.clan level change","%tag% &aEl &eclan &b%clan% es ahora nivel &b%num%"),
	CLAN_NOT_HAVE_LEVELS("LANGUAGE.clan not have levels","%tag% &cEl clan no tiene suficientes niveles para eliminar"), 
	CLAN_HAS_ONLY_LEVELS("LANGUAGE.clan has only levels","%tag% &cEl clan solo tiene &b%num% &cniveles"), 
	COMMAND_IN_COOLDOWN("LANGUAGE.command in cooldown","%tag% &cEspera &b%sec% &cseg. para usar este comando de nuevo."), 

	ERROR_LENGTH("LANGUAGE.error length","%tag% &cEl valor debe tener un tamaño entre &b%min% &cy &b%max%"), 
	KITS_LIST_HEADER("LANGUAGE.kits list header","&9&lLista de Kit:"), 
	KITS_LIST_EMPTY("LANGUAGE.kits list empty"," &c- No hay kits para mostrar"), 
	KITS_LIST_FORMAT("LANGUAGE.kits list format"," &a%kit_name% &7- &7%kit_desc% &7- &fFecha: &b%kit_creation_date%"), 
	KIT_NOT_EXISTS("LANGUAGE.kit not exists","%tag% &cNo hay ningún kit con este nombre."), 
	KIT_ALREADY_EXISTS("LANGUAGE.kit already exists","%tag% &cYa existe un kit con este nombre."), 
	EMPTY_INVENTORY("LANGUAGE.empty inventory","%tag% &cTu inventario no puede estar vacío."),
	STATE_TRUE("LANGUAGE.state true","&aACTIVADO"),
	STATE_FALSE("LANGUAGE.state false","&cDESACTIVADO"), 
	ACCEPTED_VALUES("LANGUAGE.accept type","%tag% &cEl tipo no es válido, utilice: &b%types%"), 

	CLAN_REGROUP_INVITE_EXPIRED("LANGUAGE.clan regroup invite expired","%tag% &c¡La invitación para reagruparse ha expirado!"), 
	CLAN_REGROUP_INVITE_DOESNOT_EXIST("LANGUAGE.clan regroup invite doesnot exists","%tag% &cNo se ha enviado ninguna solicitud de reagrupamiento."), 
	CLAN_REGROUP_INVITE_ALREADY_EXIST("LANGUAGE.clan regroup invite already exists","%tag% &cYa se envió una solicitud de reagrupamiento."), 
	CLAN_REGROUP_INVITE_DENY("LANGUAGE.clan regroup invite deny","%tag% &cEl jugador &a%player% &crechazó su solicitud!"), 
	CLAN_REGROUP_INVITE_ACCEPT("LANGUAGE.clan regroup invite accept","%tag% &cEl jugador &a%player% &eaceptó tu solicitud!"), 
	CLAN_REGROUP_INVITE_ALREADY_DENIED("LANGUAGE.clan regroup invite already denied","%tag% &cYa denegaste la solicitud."),
	CLAN_REGROUP_INVITE_ALREADY_ACCEPTED("LANGUAGE.clan regroup invite already accepted","%tag% &cYa aceptó la solicitud."), 
	CLAN_HAS_NO_MEMBERS("LANGUAGE.clan has no members","%tag% &cTu clan no tiene miembros."), 
	
	DISABLED_WORLD_REGROUP("LANGUAGE.disabled world regroup","%tag% &cNo puedes enviar solicitudes de reagrupamiento en este mundo."),
	DISABLED_REGION_REGROUP("LANGUAGE.disabled region regroup","%tag% &cNo puede enviar solicitudes de reagrupamiento en esta región."), 
	DISABLED_REGION_COMMAND("LANGUAGE.disabled region command","%tag% &cNo puede utilizar estos comandos en esta región."), 
	
	CLAN_RIVAL_REMOVE_ALREADY_INVITED("LANGUAGE.clan rival remove already invited","%tag% &c¡Ya hay una solicitud de paz de tu clan o otro clan en curso para este clan, ¡espere y vuelva a intentarlo!"),  
	CLAN_RIVAL_REMOVE_ERROR("LANGUAGE.clan rival remove error","%tag% &c¡Hubo un error al enviar la solicitud!"),  
	CLAN_RIVAL_REMOVE_MODERATION_OFFLINE("LANGUAGE.clan rival remove moderation offline","%tag% &cNo hay moderadores ni líderes en línea en el otro clan."),
	CLAN_RIVAL_REMOVE_SENDED("LANGUAGE.clan rival remove sended","%tag% &aSolicitud de paz enviada, espera a que el clan acepte o rechace."), 
	CLAN_RIVAL_REMOVE_NOT_FOUND("LANGUAGE.clan rival remove not found","%tag% &cNo hay peticiones de paz."),
	CLAN_RIVAL_REMOVE_DENY("LANGUAGE.clan rival remove deny","%tag% &cNegaste la solicitud para eliminar la rivalidad."), 
	CLAN_RIVAL_REMOVE_DENY_RECEIVED("LANGUAGE.clan rival remove deny received","%tag% &cEl otro clan negó la solicitud de paz."),
	CLAN_RIVAL_REMOVE_EXPIRED("LANGUAGE.clan rival remove expired","%tag% &c¡La invitación a la paz ha expirado!"),
	
	CLAN_ALLY_INVITE_NOT_FOUND("LANGUAGE.clan ally invite not found","%tag% &cNo hay invitaciones para aliados."),
	CLAN_ALLY_INVITE_DENY("LANGUAGE.clan ally invite deny","%tag% &cHas negado la invitación a la alianza."), 
	CLAN_ALLY_INVITE_ALREADY_INVITED("LANGUAGE.clan ally invite already invited","%tag% &cYa hay una invitación de tu clan o otro clan en progreso para este clan, ¡espera y vuelve a intentarlo!"), 
	CLAN_ALLY_INVITE_ERROR("LANGUAGE.clan ally invite error","%tag% &c¡Hubo un error al enviar la solicitud!"), 
	CLAN_ALLY_INVITE_MODERATION_OFFLINE("LANGUAGE.clan ally invite moderation offline","%tag% &cNo hay moderadores ni líderes en línea en el otro clan."), 
	CLAN_ALLY_INVITE_SENDED("LANGUAGE.clan ally invite sended","%tag% &aInvitación enviada, espera a que el clan acepte o rechace."),
	CLAN_ALLY_INVITE_EXPIRED("LANGUAGE.clan ally invite expired","%tag% &c¡La invitación a la alianza ha expirado!"), 
	CLAN_ALLY_INVITE_DENY_RECEIVED("LANGUAGE.clan ally invite deny received","%tag% &cEl otro clan negó la solicitud de alianza."), 
	
	CLAN_NOT_HAVE_POINTS("LANGUAGE.clan not have points","%tag% &cEl clan no tiene puntos para quitar"), 
	CLAN_HAS_ONLY_POINTS("LANGUAGE.clan has only points","%tag% &cEl clan solo tiene &b%num% &cpuntos"), 
	CLAN_ALLY_IN_LIMIT("LANGUAGE.clan ally in limit","%tag% &cTu clan ha alcanzado el límite de aliados y necesita ganar niveles para desbloquear más aliados. El límite actual de tu clan es &b&l%uclans_limit_ally%"),
	CLAN_RIVAL_IN_LIMIT("LANGUAGE.clan rival in limit","%tag% &cTu clan ha alcanzado el límite de rivales y necesita ganar niveles para desbloquear más rivales. El límite actual de tu clan es &b&l%uclans_limit_rival%"),
	COMMAND_DEPRECATED("LANGUAGE.command deprecated","%tag% &cEste comando ha quedado obsoleto y se puede eliminar de la configuración"), 
	CLAN_DOES_NOT_EXISTS("LANGUAGE.chan does not exists", "%tag% &cEste clan no existe"),
	NEED_LEVEL_MIN("LANGUAGE.need level min","%tag% &cTu clan debe tener al menos &b&l%level% &cniveles para esto!"), 
	DISABLED_REGION_CHEST("LANGUAGE.disabled region chest","%tag% &cNo puedes usar cofres en esta región."), 
	PLAYER_LEAVE("LANGUAGE.player_leave","%tag% &cEl miembro &b&l%player% &cse ha desconectado."), 
	PLAYER_JOIN("LANGUAGE.player_join","%tag% &aEl miembro &b&l%player% &aacaba de unirse."),

	HOME_ALREADY_EXISTS("LANGUAGE.home already exists","%tag% &cYa hay un home con este nombre."), 
	HOME_CREATE_ERROR("LANGUAGE.home create error","%tag% &cHubo un error al crear el home."), 
	HOME_CREATE_SUCCESS("LANGUAGE.home create success","%tag% &a¡Home nuevo creado con éxito!"), 
	HOME_NOT_EXISTS("LANGUAGE.home no exists","%tag% &cNo hay home con ese nombre."), 
	HOME_NOT_EXISTS_GUI("LANGUAGE.home no exists gui","&cEste home tiene un error."), 
	HOME_DELETE_ERROR("LANGUAGE.home delete error","%tag% &cHubo un error al eliminar."), 
	HOME_DELETE_ERROR_GUI("LANGUAGE.home delete error gui","&cHubo un error al eliminar."), 
	HOME_DELETE_SUCCESS("LANGUAGE.home delete success","%tag% &a¡El home se ha eliminado correctamente!"), 
	HOME_DELETE_SUCCESS_GUI("LANGUAGE.home delete success gui","&a¡Se ha eliminado con éxito!"), 
	HOME_NEW_CREATE("LANGUAGE.new create home","%tag% &aSe ha creado un nuevo home de clan en el servidor &b%server% &acon el nombre &b%name%"), 
	HOME_REMOVED("LANGUAGE.home removed","%tag% &cEl home &b%name% &cdel servidor &b%server% &cdel clan se ha eliminado"), 
	DISABLED_WORLD_HOME("LANGUAGE.disabled world command","%tag% &cLos home de los clanes están desactivados en este mundo."),
	DISABLED_REGION_HOME("LANGUAGE.disabled region home","%tag% &cLos home de los clanes están desactivados en esta región."), 
	HOME_LIMIT("LANGUAGE.home limit","&cEste es el límite (%limit%) para tu Clan!"),
	HOME_LIMIT_REACHED("LANGUAGE.home limit reached","%tag% &cEl límite para tu clan es %homes% homes."), 
	BANNER_DELETE_ERROR_GUI("LANGUAGE.banner delete error gui","&c¡Error al eliminar!"), 
	BANNER_DELETE_SUCCESS_GUI("LANGUAGE.banner delete success gui","&bSe ha eliminado con éxito!"), 
	BANNER_DELETE_ERROR("LANGUAGE.banner delete error","%tag% &cOcurrió un error al eliminar."), 
	BANNER_DELETE_SUCCESS("LANGUAGE.banner delete success","%tag% &aBanner eliminado correctamente!"), 
	BANNER_EMPTY("LANGUAGE.banner empty","%tag% &c¡Tu clan no tiene estandarte!"), 
	BANNER_EMPTY_GUI("LANGUAGE.banner empty gui","&c¡Tu clan no tiene estandarte!"),
	BANNER_EMPTY_ITEM("LANGUAGE.banner empty item","&c¡El artículo debe ser un estandarte!"), 
	BANNER_NOT_ITEMSTACK("LANGUAGE.banner not itemstack","&cEl artículo debe ser un estandarte."), 
	BANNER_NOT_BANNER("LANGUAGE.banner not banner","%tag% &cEl artículo que tienes en la mano debe ser un estandarte."), 
	BANNER_HAND_EMPTY("LANGUAGE.banner hand empty","%tag% &cDebes tener un artículo en la mano."), 
	BANNER_UPLOAD_ERROR_GUI("LANGUAGE.banner upload error gui","&cError al guardar el estandarte."), 
	BANNER_UPLOAD_SUCCESS_GUI("LANGUAGE.banner upload success gui","&b¡Nuevo estandarte guardado!"),  
	NEW_POINT_RECEIVED("LANGUAGE.new point received","%tag% &aTu clan recibió &b%points% puntos&a, y ahora tiene &b%totalpoints% puntos"),
	NEW_POINT_REMOVED("LANGUAGE.new point removed","%tag% &cTu clan perdió &b%points% puntos&c, y ahora tiene &b%totalpoints% points"),
	NEW_POINT_SET("LANGUAGE.new point set","%tag% &aTus puntos de clan se han cambiado a &b%totalpoints% puntos"), 


	

	GUI("GUI", " ", " ", "# TRANSLATIONS OF GUI MENU FILES", " "),
	
	
	General_disband_confirm_title("GUI.General disband_confirm title", "&c&l¿Confirmas la eliminación del Clan?"),
	General_disband_confirm_items_fill_name("GUI.General disband_confirm items fill name", " "),
	General_disband_confirm_items_fill_lore("GUI.General disband_confirm items fill lore", Arrays.asList()),
	General_disband_confirm_items_confirm_name("GUI.General disband_confirm items confirm name", "&aConfirmar"),
	General_disband_confirm_items_confirm_lore("GUI.General disband_confirm items confirm lore", Arrays.asList("", " &cClic para confirmar.")),
	General_disband_confirm_items_cancel_name("GUI.General disband_confirm items cancel name", "&aCancelar"),
	General_disband_confirm_items_cancel_lore("GUI.General disband_confirm items cancel lore", Arrays.asList("", " &eClic para cancelar.")),
	
	General_changeleader_confirm_title("GUI.General changeleader_confirm title", "&c&l¿Confirmar el cambio de líder del clan?"),
	General_changeleader_confirm_items_fill_name("GUI.General changeleader_confirm items fill name", " "),
	General_changeleader_confirm_items_fill_lore("GUI.General changeleader_confirm items fill lore", Arrays.asList()),
	General_changeleader_confirm_items_confirm_name("GUI.General changeleader_confirm items confirm name", "&aConfirmar"),
	General_changeleader_confirm_items_confirm_lore("GUI.General changeleader_confirm items confirm lore", Arrays.asList("", " &cClic para confirmar.")),
	General_changeleader_confirm_items_cancel_name("GUI.General changeleader_confirm items cancel name", "&aCancelar"),
	General_changeleader_confirm_items_cancel_lore("GUI.General changeleader_confirm items cancel lore", Arrays.asList("", " &eClic para cancelar.")),
	
	Home_clan_home_title("GUI.Home clan_home title", "&9&lEl home del clan"),
	Home_clan_home_items_fill_name("GUI.Home clan_home items fill name", " "),
	Home_clan_home_items_fill_lore("GUI.Home clan_home items fill lore", Arrays.asList()),
	Home_clan_home_items_ally_homes_name("GUI.Home clan_home items ally_homes name", "&aVer home de Aliados"),
	Home_clan_home_items_ally_homes_lore("GUI.Home clan_home items ally_homes lore", Arrays.asList("", " &eClic para abrir.")),
	Home_clan_home_items_create_name("GUI.Home clan_home items create name", "&aCrear un nuevo home"),
	Home_clan_home_items_create_lore("GUI.Home clan_home items create lore", Arrays.asList("", " &eClic para crear.")),
	Home_clan_home_items_back_name("GUI.Home clan_home items back name", "&cRegresar"),
	Home_clan_home_items_back_lore("GUI.Home clan_home items back lore", Arrays.asList("", " &eClic para volver.")),
	Home_clan_home_items_next_name("GUI.Home clan_home items next name", "&aSiguiente página"),
	Home_clan_home_items_next_lore("GUI.Home clan_home items next lore", Arrays.asList("", " &eClic para continuar.")),
	Home_clan_home_items_previous_name("GUI.Home clan_home items previous name", "&aPágina anterior"),
	Home_clan_home_items_previous_lore("GUI.Home clan_home items previous lore", Arrays.asList("", " &eClic para volver.")),
	Home_clan_home_items_current_name("GUI.Home clan_home items current name", "&aHome %uclans_home:<num>:name%"),
	Home_clan_home_items_current_lore("GUI.Home clan_home items current lore", Arrays.asList("", " &eInformación del home", " &7", " &7Server: &a%uclans_home:<num>:server%", " &7Nombre: &b%uclans_home:<num>:name%", "", " &eClic izquierdo para teletransportarte ", " &cClic derecho para eliminar.")),
	

	Home_clan_delhome_confirm_title("GUI.Home clan_delhome_confirm title", "&c&l¿Confirmar eliminación del home &4&l%home_name% &c?"),
	Home_clan_delhome_confirm_items_fill_name("GUI.Home clan_delhome_confirm items fill name", " "),
	Home_clan_delhome_confirm_items_fill_lore("GUI.Home clan_delhome_confirm items fill lore", Arrays.asList()),
	Home_clan_delhome_confirm_items_confirm_name("GUI.Home clan_delhome_confirm items confirm name", "&aClic para confirmar"),

	Home_clan_delhome_confirm_items_confirm_lore("GUI.Home clan_delhome_confirm items confirm lore", Arrays.asList(" ", " &eHaz clic para confirmar.")),
	Home_clan_delhome_confirm_items_cancel_name("GUI.Home clan_delhome_confirm items cancel name", "&aClic para cancelar"),
	Home_clan_delhome_confirm_items_cancel_lore("GUI.Home clan_delhome_confirm items cancel lore", Arrays.asList(" ", " &eHaz clic para cancelar.")),
	
	General_noclan_home_title("GUI.General noclan_home title", "&9&lClan &7| &cSin clan"),
	General_noclan_home_items_fill_name("GUI.General noclan_home items fill name", " "),
	General_noclan_home_items_fill_lore("GUI.General noclan_home items fill lore", Arrays.asList()),
	General_noclan_home_items_fill2_name("GUI.General noclan_home items fill2 name", " "),
	General_noclan_home_items_fill2_lore("GUI.General noclan_home items fill2 lore", Arrays.asList()),
	General_noclan_home_items_commands_name("GUI.General noclan_home items commands name", "&aLista de comandos y ayuda"),
	General_noclan_home_items_commands_lore("GUI.General noclan_home items commands lore", Arrays.asList(" &eClic para ver la lista completa", "&ede comandos para clanes y tierras.")),
	General_noclan_home_items_clans_name("GUI.General noclan_home items clans name", "&aTodos los clanes"),
	General_noclan_home_items_clans_lore("GUI.General noclan_home items clans lore", Arrays.asList(" &eClic para abrir el menú de la lista de clanes.")),
	General_noclan_home_items_create_name("GUI.General noclan_home items create name", "&cNo tienes un clan"),
	General_noclan_home_items_create_lore("GUI.General noclan_home items create lore", Arrays.asList(" &eClic para crear un clan.")),
	
	General_clan_home_title("GUI.General clan_home title", "&9&lMenu del clan"),
	General_clan_home_items_fill_name("GUI.General clan_home items fill name", " "),
	General_clan_home_items_fill_lore("GUI.General clan_home items fill lore", Arrays.asList()),
	General_clan_home_items_fill2_name("GUI.General clan_home items fill2 name", " "),
	General_clan_home_items_fill2_lore("GUI.General clan_home items fill2 lore", Arrays.asList()),
	
	General_clan_home_items_info_name("GUI.General clan_home items info name", "&aClan %uclans_tag_color%"),
	General_clan_home_items_info_lore("GUI.General clan_home items info lore", Arrays.asList(" &eInformación del clan", " &7", " &7Nivel de clan: &a%uclans_level%"," &7Puntos de clan: &a%uclans_points%", " &7Banco: &a$%uclans_bank_balance%", " &7", " &7Etiqt: &b%uclans_tag_color%", " &7Desc: &b%uclans_desc_color%", " ", " &eClic para abrir una lista de estado.")),
	General_clan_home_items_banner_name("GUI.General clan_home items banner name", "&aEstandarte de Clan"),
	General_clan_home_items_banner_lore("GUI.General clan_home items banner lore", Arrays.asList(" ", " &eInformación del estandarte:", "", " &fTiene estandarte: &b%uclans_hasbanner_formated%"," "," &eEl estandarte del clan es tu marca", "&ey tu &b&lNEXUS &eutilizado para la señalización de la tierra!", " &eSolo el líder o los moderadores pueden","&eeditar el estandarte del clan" )),
	General_clan_home_items_clans_name("GUI.General clan_home items clans name", "&aAliados de clan"),
	General_clan_home_items_clans_lore("GUI.General clan_home items clans lore", Arrays.asList(" &eClic para abrir el menú de lista de clanes.")),
	General_clan_home_items_commands_name("GUI.General clan_home items commands name", "&aLista de comandos y ayuda"),
	General_clan_home_items_commands_lore("GUI.General clan_home items commands lore", Arrays.asList(" &eClic para ver la lista completa", "&ede comandos para clanes y tierras.")),
	General_clan_home_items_settings_name("GUI.General clan_home items settings name", "&aConfiguración del clan"),
	General_clan_home_items_settings_lore("GUI.General clan_home items settings lore", Arrays.asList(" &eClic para abrir.")),
	General_clan_home_items_home_name("GUI.General clan_home items home name", "&aAbrir menú del home."),
	General_clan_home_items_home_lore("GUI.General clan_home items home lore", Arrays.asList(" &eClic para abrir.")),
	General_clan_home_items_ally_name("GUI.General clan_home items ally name", "&aAlliances"),
	General_clan_home_items_ally_lore("GUI.General clan_home items ally lore", Arrays.asList(" ", " &7Aliados: &b%uclans_clan_count_ally%", " "," &eClic para abrir el menú de alianzas.")),
	General_clan_home_items_rival_name("GUI.General clan_home items rival name", "&aRivalries"),
	General_clan_home_items_rival_lore("GUI.General clan_home items rival lore", Arrays.asList(" ", " &7Rivales: &b%uclans_clan_count_rival%", " " ," &eClic para abrir el menú de rivales.")),
	General_clan_home_items_members_name("GUI.General clan_home items members name", "&aMiembros del clan"),
	General_clan_home_items_members_lore("GUI.General clan_home items members lore", Arrays.asList(" "," &7Miembros: &b%uclans_count_members%", " ", " &eClic para abrir el menú de miembros.")),

	General_player_profile_title("GUI.General player_profile title", "&9&lPerfil de &7| &a%uclans_player%"),
	General_player_profile_items_head_name("GUI.General player_profile items head name", "&a%uclans_player%"),
	General_player_profile_items_head_lore("GUI.General player_profile items head lore", Arrays.asList("", " &7Clan: &b%uclans_tag_color%", " &7Líder: &b%uclans_leader%", " ", " &7Nickname: &b%uclans_player%", " &7Kdr: &b%uclans_player_kills%&8/&b%uclans_player_deaths% &8(%uclans_player_kdr%)", " &7Entró: &b%uclans_player_joindate_formated%", " &7Ultima vez visto: &b%uclans_player_lastsee_formated%" )),
	General_player_profile_items_back_name("GUI.General player_profile items back name", "&cRegresa a tu home"),
	General_player_profile_items_back_lore("GUI.General player_profile items back lore", Arrays.asList(" &eClic para volver a tu home" )),
	General_player_profile_items_fill_name("GUI.General player_profile items fill name", " "),
	General_player_profile_items_fill_lore("GUI.General player_profile items fill lore", Arrays.asList()),
	
	General_clan_stats_title("GUI.General clan_stats title", "&9&lEstadisticas &7| %uclans_tag_color%"),
	General_clan_stats_items_fill_name("GUI.General clan_stats items fill name", " "),
	General_clan_stats_items_fill_lore("GUI.General clan_stats items fill lore", Arrays.asList()),
	General_clan_stats_items_back_name("GUI.General clan_stats items back name", "&cRegresar"),
	General_clan_stats_items_back_lore("GUI.General clan_stats items back lore", Arrays.asList(" &eClic para volver" )),
	General_clan_stats_items_limits_name("GUI.General clan_stats items limits name", "&aLímites del clan:"),
	General_clan_stats_items_limits_lore("GUI.General clan_stats items limits lore", Arrays.asList(" ", "&eAcerca de los límites:", " ", " &7Homes: &b%uclans_limit_home%", " &7Aliados: &b%uclans_limit_ally%", " &7Rivales: &b%uclans_limit_rival%", " &7Espacios: &b%uclans_slots_total%", " ", " &eLos límites se incrementan a medida que", "&eel clan gana niveles.")),
	General_clan_stats_items_member_rival_ally_name("GUI.General clan_stats items member_rival_ally name", "&aMiembros, rivales y aliados:"),
	General_clan_stats_items_member_rival_ally_lore("GUI.General clan_stats items member_rival_ally lore", Arrays.asList(" ", "&eSobre miembros, rivales y aliados:", " ", " &7Miembros: &b%uclans_count_members%", " &7Miembros en línea: &b%uclans_count_onlinemembers%", " &7Aliados: &b%uclans_clan_count_ally%", " &7Rivales: &b%uclans_clan_count_rival%")),
	General_clan_stats_items_others_name("GUI.General clan_stats items others name", "&aOthers stats:"),
	General_clan_stats_items_others_lore("GUI.General clan_stats items others lore", Arrays.asList(" ", "&eOtros:", " ", " &7Miembros que se han unido: &b%uclans_clan_member_joined%", " &7Miembros que se han salido: &b%uclans_clan_member_leave%", " &7Miembros expulsados: &b%uclans_clan_member_kicked%", " &7Cambios de etiqueta: &b%uclans_clan_tag_changed%")),
	General_clan_stats_items_status_name("GUI.General clan_stats items status name", "&aStatus:"),
	General_clan_stats_items_status_lore("GUI.General clan_stats items status lore", Arrays.asList(" ", "&eSobre el estado:", " "," &7Banco: &a$%uclans_bank_balance%", " &7Nivel: &b%uclans_level%", " &7Nivel máximo alcanzado: &b%uclans_max_level_reached%", " &7Puntos de clan: &b%uclans_points%", " &7Desafío finalizado: &b%uclans_quest_finished%")),
	General_clan_stats_items_war_name("GUI.General clan_stats items war name", "&aWar stats:"),
	General_clan_stats_items_war_lore("GUI.General clan_stats items war lore", Arrays.asList(" ", "&eSobre las guerras:", " ", " &7Guerras ganadas: &b%uclans_clan_war_win%", " &7Guerras perdidas: &b%uclans_clan_war_lose%", " &7Guerras total: &b%uclans_clan_war_total%")),
	General_clan_stats_items_kdr_name("GUI.General clan_stats items kdr name", "&aKDR:"),
	General_clan_stats_items_kdr_lore("GUI.General clan_stats items kdr lore", Arrays.asList(" ", "&eSobre kdr:", " ", " &7Asesinatos: &b%uclans_clan_kills%", " &7Muertes: &b%uclans_clan_deaths%", " &7Kdr Total: &b%uclans_clan_kdr%")),
	General_clan_stats_items_banner_name("GUI.General clan_stats items banner name", "&aEstandarte de clan"),
	General_clan_stats_items_banner_lore("GUI.General clan_stats items banner lore", Arrays.asList(" ", " &eInformación del estandarte:", "", " &fTiene estandarte: &b%uclans_hasbanner_formated%" )),
	General_clan_stats_items_foundation_name("GUI.General clan_stats items foundation name", "&aFundación:"),
	General_clan_stats_items_foundation_lore("GUI.General clan_stats items foundation lore", Arrays.asList(" ", "&eSobre la fundación:", " ", " &7Líder: &b%uclans_leader%", " &7Fecha de creación: &b%uclans_creation_date_formated%", " &7Está verificado: &f%uclans_verified%", " &7Espacios: &f%uclans_slots% &8(+%uclans_slots_extra%)", " ", " &7Moderadores (%uclans_count_moderators%):", "  &a%uclans_moderators%" )),
	
	General_clan_settings_title("GUI.General clan_settings title", "&9&lMenú de configuración"),
	General_clan_settings_items_fill_name("GUI.General clan_settings items fill name", " "),
	General_clan_settings_items_fill_lore("GUI.General clan_settings items fill lore", Arrays.asList()),
	General_clan_settings_items_back_name("GUI.General clan_settings items back name", "&cRegresar"),
	General_clan_settings_items_back_lore("GUI.General clan_settings items back lore", Arrays.asList(" &eClic para volver" )),
	General_clan_settings_items_actions_name("GUI.General clan_settings items actions name", "&aAcciones"),
	General_clan_settings_items_actions_lore("GUI.General clan_settings items actions lore", Arrays.asList(" &eClic para abrir.")),
	General_clan_settings_items_delete_name("GUI.General clan_settings items delete name", "&c&lEliminar el clan"),
	General_clan_settings_items_delete_lore("GUI.General clan_settings items delete lore", Arrays.asList(" &eClic para eliminar el clan", " &c¡Solo el Líder puede hacer esto!", " &cEsto eliminará la protección de tu tierra.", " &c¡Esto requiere confirmación en CHAT!", " ", " &c¡Atención, esta acción no se puede deshacer!" )),
	General_clan_settings_items_make_banner_name("GUI.General clan_settings items make_banner name", "&aCrear o editar el estandarte"),
	General_clan_settings_items_make_banner_lore("GUI.General clan_settings items make_banner lore", Arrays.asList(" ", " &eClic para abrir.")),
	General_clan_settings_items_join_leave_name("GUI.General clan_settings items join_leave name", "&aUnirse y salir"),
	General_clan_settings_items_join_leave_lore("GUI.General clan_settings items join_leave lore", Arrays.asList(" ", " &fEstado: %uclans_settings_state:JOINLEAVE%", ""," &eClic para alternar ", " ", " &cCuando está deshabilitado, tu clan no", "&cverá más mensajes cuando", "&centren o salgan.")),
	General_clan_settings_items_ff_name("GUI.General clan_settings items ff name", "&aFuego amigo"),
	General_clan_settings_items_ff_lore("GUI.General clan_settings items ff lore", Arrays.asList(" ", " &fEstado: %uclans_settings_state:CLANFF%", ""," &eClic para alternar ", " ", " &cCuando se activa, los miembros pueden", "&catacarse unos a otros.")),
	General_clan_settings_items_allysharedhome_name("GUI.General clan_settings items allysharedhome name", "&aHome aliado compartido"),
	General_clan_settings_items_allysharedhome_lore("GUI.General clan_settings items allysharedhome lore", Arrays.asList(" ", " &fEstado: %uclans_settings_state:ALLYSHAREDHOME%", ""," &eClic para alternar ", " ", " &cCuando esté deshabilitado, los home de tu clan", "&cno aparecerá en la lista de homes aliados.")),
	General_clan_settings_items_allysharedchat_name("GUI.General clan_settings items allysharedchat name", "&aChat compartido de aliado"),
	General_clan_settings_items_allysharedchat_lore("GUI.General clan_settings items allysharedchat lore", Arrays.asList(" ", " &fEstado: %uclans_settings_state:ALLYSHAREDCHAT%", ""," &eClic para alternar ", " ", " &cCuando está deshabilitado, tu clan no", "&crecibir o enviar mensajes de aliados.")),
	General_clan_settings_items_warinvite_name("GUI.General clan_settings items warinvite name", "&aInvitaciones de guerra"),
	General_clan_settings_items_warinvite_lore("GUI.General clan_settings items warinvite lore", Arrays.asList(" ", " &fEstado: %uclans_settings_state:WARINVITE%", ""," &eClic para alternar ", " ", " &cCuando está deshabilitado, tu clan", "&cno recibe desafíos" )),

	
	General_clan_actions_title("GUI.General clan_actions title", "&9&lMenú de acciones"),
	General_clan_actions_items_fill_name("GUI.General clan_actions items fill name", " "),
	General_clan_actions_items_fill_lore("GUI.General clan_actions items fill lore", Arrays.asList()),
	General_clan_actions_items_back_name("GUI.General clan_actions items back name", "&cRegresar"),
	General_clan_actions_items_back_lore("GUI.General clan_actions items back lore", Arrays.asList(" &eClic para ir al banco" )),
	General_clan_actions_items_sethome_name("GUI.General clan_actions items sethome name", "&aEstablecer el home del clan"),
	General_clan_actions_items_sethome_lore("GUI.General clan_actions items sethome lore", Arrays.asList(" &eClic para configurar el home del clan" )),
	General_clan_actions_items_name_name("GUI.General clan_actions items name name", "&aCambiar el nombre del clan"),
	General_clan_actions_items_name_lore("GUI.General clan_actions items name lore", Arrays.asList(" &eClic para cambiar el nombre del clan.")),
	General_clan_actions_items_desc_name("GUI.General clan_actions items desc name", "&aCambiar la descripción del clan"),
	General_clan_actions_items_desc_lore("GUI.General clan_actions items desc lore", Arrays.asList(" &eClic para cambiar la descripción del clan.")),
	General_clan_actions_items_modtag_name("GUI.General clan_actions items modtag name", "&aCambiar la etiqueta del clan"),
	General_clan_actions_items_modtag_lore("GUI.General clan_actions items modtag lore", Arrays.asList(" &eclic para cambiar la etiqueta de clan" )),
	
	General_clan_top_title("GUI.General clan_top title", "&9&lLista de clanes &7| %current%"),
	General_clan_top_items_fill_name("GUI.General clan_top items fill name", " "),
	General_clan_top_items_fill_lore("GUI.General clan_top items fill lore", Arrays.asList()),
	General_clan_top_items_active_name("GUI.General clan_top items active name", " &aActual"),
	General_clan_top_items_active_lore("GUI.General clan_top items active lore", Arrays.asList()),
	General_clan_top_items_kdr_name("GUI.General clan_top items kdr name", "&cTop KDR"),
	General_clan_top_items_kdr_lore("GUI.General clan_top items kdr lore", Arrays.asList(" &eClic para ordenar", "&elista por KDR ", " ")),
	General_clan_top_items_kill_name("GUI.General clan_top items kill name", "&cTop ASESINO"),
	General_clan_top_items_kill_lore("GUI.General clan_top items kill lore", Arrays.asList(" &eClic para ordenar", "&elista por ASESINO ", " ")),
	General_clan_top_items_death_name("GUI.General clan_top items death name", "&cTop MUERTES"),
	General_clan_top_items_death_lore("GUI.General clan_top items death lore", Arrays.asList(" &eClic para ordenar", "&elista por MUERTES ", " ")),
	General_clan_top_items_bank_name("GUI.General clan_top items bank name", "&cTop BANCO"),
	General_clan_top_items_bank_lore("GUI.General clan_top items bank lore", Arrays.asList(" &eClic para ordenar", "&elista por BANCO ", " ")),
	General_clan_top_items_member_name("GUI.General clan_top items member name", "&cTop MIEMBRO"),
	General_clan_top_items_member_lore("GUI.General clan_top items member lore", Arrays.asList(" &eClic para ordenar", "&elista por MIEMBRO ", " ")),
	General_clan_top_items_level_name("GUI.General clan_top items level name", "&cTop NIVEL"),
	General_clan_top_items_level_lore("GUI.General clan_top items level lore", Arrays.asList(" &eClic para ordenar", "&elista por nivel ", " ")),
	General_clan_top_items_current_all_name("GUI.General clan_top items current_all name", "&aClan %uclans_tag_color%"),
	General_clan_top_items_current_all_lore("GUI.General clan_top items current_all lore", Arrays.asList("", " &eInformación de clan", " &7", " &7Fecha de creación: &a%uclans_creation_date_formated%", " &7", " &7Etiqt: &b%uclans_tag_color%", " &7Líder: &b%uclans_leader%", " &7Miembros: &b%uclans_count_members%", "", " &eClic derecho para ver información.")),
	General_clan_top_items_current_war_name("GUI.General clan_top items current_war name", "&aClan %uclans_tag_color%"),
	General_clan_top_items_current_war_lore("GUI.General clan_top items current_war lore", Arrays.asList("", " &eInformación del clan", " &7", " &7Guerras ganadas: &a%uclans_clan_war_win%", " &7", " &7Etiqt: &b%uclans_tag_color%", " &7Líder: &b%uclans_leader%", " &7Miembros: &b%uclans_count_members%", "", " &eClic derecho para ver información.")),
	General_clan_top_items_current_bank_name("GUI.General clan_top items current_bank name", "&aClan %uclans_tag_color%"),
	General_clan_top_items_current_bank_lore("GUI.General clan_top items current_bank lore", Arrays.asList("", " &eInformación del clan", " &7", " &7Banco: &a$%uclans_bank_balance%", " &7", " &7Etiqt: &b%uclans_tag_color%", " &7Líder: &b%uclans_leader%", " &7Miembros: &b%uclans_count_members%", "", " &eClic derecho para ver información.")),
	General_clan_top_items_current_member_name("GUI.General clan_top items current_member name", "&aClan %uclans_tag_color%"),
	General_clan_top_items_current_member_lore("GUI.General clan_top items current_member lore", Arrays.asList("", " &eInformación del clan", " &7", " &7Miembros: &a%uclans_count_members%", " &7", " &7Etiqt: &b%uclans_tag_color%", " &7Líder: &b%uclans_leader%", " &7Miembros: &b%uclans_count_members%", "", " &eClic derecho para ver información.")),
	General_clan_top_items_current_death_name("GUI.General clan_top items current_death name", "&aClan %uclans_tag_color%"),
	General_clan_top_items_current_death_lore("GUI.General clan_top items current_death lore", Arrays.asList("", " &eInformación del clan", " &7", " &7Muertes: &a%uclans_clan_deaths%", " &7", " &7Etiqt: &b%uclans_tag_color%", " &7Líder: &b%uclans_leader%", " &7Miembros: &b%uclans_count_members%", "", " &eClic derecho para ver información.")),
	General_clan_top_items_current_kill_name("GUI.General clan_top items current_kill name", "&aClan %uclans_tag_color%"),
	General_clan_top_items_current_kill_lore("GUI.General clan_top items current_kill lore", Arrays.asList("", " &eInformación del clan", " &7", " &7Asesinatos: &a%uclans_clan_kills%", " &7", " &7Etiqt: &b%uclans_tag_color%", " &7Líder: &b%uclans_leader%", " &7Miembros: &b%uclans_count_members%", "", " &eClic derecho para ver información.")),
	General_clan_top_items_current_kdr_name("GUI.General clan_top items current_kdr name", "&aClan %uclans_tag_color%"),
	General_clan_top_items_current_kdr_lore("GUI.General clan_top items current_kdr lore", Arrays.asList("", " &eInformación del clan", " &7", " &7KDR: &a%uclans_clan_kdr%", " &7", " &7Etiqt: &b%uclans_tag_color%", " &7Líder: &b%uclans_leader%", " &7Miembros: &b%uclans_count_members%", "", " &eClic derecho para ver información.")),
	General_clan_top_items_current_level_name("GUI.General clan_top items current_level name", "&aClan %uclans_tag_color%"),
	General_clan_top_items_current_level_lore("GUI.General clan_top items current_level lore", Arrays.asList("", " &eInformación del clan", " &7", " &7Nivel: &a%uclans_level%", " &7", " &7Etiqt: &b%uclans_tag_color%", " &7Líder: &b%uclans_leader%", " &7Miembros: &b%uclans_count_members%", "", " &eClic derecho para ver información.")),
	General_clan_top_items_current_name("GUI.General clan_top items current name", "&aClan %uclans_tag_color%"),
	General_clan_top_items_current_lore("GUI.General clan_top items current lore", Arrays.asList("", " &eInformación de clan", " &7", " &7Nivel: &a%uclans_level%", " &7", " &7Etiqt: &b%uclans_tag_color%", " &7Líder: &b%uclans_leader%", " &7Miembros: &b%uclans_count_members%", "", " &eClic derecho para ver información.")),
	General_clan_top_items_war_name("GUI.General clan_top items war name", "&cTop Guerra"),
	General_clan_top_items_war_lore("GUI.General clan_top items war lore", Arrays.asList(" &eClic para ordenar", "&elista por Top Guerra ", " ")),
	General_clan_top_items_all_name("GUI.General clan_top items all name", "&cTodos los verificados"),
	General_clan_top_items_all_lore("GUI.General clan_top items all lore", Arrays.asList(" &eClic para ordenar", "&elista de todos los clanes ", " ")),
	General_clan_top_items_next_name("GUI.General clan_top items next name", "&aSiguiente"),
	General_clan_top_items_next_lore("GUI.General clan_top items next lore", Arrays.asList(" &eClic para siguiente" )),
	General_clan_top_items_previous_name("GUI.General clan_top items previous name", "&aPrevio"),
	General_clan_top_items_previous_lore("GUI.General clan_top items previous lore", Arrays.asList(" &eClic para el anterior" )),
	General_clan_top_items_back_name("GUI.General clan_top items back name", "&cRegresar"),
	General_clan_top_items_back_lore("GUI.General clan_top items back lore", Arrays.asList(" &eClic para volver" )),

	General_clan_members_title("GUI.General clan_members title", "&9&lMenú de miembros"),
	General_clan_members_items_fill_name("GUI.General clan_members items fill name", " "),
	General_clan_members_items_fill_lore("GUI.General clan_members items fill lore", Arrays.asList()),
	General_clan_members_items_fill2_name("GUI.General clan_members items fill2 name", " "),
	General_clan_members_items_fill2_lore("GUI.General clan_members items fill2 lore", Arrays.asList()),
	General_clan_members_items_back_name("GUI.General clan_members items back name", "&cRegresar"),
	General_clan_members_items_back_lore("GUI.General clan_members items back lore", Arrays.asList(" &eClic para volver" )),
	General_clan_members_items_invite_name("GUI.General clan_members items invite name", "&aInvitar jugadores"),
	General_clan_members_items_invite_lore("GUI.General clan_members items invite lore", Arrays.asList(" &eClic para invitar a nuevos miembros" )),
	General_clan_members_items_list_name("GUI.General clan_members items list name", "&aLista de miembros"),
	General_clan_members_items_list_lore("GUI.General clan_members items list lore", Arrays.asList(" "," &7Miembros: &b%uclans_count_members%", " ", " &eClic para ver la lista de miembros" )),
	
	General_clan_ally_title("GUI.General clan_ally title", "&9&lMenú de alianzas"),
	General_clan_ally_items_fill_name("GUI.General clan_ally items fill name", " "),
	General_clan_ally_items_fill_lore("GUI.General clan_ally items fill lore", Arrays.asList()),
	General_clan_ally_items_fill2_name("GUI.General clan_ally items fill2 name", " "),
	General_clan_ally_items_fill2_lore("GUI.General clan_ally items fill2 lore", Arrays.asList()),
	General_clan_ally_items_back_name("GUI.General clan_ally items back name", "&cRegresar"),
	General_clan_ally_items_back_lore("GUI.General clan_ally items back lore", Arrays.asList(" &eClic para volver" )),
	General_clan_ally_items_invite_name("GUI.General clan_ally items invite name", "&aAgregar o quitar alianzas"),
	General_clan_ally_items_invite_lore("GUI.General clan_ally items invite lore", Arrays.asList(" &eClic para agregar o eliminar alianzas" )),
	General_clan_ally_items_list_name("GUI.General clan_ally items list name", "&aLista de alianzas"),
	General_clan_ally_items_list_lore("GUI.General clan_ally items list lore", Arrays.asList(" ", " &7Aliados: &b%uclans_clan_count_ally%", " " ," &eClic para ver la lista de alianzas" )),
	
	General_clan_rival_title("GUI.General clan_rival title", "&9&lMenú de rivalidades"),
	General_clan_rival_items_fill_name("GUI.General clan_rival items fill name", " "),
	General_clan_rival_items_fill_lore("GUI.General clan_rival items fill lore", Arrays.asList()),
	General_clan_rival_items_fill2_name("GUI.General clan_rival items fill2 name", " "),
	General_clan_rival_items_fill2_lore("GUI.General clan_rival items fill2 lore", Arrays.asList()),
	General_clan_rival_items_back_name("GUI.General clan_rival items back name", "&cRegresar"),
	General_clan_rival_items_back_lore("GUI.General clan_rival items back lore", Arrays.asList(" &eClic para volver" )),
	General_clan_rival_items_invite_name("GUI.General clan_rival items invite name", "&aAgregar o eliminar rivales"),
	General_clan_rival_items_invite_lore("GUI.General clan_rival items invite lore", Arrays.asList(" &eClic para agregar o eliminar rivales" )),
	General_clan_rival_items_list_name("GUI.General clan_rival items list name", "&aLista de rivales"),
	General_clan_rival_items_list_lore("GUI.General clan_rival items list lore", Arrays.asList(" ", " &7Rivales: &b%uclans_clan_count_rival%", " " ," &eClic para ver la lista de rivales" )),

	Pagination_rival_title("GUI.Pagination rival title", "&9&lLista de rivales."),
	Pagination_rival_items_fill_name("GUI.Pagination rival items fill name", " "),
	Pagination_rival_items_fill_lore("GUI.Pagination rival items fill lore", Arrays.asList()),
	Pagination_rival_items_back_name("GUI.Pagination rival items back name", "&cRegresar"),
	Pagination_rival_items_back_lore("GUI.Pagination rival items back lore", Arrays.asList("", " &eClic para volver.")),
	Pagination_rival_items_next_name("GUI.Pagination rival items next name", "&aSiguiente página"),
	Pagination_rival_items_next_lore("GUI.Pagination rival items next lore", Arrays.asList("", " &eClic para continuar.")),
	Pagination_rival_items_previous_name("GUI.Pagination rival items previous name", "&aPágina anterior"),
	Pagination_rival_items_previous_lore("GUI.Pagination rival items previous lore", Arrays.asList("", " &eClic para volver.")),
	Pagination_rival_items_current_name("GUI.Pagination rival items current name", "&aClan %uclans_tag_color%"),
	Pagination_rival_items_current_lore("GUI.Pagination rival items current lore", Arrays.asList("", " &eInformación del clan", " &7", " &7Nivel: &a%uclans_level%", " &7", " &7Etiqt: &b%uclans_tag_color%", " &7Líder: &b%uclans_leader%", " &7Miembros: &b%uclans_count_members%", "", " &eClic derecho para ver información.")),
	
	Pagination_ally_title("GUI.Pagination ally title", "&9&lLista de aliados."),
	Pagination_ally_items_fill_name("GUI.Pagination ally items fill name", " "),
	Pagination_ally_items_fill_lore("GUI.Pagination ally items fill lore", Arrays.asList()),
	Pagination_ally_items_back_name("GUI.Pagination ally items back name", "&cRegresar"),
	Pagination_ally_items_back_lore("GUI.Pagination ally items back lore", Arrays.asList("", " &eClic para volver.")),
	Pagination_ally_items_next_name("GUI.Pagination ally items next name", "&aSiguiente página"),
	Pagination_ally_items_next_lore("GUI.Pagination ally items next lore", Arrays.asList("", " &eClic para continuar.")),
	Pagination_ally_items_previous_name("GUI.Pagination ally items previous name", "&aPágina anterior"),
	Pagination_ally_items_previous_lore("GUI.Pagination ally items previous lore", Arrays.asList("", " &eClic para volver.")),
	Pagination_ally_items_current_name("GUI.Pagination ally items current name", "&aClan %uclans_tag_color%"),
	Pagination_ally_items_current_lore("GUI.Pagination ally items current lore", Arrays.asList("", " &eInformación del clan", " &7", " &7Nivel: &a%uclans_level%", " &7", " &7Etiqt: &b%uclans_tag_color%", " &7Líder: &b%uclans_leader%", " &7Miembros: &b%uclans_count_members%", "", " &eClic derecho para ver información.")),
	
	Pagination_members_title("GUI.Pagination members title", "&9&lLista de miembros."),
	Pagination_members_items_fill_name("GUI.Pagination members items fill name", " "),
	Pagination_members_items_fill_lore("GUI.Pagination members items fill lore", Arrays.asList()),
	Pagination_members_items_back_name("GUI.Pagination members items back name", "&cRegresar"),
	Pagination_members_items_back_lore("GUI.Pagination members items back lore", Arrays.asList("", " &eClic para volver.")),
	Pagination_members_items_next_name("GUI.Pagination members items next name", "&aSiguiente página"),
	Pagination_members_items_next_lore("GUI.Pagination members items next lore", Arrays.asList("", " &eClic para continuar.")),
	Pagination_members_items_previous_name("GUI.Pagination members items previous name", "&aPágina anterior"),
	Pagination_members_items_previous_lore("GUI.Pagination members items previous lore", Arrays.asList("", " &eClick  para volver.")),
	Pagination_members_items_current_name("GUI.Pagination members items current name", "&a%uclans_player%"),
	Pagination_members_items_current_lore("GUI.Pagination members items current lore", Arrays.asList("", " &7Líder: &b%uclans_player_leader_yes_no%", " &7Moderadores: &b%uclans_player_mod_yes_no%", " &7Nickname: &b%uclans_player%", " &7Kdr: &b%uclans_player_kills%&8/&b%uclans_player_deaths% &8(%uclans_player_kdr%)", " &7Entró: &b%uclans_player_joindate_formated%", " &7Ultima vez visto: &b%uclans_player_lastsee_formated%", " ", " &eClic para ver el perfil.")),
	
	Pagination_clans_title("GUI.Pagination clans title", "&9&lClanes verificados."),
	Pagination_clans_items_fill_name("GUI.Pagination clans items fill name", " "),
	Pagination_clans_items_fill_lore("GUI.Pagination clans items fill lore", Arrays.asList()),
	Pagination_clans_items_back_name("GUI.Pagination clans items back name", "&cRegresar"),
	Pagination_clans_items_back_lore("GUI.Pagination clans items back lore", Arrays.asList("", " &eClic para volver.")),
	Pagination_clans_items_next_name("GUI.Pagination clans items next name", "&aSiguiente página"),
	Pagination_clans_items_next_lore("GUI.Pagination clans items next lore", Arrays.asList("", " &eClic para proceder.")),
	Pagination_clans_items_previous_name("GUI.Pagination clans items previous name", "&aPágina anterior"),
	Pagination_clans_items_previous_lore("GUI.Pagination clans items previous lore", Arrays.asList("", " &eClic para volver.")),
	Pagination_clans_items_current_name("GUI.Pagination clans items current name", "&aClan %uclans_tag_color%"),
	Pagination_clans_items_current_lore("GUI.Pagination clans items current lore", Arrays.asList("", " &eInformación del clan", " &7", " &7Nivel: &a%uclans_level%", " &7", " &7Etiqt: &b%uclans_tag_color%", " &7Líder: &b%uclans_leader%", " &7Miembros: &b%uclans_count_members%", "", " &eClic derecho para ver información.")),

	Home_clan_allyhome_title("GUI.Home clan_allyhome title", "&9&lHome Aliados"),
	Home_clan_allyhome_items_back_name("GUI.Home clan_allyhome items back name", "&cRegresar"),
	Home_clan_allyhome_items_back_lore("GUI.Home clan_allyhome items back lore", Arrays.asList("", " &eClic para volver.")),
	Home_clan_allyhome_items_next_name("GUI.Home clan_allyhome items next name", "&aSiguiente página"),
	Home_clan_allyhome_items_next_lore("GUI.Home clan_allyhome items next lore", Arrays.asList("", " &eClic para proceder.")),
	Home_clan_allyhome_items_previous_name("GUI.Home clan_allyhome items previous name", "&aPágina anterior"),
	Home_clan_allyhome_items_previous_lore("GUI.Home clan_allyhome items previous lore", Arrays.asList("", " &eClic para volver.")),
	Home_clan_allyhome_items_current_name("GUI.Home clan_allyhome items current name", "&aHome %uclans_home:<num>:name% del clan %uclans_tag_color%."),
	Home_clan_allyhome_items_current_lore("GUI.Home clan_allyhome items current lore", Arrays.asList("", " &eInformación del home", " &7", " &7Clan: &b%uclans_tag_color%", " &7Server: &a%uclans_home:<num>:server%", " &7Nombre: &b%uclans_home:<num>:name%", "", " &eClic izquierdo para teletransportarte.")),
	Home_clan_allyhome_items_fill_name("GUI.Home clan_allyhome items fill name", " "),
	Home_clan_allyhome_items_fill_lore("GUI.Home clan_allyhome items fill lore", Arrays.asList()),
	
	Banner_banner_home_title("GUI.Banner banner_home title", "&9&lMenú de estandarte"),
	Banner_banner_home_items_fill_name("GUI.Banner banner_home items fill name", " "),
	Banner_banner_home_items_fill_lore("GUI.Banner banner_home items fill lore", Arrays.asList()),
	Banner_banner_home_items_fill2_name("GUI.Banner banner_home items fill2 name", " "),
	Banner_banner_home_items_fill2_lore("GUI.Banner banner_home items fill2 lore", Arrays.asList()),
	Banner_banner_home_items_current_name("GUI.Banner banner_home items current name", "&aEstandarte actual"),
	Banner_banner_home_items_current_lore("GUI.Banner banner_home items current lore", Arrays.asList(" "," &eEl estandarte del clan es tu marca","&ey tu &b&lNEXUS &eutilizado para la señalización de la tierra!","", " &b&l<< &cUsa los botones de los lados &b&l>>" )),
	Banner_banner_home_items_upload_name("GUI.Banner banner_home items upload name", "&aCargar"),
	Banner_banner_home_items_upload_lore("GUI.Banner banner_home items upload lore", Arrays.asList("", " &eClic para abrir el menú de carga.")),
	Banner_banner_home_items_delete_name("GUI.Banner banner_home items delete name", "&aEliminar un estandarte"),
	Banner_banner_home_items_delete_lore("GUI.Banner banner_home items delete lore", Arrays.asList("", " &eClic para eliminar el estandarte actual.")),
	Banner_banner_home_items_pre_name("GUI.Banner banner_home items pre name", "&aEstandartes prediseñados."),
	Banner_banner_home_items_pre_lore("GUI.Banner banner_home items pre lore", Arrays.asList("", " &eClic para abrir la lista.")),
	Banner_banner_home_items_back_name("GUI.Banner banner_home items back name", "&cRegresar"),
	Banner_banner_home_items_back_lore("GUI.Banner banner_home items back lore", Arrays.asList("", " &eClic para volver.")),
	
	Banner_banner_delete_title("GUI.Banner banner_delete title", "&c¿Confirmar eliminar el estandarte actual?"),
	Banner_banner_delete_items_fill_name("GUI.Banner banner_delete items fill name", " "),
	Banner_banner_delete_items_fill_lore("GUI.Banner banner_delete items fill lore", Arrays.asList()),
	Banner_banner_delete_items_confirm_name("GUI.Banner banner_delete items confirm name", "&aConfirmar"),
	Banner_banner_delete_items_confirm_lore("GUI.Banner banner_delete items confirm lore", Arrays.asList("", " &cClic para confirmar.")),
	Banner_banner_delete_items_cancel_name("GUI.Banner banner_delete items cancel name", "&aCancelar"),
	Banner_banner_delete_items_cancel_lore("GUI.Banner banner_delete items cancel lore", Arrays.asList("", " &eClic para cancelar.")),
	
	Banner_banner_upload_title("GUI.Banner banner_upload title", "&9&lEstandarte cargado"),
	Banner_banner_upload_items_fill_name("GUI.Banner banner_upload items fill name", " "),
	Banner_banner_upload_items_fill_lore("GUI.Banner banner_upload items fill lore", Arrays.asList()),
	Banner_banner_upload_items_fill2_name("GUI.Banner banner_upload items fill2 name", "&c¡Coloque su nuevo estandarte aquí!"),
	Banner_banner_upload_items_fill2_lore("GUI.Banner banner_upload items fill2 lore", Arrays.asList(" ", " &c¡Coloque su nuevo estandarte aquí!")),
	Banner_banner_upload_items_back_name("GUI.Banner banner_upload items back name", "&cRegresar"),
	Banner_banner_upload_items_back_lore("GUI.Banner banner_upload items back lore", Arrays.asList("", " &cClic para volver.")),
	Banner_banner_upload_items_confirm_name("GUI.Banner banner_upload items confirm name", "&aClic para guardar."),
	Banner_banner_upload_items_confirm_lore("GUI.Banner banner_upload items confirm lore", Arrays.asList("", " &eClic aquí para guardar.")),
	
	
	
	COMMANDS("COMMANDS", " ", " ", " ", " # TRANSLATIONS OF THE COMMANDS", " "),

	//CLAN COMMANDS
	
	COMMANDS_clan_help_show_on_help("COMMANDS.clan help show on_help", " &b/clan help &7-&e Mostrar menú de ayuda."),
	COMMANDS_clan_help_show_on_help_json_hover_text("COMMANDS.clan help show on_help_json hover_text", "&aClic para ver la ayuda de los clanes."),
	COMMANDS_clan_help_show_on_success("COMMANDS.clan help show on_success", "%tag% &a¡Estás viendo la ayuda!"),
	COMMANDS_clan_help_show_on_error("COMMANDS.clan help show on_error", "%tag%&cError al mostrar texto."),
	COMMANDS_clan_help_show_on_usage("COMMANDS.clan help show on_usage", "%tag% &cUsa &b/clan help"),
	
	COMMANDS_clan_create_show_on_help_json_hover_text("COMMANDS.clan create show on_help_json hover_text", "&aClic para crear un nuevo clan."),
	COMMANDS_clan_create_show_on_help("COMMANDS.clan create show on_help", " &b/clan create &7-&e Crea un nuevo clan."),
	COMMANDS_clan_create_show_on_success("COMMANDS.clan create show on_success", "%tag% &a¡Has creado un nuevo clan!"),
	COMMANDS_clan_create_show_on_error("COMMANDS.clan create show on_error", "%tag% &cError al crear un nuevo clan, inténtalo de nuevo."),
	COMMANDS_clan_create_show_on_usage("COMMANDS.clan create show on_usage", "%tag% &cUsa &b/clan create <etiqt>"),
	
	COMMANDS_clan_cancel_show_on_help_json_hover_text("COMMANDS.clan cancel show on_help_json hover_text", "&aClic para cancelar acciones pendientes."),
	COMMANDS_clan_cancel_show_on_help("COMMANDS.clan cancel show on_help", " &b/clan cancel &7-&e Cancelar acciones pendientes."),
	COMMANDS_clan_cancel_show_on_success("COMMANDS.clan cancel show on_success", "%tag% &a¡Cancelado con éxito!"),
	COMMANDS_clan_cancel_show_on_error("COMMANDS.clan cancel show on_error", "%tag% &cError al cancelar"),
	COMMANDS_clan_cancel_show_on_usage("COMMANDS.clan cancel show on_usage", "%tag% &cUse &b/clan cancel"),
	
	COMMANDS_clan_changeleader_show_on_help_json_hover_text("COMMANDS.clan changeleader show on_help_json hover_text", "&aClic para transferir el liderazgo."),
	COMMANDS_clan_changeleader_show_on_help("COMMANDS.clan changeleader show on_help", " &b/clan changeleader <jugador> &7-&e Transferir el liderazgo."),
	COMMANDS_clan_changeleader_show_on_success("COMMANDS.clan changeleader show on_success", "%tag% &aHas cambiado el liderazgo del clan a %clan_leader%"),
	COMMANDS_clan_changeleader_show_on_error("COMMANDS.clan changeleader show on_error", "%tag% &cError al transferir el liderazgo."),
	COMMANDS_clan_changeleader_show_on_usage("COMMANDS.clan changeleader show on_usage", "%tag% &cUse &b/clan changeleader <jugador>"),
	
	COMMANDS_clan_desc_show_on_help("COMMANDS.clan desc show on_help", " &b/clan desc &7-&e Añadir descripción al Clan."),
	COMMANDS_clan_desc_show_on_help_json_hover_text("COMMANDS.clan desc show on_help_json hover_text", "&aClic para agregar / cambiar la descripción de un clan."),
	COMMANDS_clan_desc_show_on_success("COMMANDS.clan desc show on_success", "%tag% &a¡Has cambiado la descripción del clan!"),
	COMMANDS_clan_desc_show_on_error("COMMANDS.clan desc show on_error", "%tag% &cError al cambiar la descripción del clan."),
	COMMANDS_clan_desc_show_on_usage("COMMANDS.clan desc show on_usage", "%tag% &cUsa &b/clan desc <descripción>"),
	
	COMMANDS_clan_disband_show_on_help("COMMANDS.clan disband show on_help", " &b/clan disband &7-&e Borra tu clan."),
	COMMANDS_clan_disband_show_on_help_json_hover_text("COMMANDS.clan disband show on_help_json hover_text", "&aClic para eliminar un clan."),
	COMMANDS_clan_disband_show_on_success("COMMANDS.clan disband show on_success", "%tag% &a¡Has eliminado tu clan!"),
	COMMANDS_clan_disband_show_on_error("COMMANDS.clan disband show on_error", "%tag% &cError al eliminar el clan, inténtalo de nuevo."),
	COMMANDS_clan_disband_show_on_usage("COMMANDS.clan disband show on_usage", "%tag% &cUsa &b/clan disband CONFIRM"),
	
	COMMANDS_clan_leave_show_on_help("COMMANDS.clan leave show on_help", " &b/clan leave &7-&e Dejar un clan."),
	COMMANDS_clan_leave_show_on_help_json_hover_text("COMMANDS.clan leave show on_help_json hover_text", "&aClic para dejar al Clan."),
	COMMANDS_clan_leave_show_on_success("COMMANDS.clan leave show on_success", "%tag% &a¡Dejaste el Clan!"),
	COMMANDS_clan_leave_show_on_error("COMMANDS.clan leave show on_error", "%tag% &cError al salir del Clan, vuelve a intentarlo."),
	COMMANDS_clan_leave_show_on_usage("COMMANDS.clan leave show on_usage", "%tag% &cUsa &b/clan leave"),
	
	COMMANDS_clan_invite_show_on_help("COMMANDS.clan invite show on_help", " &b/clan invite <player> &7-&e Invita a un jugador a tu clan."),
	COMMANDS_clan_invite_show_on_help_json_hover_text("COMMANDS.clan invite show on_help_json hover_text", "&aClic para enviar invitación al jugador"),
	COMMANDS_clan_invite_show_on_success("COMMANDS.clan invite show on_success", "%tag% &a¡Se ha enviado una invitación al jugador, ¡espere!"),
	COMMANDS_clan_invite_show_on_error("COMMANDS.clan invite show on_error", "%tag% &cError al invitar al jugador."),
	COMMANDS_clan_invite_show_on_usage("COMMANDS.clan invite show on_usage", "%tag% &cUsa &b/clan invite <jugador>"),
	

	COMMANDS_clan_join_show_on_help("COMMANDS.clan join show on_help", " &b/clan join <etiqueta> &7- &eAcepta la invitación de un jugador."),
	COMMANDS_clan_join_show_on_help_json_hover_text("COMMANDS.clan join show on_help_json hover_text", "&aClic para aceptar invitación."),
	COMMANDS_clan_join_show_on_success("COMMANDS.clan join show on_success", "%tag% &a¡Has aceptado la invitación para entrar en el clan!"),
	COMMANDS_clan_join_show_on_error("COMMANDS.clan join show on_error", "%tag% &cError al ingresar al clan, intentar otra vez."),
	COMMANDS_clan_join_show_on_usage("COMMANDS.clan join show on_usage", "%tag% &cUsa &b/clan join <etiqueta>"),
	
	COMMANDS_clan_deny_show_on_help("COMMANDS.clan deny show on_help", " &b/clan deny <etiqueta> &7- &eNegar la invitación de un jugador."),
	COMMANDS_clan_deny_show_on_help_json_hover_text("COMMANDS.clan deny show on_help_json hover_text", "&aClic para cancelar la invitación."),
	COMMANDS_clan_deny_show_on_success("COMMANDS.clan deny show on_success", "%tag% &a¡Has recibido una invitación!"),
	COMMANDS_clan_deny_show_on_error("COMMANDS.clan deny show on_error", "%tag% &cError al rechazar la invitación."),
	COMMANDS_clan_deny_show_on_usage("COMMANDS.clan deny show on_usage", "%tag% &cUsa &b/clan deny <etiqueta>"),
	
	COMMANDS_clan_kick_show_on_help("COMMANDS.clan kick show on_help", " &b/clan kick <jugador> &7-&e Eliminar jugador del clan."),
	COMMANDS_clan_kick_show_on_help_json_hover_text("COMMANDS.clan kick show on_help_json hover_text", "&aClic para eliminar a un jugador del clan"),
	COMMANDS_clan_kick_show_on_success("COMMANDS.clan kick show on_success", "%tag% &aEl jugador ha sido eliminado del clan."),
	COMMANDS_clan_kick_show_on_error("COMMANDS.clan kick show on_error", "%tag% &cError al expulsar al jugador."),
	COMMANDS_clan_kick_show_on_usage("COMMANDS.clan kick show on_usage", "%tag% &cUsa &b/clan kick <jugador>"),
	
	COMMANDS_clan_promote_show_on_help("COMMANDS.clan promote show on_help", " &b/clan promote <jugador> &7-&e Ascender al jugador a moderador."),
	COMMANDS_clan_promote_show_on_help_json_hover_text("COMMANDS.clan promote show on_help_json hover_text", "&aClic para promover al jugador."),
	COMMANDS_clan_promote_show_on_success("COMMANDS.clan promote show on_success", "%tag% &aJugador promovido a moderador del clan."),
	COMMANDS_clan_promote_show_on_error("COMMANDS.clan promote show on_error", "%tag% &cError al ascender al jugador. Vuelve a intentarlo.."),
	COMMANDS_clan_promote_show_on_usage("COMMANDS.clan promote show on_usage", "%tag% &cUsa &b/clan promote <jugador>"),
	
	COMMANDS_clan_demote_show_on_help("COMMANDS.clan demote show on_help", " &b/clan demote <jugador> &7-&e Degrada al jugador en el clan."),
	COMMANDS_clan_demote_show_on_help_json_hover_text("COMMANDS.clan demote show on_help_json hover_text", "&aClic para degradar al jugador."),
	COMMANDS_clan_demote_show_on_success("COMMANDS.clan demote show on_success", "%tag% &aEl jugador ha sido degradado en el clan."),
	COMMANDS_clan_demote_show_on_error("COMMANDS.clan demote show on_error", "%tag% &cError al degradar a este jugador. Vuelve a intentarlo"),
	COMMANDS_clan_demote_show_on_usage("COMMANDS.clan demote show on_usage", "%tag% &cUsa &b/clan demote <jugador>"),
	
	COMMANDS_clan_home_show_on_help("COMMANDS.clan home show on_help", " &b/clan home <create|delete|list|teleport>  <nombre> &7-&e Teletransportarse al home del clan."),
	COMMANDS_clan_home_show_on_help_json_hover_text("COMMANDS.clan home show on_help_json hover_text", "&aClic para teletransportarte al home del Clan."),
	COMMANDS_clan_home_show_on_success("COMMANDS.clan home show on_success", "%tag% &a¡Te has teletransportado al home del Clan!"),
	COMMANDS_clan_home_show_on_error("COMMANDS.clan home show on_error", "%tag% &cError al teletransportarse al home del clan."),
	COMMANDS_clan_home_show_on_usage("COMMANDS.clan home show on_usage", "%tag% &cUsa &b/clan home <create|delete|list|teleport> <nombre>"),
	
	COMMANDS_clan_chat_show_on_help("COMMANDS.clan chat show on_help", " &b/clan chat &7-&e Bloquea el chat para el clan o usa &b/  <msg>"),
	COMMANDS_clan_chat_show_on_help_json_hover_text("COMMANDS.clan chat show on_help_json hover_text", "&aClic para alternar el chat del clan."),
	COMMANDS_clan_chat_show_on_success("COMMANDS.clan chat show on_success", "%tag% &aChat del clan bloqueado ahora: &b%player_chat%"),
	COMMANDS_clan_chat_show_on_error("COMMANDS.clan chat show on_error", "%tag% &cError al usar el chat."),
	COMMANDS_clan_chat_show_on_usage("COMMANDS.clan chat show on_usage", "%tag% &cUsa &b/clan chat"),
	
	COMMANDS_clan_ff_show_on_help("COMMANDS.clan ff show on_help", " &b/clan ff &7-&e Alternar fuego amigo en el clan."),
	COMMANDS_clan_ff_show_on_help_json_hover_text("COMMANDS.clan ff show on_help_json hover_text", "&aClic para alternar el fuego amigo del clan."),
	COMMANDS_clan_ff_show_on_success("COMMANDS.clan ff show on_success", "%tag% &aFuego amigo del clan cambiado a &b%clan_ff%"),
	COMMANDS_clan_ff_show_on_error("COMMANDS.clan ff show on_error", "%tag% &cError al usar ff."),
	COMMANDS_clan_ff_show_on_usage("COMMANDS.clan ff show on_usage", "%tag% &cUsa &b/clan ff"),

	COMMANDS_clan_modtag_show_on_help("COMMANDS.clan modtag show on_help", " &b/clan modtag <nueva etiqueta> &7-&e Cambiar etiqueta de clan."),
	COMMANDS_clan_modtag_show_on_help_json_hover_text("COMMANDS.clan modtag show on_help_json hover_text", "&aClic para cambiar la etiqueta."),
	COMMANDS_clan_modtag_show_on_success("COMMANDS.clan modtag show on_success", "%tag% &aLa etiqueta de Clan ha cambiado a &b%clan_tag%"),
	COMMANDS_clan_modtag_show_on_error("COMMANDS.clan modtag show on_error", "%tag% &cError al cambiar la etiqueta del clan."),
	COMMANDS_clan_modtag_show_on_usage("COMMANDS.clan modtag show on_usage", "%tag% &cUsa &b/clan modtag <nueva etiqueta>"),
	
	COMMANDS_clan_list_show_on_help("COMMANDS.clan list show on_help", " &b/clan list &7-&e Lista de todos los clanes."),
	COMMANDS_clan_list_show_on_help_json_hover_text("COMMANDS.clan list show on_help_json hover_text", "&aClic para la lista de todos los clanes."),
	COMMANDS_clan_list_show_on_success("COMMANDS.clan list show on_success", "%tag% &aÉxito para usar la lista."),
	COMMANDS_clan_list_show_on_error("COMMANDS.clan list show on_error", "%tag% &cError al usar la lista."),
	COMMANDS_clan_list_show_on_usage("COMMANDS.clan list show on_usage", "%tag% &cUsa &b/clan list"),
	
	COMMANDS_clan_info_show_on_help("COMMANDS.clan info show on_help", " &b/clan info [etiqueta] &7-&e Mostrar información del clan."),
	COMMANDS_clan_info_show_on_help_json_hover_text("COMMANDS.clan info show on_help_json hover_text", "&aClic para ver la información del clan."),
	COMMANDS_clan_info_show_on_success("COMMANDS.clan info show on_success", ""),
	COMMANDS_clan_info_show_on_error("COMMANDS.clan info show on_error", "%tag% &cError al usar la información."),
	COMMANDS_clan_info_show_on_usage("COMMANDS.clan info show on_usage", "%tag% &cUse &b/clan info [etiqueta]"),
	
	COMMANDS_clan_profile_show_on_help("COMMANDS.clan profile show on_help", " &b/clan profile [jugador] &7-&e Mostrar perfil de jugador."),
	COMMANDS_clan_profile_show_on_help_json_hover_text("COMMANDS.clan profile show on_help_json hover_text", "&aClic para mostrar el perfil."),
	COMMANDS_clan_profile_show_on_success("COMMANDS.clan profile show on_success", "%tag% &aÉxito para usar el perfil."),
	COMMANDS_clan_profile_show_on_error("COMMANDS.clan profile show on_error", "%tag% &cError al usar el perfil."),
	COMMANDS_clan_profile_show_on_usage("COMMANDS.clan profile show on_usage", "%tag% &cUsa &b/clan profile [jugador]"),
	
	COMMANDS_clan_rival_show_on_help("COMMANDS.clan rival show on_help", " &b/clan rival <add/remove> <etiqueta> &7-&e Añadir clan al rival."),
	COMMANDS_clan_rival_show_on_help_json_hover_text("COMMANDS.clan rival show on_help_json hover_text", "&aClic para añadir / eliminar un rival del clan."),
	COMMANDS_clan_rival_show_on_success("COMMANDS.clan rival show on_success", "%tag% &aSe actualiza la lista de rivalidades."),
	COMMANDS_clan_rival_show_on_error("COMMANDS.clan rival show on_error", "%tag% &cError al usar rival."),
	COMMANDS_clan_rival_show_on_usage("COMMANDS.clan rival show on_usage", "%tag% &cUsa &b/clan rival <add/remove> <etiqueta>."),
	
	COMMANDS_clan_rivalries_show_on_help("COMMANDS.clan rivalries show on_help", " &b/clan rivalries &7-&e Lista de rivales"),
	COMMANDS_clan_rivalries_show_on_help_json_hover_text("COMMANDS.clan rivalries show on_help_json hover_text", "&aClic para enumerar a los rivales del clan."),
	COMMANDS_clan_rivalries_show_on_success("COMMANDS.clan rivalries show on_success", "%tag% &aÉxito al establecer rivales."),
	COMMANDS_clan_rivalries_show_on_error("COMMANDS.clan rivalries show on_error", "%tag% &cError al establecer rivales."),
	COMMANDS_clan_rivalries_show_on_usage("COMMANDS.clan rivalries show on_usage", "%tag% &cUsa &b/clan rivalries"),
	
	COMMANDS_clan_ally_show_on_help("COMMANDS.clan ally show on_help", " &b/clan ally <add/remove/accept/deny> <etiqueta> &7-&e Añadir clan como aliado."),
	COMMANDS_clan_ally_show_on_help_json_hover_text("COMMANDS.clan ally show on_help_json hover_text", "&aClic para agregar / eliminar un aliado del clan."),
	COMMANDS_clan_ally_show_on_success("COMMANDS.clan ally show on_success", "%tag% &alista de alianzas actualizada."),
	COMMANDS_clan_ally_show_on_error("COMMANDS.clan ally show on_error", "%tag% &cError al establecer un aliado."),
	COMMANDS_clan_ally_show_on_usage("COMMANDS.clan ally show on_usage", "%tag% &cUsa &b/clan ally <add/remove/accept/deny> <etiqueta>."),
	
	COMMANDS_clan_alliances_show_on_help("COMMANDS.clan alliances show on_help", " &b/clan alliances &7-&e Lista de alianzas."),
	COMMANDS_clan_alliances_show_on_help_json_hover_text("COMMANDS.clan alliances show on_help_json hover_text", "&aClic para enumerar las alianzas del Clan."),
	COMMANDS_clan_alliances_show_on_success("COMMANDS.clan alliances show on_success", "%tag% &aÉxito al usar alianzas."),
	COMMANDS_clan_alliances_show_on_error("COMMANDS.clan alliances show on_error", "%tag% &cError al usar alianzas."),
	COMMANDS_clan_alliances_show_on_usage("COMMANDS.clan alliances show on_usage", "%tag% &cUse &b/clan alliances."),
	
	COMMANDS_clan_members_show_on_help("COMMANDS.clan members show on_help", " &b/clan members &7-&e Muestra la lista de miembros."),
	COMMANDS_clan_members_show_on_help_json_hover_text("COMMANDS.clan members show on_help_json hover_text", "&aClic para ver."),
	COMMANDS_clan_members_show_on_success("COMMANDS.clan members show on_success", "%tag% &aÉxito al usar miembros."),
	COMMANDS_clan_members_show_on_error("COMMANDS.clan members show on_error", "%tag% &cError al usar miembros."),
	COMMANDS_clan_members_show_on_usage("COMMANDS.clan members show on_usage", "%tag% &cUsa &6/clan members"),
	
	COMMANDS_clan_settings_show_on_help("COMMANDS.clan settings show on_help", " &b/clan settings <TIPO> <VALOR> &7-&e Cambiar la configuración del clan."),
	COMMANDS_clan_settings_show_on_help_json_hover_text("COMMANDS.clan settings show on_help_json hover_text", "&aClic para cambiar la configuración del clan"),
	COMMANDS_clan_settings_show_on_success("COMMANDS.clan settings show on_success", "%tag% &aLa configuración del clan cambió a &b%type%&7:&b%value%"),
	COMMANDS_clan_settings_show_on_error("COMMANDS.clan settings show on_error", "%tag% &cSe produjo un error al cambiar la configuración del clan."),
	COMMANDS_clan_settings_show_on_usage("COMMANDS.clan settings show on_usage", "%tag% &cUsa &b/clan settings <TIPO> <VALOR>"),
	
	COMMANDS_clan_regroup_show_on_help("COMMANDS.clan regroup show on_help", " &b/clan regroup <send/accept/deny> &7-&e Reagrupar el clan"),
	COMMANDS_clan_regroup_show_on_help_json_hover_text("COMMANDS.clan regroup show on_help_json hover_text", "&aHaga clic para reagrupar el clan"),
	COMMANDS_clan_regroup_show_on_success("COMMANDS.clan regroup show on_success", "%tag% &aSe ha enviado la solicitud de reagrupamiento."),
	COMMANDS_clan_regroup_show_on_error("COMMANDS.clan regroup show on_error", "%tag% &cOcurrió un error al enviar la solicitud."),
	COMMANDS_clan_regroup_show_on_usage("COMMANDS.clan regroup show on_usage", "%tag% &cUsa &b/clan regroup <send/accept/deny>"),
	
	COMMANDS_clan_banner_show_on_help("COMMANDS.clan banner show on_help", " &b/clan banner <open|send|delete> &7-&e Estandarte del clan"),
	COMMANDS_clan_banner_show_on_help_json_hover_text("COMMANDS.clan banner show on_help_json hover_text", "&aClic para cambiar el estandarte del clan"),
	COMMANDS_clan_banner_show_on_success("COMMANDS.clan banner show on_success", "%tag% &a¡El nuevo estandarte se guardó correctamente!"),
	COMMANDS_clan_banner_show_on_error("COMMANDS.clan banner show on_error", "%tag% &cHubo un error al guardar."),
	COMMANDS_clan_banner_show_on_usage("COMMANDS.clan banner show on_usage", "%tag% &cUsa &b/clan banner <open|send|delete>"),
	
	// UCLANS COMMANDS
	COMMANDS_uclan_help_show_on_help("COMMANDS.uclan help show on_help", " &4/uclan help &7-&e Mostrar menú de ayuda."),
	COMMANDS_uclan_help_show_on_help_json_hover_text("COMMANDS.uclan help show on_help_json hover_text", "&aClic para ver la ayuda de los clanes."),
	COMMANDS_uclan_help_show_on_success("COMMANDS.uclan help show on_success", "%tag% &aÉxito para utilizar la ayuda."),
	COMMANDS_uclan_help_show_on_error("COMMANDS.uclan help show on_error", "%tag% &cError al utilizar la ayuda"),
	COMMANDS_uclan_help_show_on_usage("COMMANDS.uclan help show on_usage", "%tag% &cError usa &b/uclan help"),
	
	COMMANDS_uclan_chatspy_show_on_help("COMMANDS.uclan chatspy show on_help", " &4/uclan chatspy &7-&e Espiar el chat del clan"),
	COMMANDS_uclan_chatspy_show_on_help_json_hover_text("COMMANDS.uclan chatspy show on_help_json hover_text", "&aClic para espiar el chat del clan"),
	COMMANDS_uclan_chatspy_show_on_success("COMMANDS.uclan chatspy show on_success", "%tag% &aChat Spy está ahora: %state%"),
	COMMANDS_uclan_chatspy_show_on_error("COMMANDS.uclan chatspy show on_error", "%tag% &cOcurrió un error al cambiar."),
	COMMANDS_uclan_chatspy_show_on_usage("COMMANDS.uclan chatspy show on_usage", "%tag% &cUsa &4/uclan chatspy"),
	
	COMMANDS_uclan_addslot_show_on_help("COMMANDS.uclan addslot show on_help", " &4/uclan addslot <jugador|etiqt> <cantidad> &7-&e Agrega espacios al Clan."),
	COMMANDS_uclan_addslot_show_on_help_json_hover_text("COMMANDS.uclan addslot show on_help_json hover_text", "&aClic para agregar espacios al clan"),
	COMMANDS_uclan_addslot_show_on_success("COMMANDS.uclan addslot show on_success", "%tag% &aHas añadido %num% espacios para el %clan% clan"),
	COMMANDS_uclan_addslot_show_on_error("COMMANDS.uclan addslot show on_error", "%tag% &cHubo un error al agregar."),
	COMMANDS_uclan_addslot_show_on_usage("COMMANDS.uclan addslot show on_usage", "%tag% &cUsa &4/uclan addslot <jugador|etiqt> <cantidad>"),
	
	COMMANDS_uclan_setslot_show_on_help("COMMANDS.uclan setslot show on_help", " &4/uclan setslot <jugador|etiqt> <cantidad> &7-&e Establecer espacios para el Clan."),
	COMMANDS_uclan_setslot_show_on_help_json_hover_text("COMMANDS.uclan setslot show on_help_json hover_text", "&aClic para establecer espacios para el clan"),
	COMMANDS_uclan_setslot_show_on_success("COMMANDS.uclan setslot show on_success", "%tag% &aHa establecido %num% espacios para el %clan% clan"),
	COMMANDS_uclan_setslot_show_on_error("COMMANDS.uclan setslot show on_error", "%tag% &cHubo un error al agregar."),
	COMMANDS_uclan_setslot_show_on_usage("COMMANDS.uclan setslot show on_usage", "%tag% &cUse &4/uclan setslot <jugador|etiqt> <cantidad>"),
	
	COMMANDS_uclan_removeslot_show_on_help("COMMANDS.uclan removeslot show on_help", " &4/uclan removeslot <jugador|etiqt> <cantidad> &7-&e Eliminar espacios al Clan."),
	COMMANDS_uclan_removeslot_show_on_help_json_hover_text("COMMANDS.uclan removeslot show on_help_json hover_text", "&aClic para eliminar las ranuras del clan."),
	COMMANDS_uclan_removeslot_show_on_success("COMMANDS.uclan removeslot show on_success", "%tag% &aTe has quitado %num% espacios para el %clan% clan"),
	COMMANDS_uclan_removeslot_show_on_error("COMMANDS.uclan removeslot show on_error", "%tag% &cThere was an error adding."),
	COMMANDS_uclan_removeslot_show_on_usage("COMMANDS.uclan removeslot show on_usage", "%tag% &cUse &4/uclan removeslot <jugador|etiqt> <cantidad>"),
	
	COMMANDS_uclan_addpoints_show_on_help("COMMANDS.uclan addpoints show on_help", " &4/uclan addpoints <jugador|etiqt> <cantidad> &7-&e Suma puntos al Clan."),
	COMMANDS_uclan_addpoints_show_on_help_json_hover_text("COMMANDS.uclan addpoints show on_help_json hover_text", "&aClic para agregar puntos al clan"),
	COMMANDS_uclan_addpoints_show_on_success("COMMANDS.uclan addpoints show on_success", "%tag% &aHas añadido %num% puntos para el %clan% clan"),
	COMMANDS_uclan_addpoints_show_on_error("COMMANDS.uclan addpoints show on_error", "%tag% &cHubo un error al agregar."),
	COMMANDS_uclan_addpoints_show_on_usage("COMMANDS.uclan addpoints show on_usage", "%tag% &cUse &4/uclan addpoints <jugador|etiqt> <cantidad>"),
	
	COMMANDS_uclan_setpoints_show_on_help("COMMANDS.uclan setpoints show on_help", " &4/uclan setpoints <jugador|etiqt> <cantidad> &7-&e establecer puntos para el Clan."),
	COMMANDS_uclan_setpoints_show_on_help_json_hover_text("COMMANDS.uclan setpoints show on_help_json hover_text", "&aClic para establecer puntos para el clan"),
	COMMANDS_uclan_setpoints_show_on_success("COMMANDS.uclan setpoints show on_success", "%tag% &aHa establecido %num% puntos para el %clan% clan"),
	COMMANDS_uclan_setpoints_show_on_error("COMMANDS.uclan setpoints show on_error", "%tag% &cHubo un error al agregar."),
	COMMANDS_uclan_setpoints_show_on_usage("COMMANDS.uclan setpoints show on_usage", "%tag% &cUse &4/uclan setpoints <jugador|etiqt> <cantidad>"),
	
	COMMANDS_uclan_removepoints_show_on_help("COMMANDS.uclan removepoints show on_help", " &4/uclan removepoints <jugador|etiqt> <cantidad> &7-&e Quitar puntos al Clan."),
	COMMANDS_uclan_removepoints_show_on_help_json_hover_text("COMMANDS.uclan removepoints show on_help_json hover_text", "&aClic para quitar puntos al clan"),
	COMMANDS_uclan_removepoints_show_on_success("COMMANDS.uclan removepoints show on_success", "%tag% &aHas quitado %num% puntos a el %clan% clan"),
	COMMANDS_uclan_removepoints_show_on_error("COMMANDS.uclan removepoints show on_error", "%tag% &cHubo un error al eliminar."),
	COMMANDS_uclan_removepoints_show_on_usage("COMMANDS.uclan removepoints show on_usage", "%tag% &cUse &4/uclan removepoints <jugador|etiqt> <cantidad>"),
	
	
	COMMANDS_uclan_changetag_show_on_help("COMMANDS.uclan changetag show on_help", " &4/uclan changetag <etiqt> <nueva etiqueta> &7-&e Cambiar una etiqueta de clan."),
	COMMANDS_uclan_changetag_show_on_help_json_hover_text("COMMANDS.uclan changetag show on_help_json hover_text", "&aClic para cambiar una etiqueta de clan."),
	COMMANDS_uclan_changetag_show_on_success("COMMANDS.uclan changetag show on_success", "%tag% &aLa etiqueta del clan &b%clan% &aha sido cambiado a &b%newtag%"),
	COMMANDS_uclan_changetag_show_on_error("COMMANDS.uclan changetag show on_error", "%tag% &cOcurrió un error al cambiar la etiqueta."),
	COMMANDS_uclan_changetag_show_on_usage("COMMANDS.uclan changetag show on_usage", "%tag% &cErro usa &4/uclan changetag <tag> <newtag>"),
	
	COMMANDS_uclan_resetplayerkdr_show_on_help("COMMANDS.uclan resetplayerkdr show on_help", " &4/uclan resetplayerkdr <jugador> &7-&e Reiniciar el KDR del jugador."),
	COMMANDS_uclan_resetplayerkdr_show_on_help_json_hover_text("COMMANDS.uclan resetplayerkdr show on_help_json hover_text", "&aClic para restablecer el KDR de jugador"),
	COMMANDS_uclan_resetplayerkdr_show_on_success("COMMANDS.uclan resetplayerkdr show on_success", "%tag% &aHas restablecido el KDR del jugador. &a%player%"),
	COMMANDS_uclan_resetplayerkdr_show_on_error("COMMANDS.uclan resetplayerkdr show on_error", "%tag% &cOcurrió un error al restablecer"),
	COMMANDS_uclan_resetplayerkdr_show_on_usage("COMMANDS.uclan resetplayerkdr show on_usage", "%tag% &cUsa &4/uclan resetplayerkdr <jugador>"),
	
	COMMANDS_uclan_resetclankdr_show_on_help("COMMANDS.uclan resetclankdr show on_help", " &4/uclan resetclankdr <tag> &7-&e Reiniciar KDR del Clan."),
	COMMANDS_uclan_resetclankdr_show_on_help_json_hover_text("COMMANDS.uclan resetclankdr show on_help_json hover_text", "&aClic para restablecer KDR del Clan"),
	COMMANDS_uclan_resetclankdr_show_on_success("COMMANDS.uclan resetclankdr show on_success", "%tag% &aHas restablecido el KDR del clan &a%uclans_tag_color%"),
	COMMANDS_uclan_resetclankdr_show_on_error("COMMANDS.uclan resetclankdr show on_error", "%tag% &cOcurrió un error al restablecer"),
	COMMANDS_uclan_resetclankdr_show_on_usage("COMMANDS.uclan resetclankdr show on_usage", "%tag% &cUsa &4/uclan resetclankdr <etiqueta>"),
	
	COMMANDS_uclan_globalff_show_on_help("COMMANDS.uclan globalff show on_help", " &4/uclan globalff &7-&e Cambiar global el ff."),
	COMMANDS_uclan_globalff_show_on_help_json_hover_text("COMMANDS.uclan globalff show on_help_json hover_text", "&aClic en cambiar global FF"),
	COMMANDS_uclan_globalff_show_on_success("COMMANDS.uclan globalff show on_success", "%tag% &aHa cambiado un ff global a &b%globalff%"),
	COMMANDS_uclan_globalff_show_on_error("COMMANDS.uclan globalff show on_error", "%tag% &cError al usar globaff."),
	COMMANDS_uclan_globalff_show_on_usage("COMMANDS.uclan globalff show on_usage", "%tag% &cUsa &4/uclan globalff"),
	
	COMMANDS_uclan_delete_show_on_help("COMMANDS.uclan delete show on_help", " &4/uclan delete <etiqueta> &7-&e Eliminar un nuevo clan."),
	COMMANDS_uclan_delete_show_on_help_json_hover_text("COMMANDS.uclan delete show on_help_json hover_text", "&aClic para eliminar un clan."),
	COMMANDS_uclan_delete_show_on_success("COMMANDS.uclan delete show on_success", "%tag% &aHas eliminado un clan!"),
	COMMANDS_uclan_delete_show_on_error("COMMANDS.uclan delete show on_error", "%tag% &cError al eliminar el clan."),
	COMMANDS_uclan_delete_show_on_usage("COMMANDS.uclan delete show on_usage", "%tag% &cUsa &4/uclan delete <etiqueta>"),
	
	COMMANDS_uclan_forcejoin_show_on_help("COMMANDS.uclan forcejoin show on_help", " &4/uclan forcejoin <jugador> <etiqueta> &7-&e Agregar un jugador a un clan."),
	COMMANDS_uclan_forcejoin_show_on_help_json_hover_text("COMMANDS.uclan forcejoin show on_help_json hover_text", "&aClic para añadir un jugador a un clan.."),
	COMMANDS_uclan_forcejoin_show_on_success("COMMANDS.uclan forcejoin show on_success", "%tag% &a¡Añadiste el jugador!"),
	COMMANDS_uclan_forcejoin_show_on_error("COMMANDS.uclan forcejoin show on_error", "%tag% &cError al agregar jugador."),
	COMMANDS_uclan_forcejoin_show_on_usage("COMMANDS.uclan forcejoin show on_usage", "%tag% &cUsa &4/uclan forcejoin <jugador> <etiqueta>"),
	
	COMMANDS_uclan_verify_show_on_help("COMMANDS.uclan verify show on_help", " &4/uclan verify <tag> &7-&e Verificar un clan."),
	COMMANDS_uclan_verify_show_on_help_json_hover_text("COMMANDS.uclan verify show on_help_json hover_text", "&aClic para verificar un Clan."),
	COMMANDS_uclan_verify_show_on_success("COMMANDS.uclan verify show on_success", "%tag% &a¡Has activado la verificación del clan!"),
	COMMANDS_uclan_verify_show_on_error("COMMANDS.uclan verify show on_error", "%tag% &cError al comprobar el clan."),
	COMMANDS_uclan_verify_show_on_usage("COMMANDS.uclan verify show on_usage", "%tag% &cUsa &4/uclan verify <etiqueta>"),
	
	COMMANDS_uclan_reload_show_on_help("COMMANDS.uclan reload show on_help", " &4/uclan reload &7-&e Recargar el complemento."),
	COMMANDS_uclan_reload_show_on_help_json_hover_text("COMMANDS.uclan reload show on_help_json hover_text", "&aClic para recargar las configuraciones del complemento."),
	COMMANDS_uclan_reload_show_on_success("COMMANDS.uclan reload show on_success", "%tag% &aEl complemento se recargó correctamente &7(%time%)."),
	COMMANDS_uclan_reload_show_on_error("COMMANDS.uclan reload show on_error", "%tag% &cError al volver a cargar la configuración."),
	COMMANDS_uclan_reload_show_on_usage("COMMANDS.uclan reload show on_usage", "%tag% &cUsa &4/uclan reload"), 
	
	COMMANDS_uclan_reloadaddons_show_on_help("COMMANDS.uclan reloadaddons show on_help", " &4/uclan reloadaddons &7-&e Recargar los complementos."),
	COMMANDS_uclan_reloadaddons_show_on_help_json_hover_text("COMMANDS.uclan reloadaddons show on_help_json hover_text", "&aClic para recargar complementos."),
	COMMANDS_uclan_reloadaddons_show_on_success("COMMANDS.uclan reloadaddons show on_success", "%tag% &a¡Los complementos se han recargado correctamente! &7(%time%)."),
	COMMANDS_uclan_reloadaddons_show_on_error("COMMANDS.uclan reloadaddons show on_error", "%tag% &cError al recargar complementos."),
	COMMANDS_uclan_reloadaddons_show_on_usage("COMMANDS.uclan reloadaddons show on_usage", "%tag% &cUsa &4/uclan reloadaddons"), 
	
	;
	
	private String path;
    private Object defaultValue;
    private String[] comments; 

    Lang(String path, Object defaultValue, String... comments) {
        this.path = path;
        this.defaultValue = defaultValue;
        this.comments = comments;
    }

    @Override
    public String getPath() {
    	
        return path;
    }

    @Override
    public Object getDefaultValue() {
        return defaultValue;
    }

    @Override
    public String[] getComments() {
        return comments;
    }

    
}