name: UltimateClans
main: me.ulrich.clans.Clans
version: 1.0
author: UlrichBR
website: https://www.spigotmc.org/resources/authors/543977/
description: The best and most complete system of clans and lands.
api-version: 1.13