package me.ulrich.clans.manager.EnumFiles.en_us;

import java.util.Arrays;

import me.ulrich.clans.packets.methods.enums.interfaces.ConfigurationEnum;


public enum Lang implements ConfigurationEnum  {
	
	LANGUAGE("LANGUAGE", " ", " ", " ", " # TRANSLATIONS OF THE LANGUAGE AND DIALOGUE FILES", " "),
	
	TAG("LANGUAGE.tag", "&6&lU&9&lClans &r&7|"),
	COMMAND_BY_PLAYER("LANGUAGE.command by player","%tag% &cThis command must be used by a player."),
	COMMAND_BY_CONSOLE("LANGUAGE.command by console","%tag% &cThis command must be used by a CONSOLE."),

	EMPTY_CHAT_HELP("LANGUAGE.empty chat help","%tag% &cError, Use &b/. <message>"),
	DISABLED_WORLD_COMMAND("LANGUAGE.disabled world command","%tag% &cClan commands are turned off in this world."),
	ERROR_START_ACTION("LANGUAGE.error start action","%tag% &cThere was an error running this."),
	ERROR_CHARACTER("LANGUAGE.error character","%tag% &cThis contains invalid characters."),
	ERROR_MOD_DESC("LANGUAGE.error mod desc","%tag% &cError changing the Clan description."),
	HAS_GLOBALFF("LANGUAGE.has globalff","%tag% &aGlobal friendly fire is now on!"),
	NO_PERMISSION("LANGUAGE.no permission","%tag% &cYou do not have permission"), 
	CHEST_EXTRA_BUYED_UPDATE("LANGUAGE.chest extra buyed update","%tag% &b%player% &ahas purchased a new Chest for the Clan."), 
	REGION_LIST_HEADER("LANGUAGE.region list header","&9&lList of regions:"), 
	REGION_LIST_EMPTY("LANGUAGE.region list empty","&8 - There are no saved regions"), 
	REGION_LIST_FORMAT("LANGUAGE.region list format"," &b%region_name% &7- %region_creator% &7- &b%region_firstpoint%&7/&b%region_secondpoint%"),
	REGION_NOT_EXISTS("LANGUAGE.region not exists","%tag% &cThere is no region with this name."),
	REGION_EXISTS("LANGUAGE.region exists","%tag% &cThere is already a region with this name."),
	CLAN_TAG_IN_USE("LANGUAGE.tag in use","%tag% &cThis Tag is already in use."),
	CLAN_NOT_FOUND("LANGUAGE.clan not found","%tag% &cClan with this TAG does not exist."),
	CLAN_ALLY_HEADER("LANGUAGE.clan ally header","&9&lList of Allies. &8(tag/kdr/members)"), 
	CLAN_LIST_EMPTY("LANGUAGE.clan list empty"," &cNo Clan in this list."), 
	CLAN_IS_YOUR_CLAN("LANGUAGE.clan is your clan","%tag% &cThis is your Clan."), 
	CLAN_IS_RIVAL("LANGUAGE.clan is rival","%tag% &cThis Clan is already an rival."), 
	CLAN_ALREADY_ALLY("LANGUAGE.clan already ally","%tag% &cThis Clan is already an ally."), 
	CLAN_DONT_ALLY("LANGUAGE.clan dont ally","%tag% &cThis Clan is not an ally."), 
	CLAN_PLAYER_ISNOT_YOUR_CLAN("LANGUAGE.clan player isnot your clan","%tag% &cThis player is not in your Clan."), 
	CLAN_MAX_MEMBERS("LANGUAGE.clan max members","&cThis Clan already has the maximum number of players."), 
	CLAN_MAX_MEMBERS_LEVEL("LANGUAGE.clan max members level","%tag% &cThis clan already has the maximum number of players for the current level."), 
	CLAN_PLAYER_KICKED_OUT("LANGUAGE.clan player kicked out","%tag% &aYou have been kicked out of the clan &b%clan% &cby &a%clan_leader%"),
	CLAN_PLAYER_KICKED_OUTBY("LANGUAGE.clan player kicked outby","%tag% &4%player% &ehas been kicked out of the clan by &a%clan_leader%"), 
	CLAN_TAG_EQUALS("LANGUAGE.clan tag equals","%tag% &cUnchanged TAG, appears to be the same."),
	CLAN_NAME_EQUALS("LANGUAGE.clan name equals","%tag% &cUnchanged NAME, appears to be the same."), 
	CLAN_ALREADY_RIVAL("LANGUAGE.clan already rival","%tag% &cThis Clan is already a rival."), 
	CLAN_IS_ALLY("LANGUAGE.clan is ally","%tag% &cThis Clan is already an ally."), 
	CLAN_RIVAL_ERROR_ADD("LANGUAGE.clan rival error add","%tag% &cError adding rival."), 
	CLAN_RIVAL_ERROR_REMOVE("LANGUAGE.clan rival error remove","%tag% &cError removing rival."), 
	CLAN_DONT_RIVAL("LANGUAGE.clan dont rival","%tag% &cThis Clan is not a rival."), 
	CLAN_NEW_ALLY("LANGUAGE.clan new ally","%tag% &c&l! &eA new alliance was formed with the clan &a%clan_tag%"), 
	CLAN_REMOVED_ALLY("LANGUAGE.clan removed ally","%tag% &c&l! &eThe alliance with the clan &a%clan_tag% &ehas removed."), 
	CLAN_ONE_REMOVED_ALLY("LANGUAGE.clan one removed ally","%tag% &c&l! &eAn alliance has been removed."), 
	CLAN_ONE_REMOVED_RIVAL("LANGUAGE.clan one removed rival","%tag% &c&l! &eAn rivalrie has been removed."),
	CLAN_CREATED("LANGUAGE.clan created","%tag% &c&l! &eA new Clan &b%clan_tag% &ewas created by &a%player%."), 
	CLAN_DELETED("LANGUAGE.clan deleted","%tag% &c&l! &eThe Clan &b%clan_tag% &ewas deleted by &a%player%."), 
	CLAN_DELETED_SMALL("LANGUAGE.clan deleted small","&c&mDeleted"), 
	CLAN_FF_CHANGED("LANGUAGE.clan ff changed","%tag% &c&l! &eThe friendly fire is &b%value%."), 
	CLAN_GLOBALFF_CHANGED("LANGUAGE.clan globalff changed","%tag% &c&l! &eGlobal friendly fire is &b%value%."), 
	CLAN_NEW_JOIN("LANGUAGE.clan new join","%tag% &c&l! &eThe player &a%player% &eentered the Clan."),
	CLAN_NEW_KICK("LANGUAGE.clan new kick","%tag% &c&l! &eThe player &a%player% &ewas expelled from the Clan."), 
	CLAN_NEW_RIVAL("LANGUAGE.clan new rival","%tag% &c&l! &eNew rivalry with the Clan &a%clan_tag%"), 
	CLAN_NEW_LEADER("LANGUAGE.clan new leader","%tag% &c&l! &eNew leader of clan &a%clan_tag% &eis &a%player%"),
	CLAN_RIVAL_REMOVED("LANGUAGE.clan rival removed","%tag% &c&l! &eThe rivalry with the Clan &a%clan_tag% &ewas undone."), 
	CLAN_VERIFY_CHANGED("LANGUAGE.clan verify changed","%tag% &c&l! &eThe clan was changed to &a%value%."), 
	CLAN_NEW_PROMOTE("LANGUAGE.clan new promote","%tag% &c&l! &eThe player &a%player% &egot promoted."), 
	CLAN_NEW_DEMOTE("LANGUAGE.clan new demote","%tag% &c&l! &cThe player &a%player% &ewas demoted."), 
	CLAN_PVP_DISABLED("LANGUAGE.clan pvp disabled","%tag% &cClan PVP is now turned off."),
	CLAN_ALLYPVP_DISABLED("LANGUAGE.clan allypvp disabled","%tag% &cPVP between allies is off."),
	CLAN_TAG_BLACKLIST("LANGUAGE.clan tag blacklist","%tag% &cThis Tag cannot be used in Clans."),
	CLAN_CHANGED_SETTINGS("LANGUAGE.clan changed settings","%tag% &aClan settings have been changed."),
	
	CLAN_SETTINGS_WARINVITE("LANGUAGE.clan settings warinvite","&bWar Invite"),
	CLAN_SETTINGS_ALLYSHAREDCHAT("LANGUAGE.clan settings allysharedchat","&bAlly shared chat"),
	CLAN_SETTINGS_JOINLEAVE("LANGUAGE.clan settings joinleave","&bJoin and Leave"),
	CLAN_SETTINGS_ALLYSHAREDHOME("LANGUAGE.clan settings allysharedhome","&bAlly shared homes"),
	CLAN_SETTINGS_CLANFF("LANGUAGE.clan settings clanff","&bClan FF"),
	
	CLAN_DELETE_ERROR_GUI("LANGUAGE.clan delete error gui","&4Error deleting!"), 
	CLAN_NO_ACTIONS("LANGUAGE.clan no actions","%tag% &cThere are no outstanding actions to cancel."), 
	HELP_UCLAN_HEADER("LANGUAGE.help uclan header","&4&lAdmin Clan Help:"), 
	HELP_CLAN_HEADER("LANGUAGE.help clan header","&9&lHelp with Clan:"), 
	HELP_INFO_HEADER("LANGUAGE.help info header","&9&lClan Information &8%clan_tag%&9&l:"), 
	HELP_INFO_EMPTY("LANGUAGE.help info empty","&cNothing here"), 
	HELP_CLANLIST("LANGUAGE.help clanlist","&9&lList of Clans: &8(rank/tag/desc/kdr/members)"),
	HELP_CLANLIST_SUBHEADER("LANGUAGE.help clanlist subheader"," &8Showing %cur%/%amount% of %total% (Page: %pag_cur%/%pag_max%)"),
	HELP_PROFILE_HEADER("LANGUAGE.help profile header","&9&lProfile of &a%player%&9&l:"),

	HELP_RIVAL_HEADER("LANGUAGE.help rival header","&9&lList of Rivals. &8(tag/kdr/members)"), 
	HELP_STATS_HEADER("LANGUAGE.help stats header","&9&lClan Status &a%clan_tag%&9&l:"),
	HELP_STATS_FORMAT_PLAYER("LANGUAGE.help stats format player","  &7&a%list_player% &7- &b%list_player_role% &7- &b%list_player_kills%&8/&b%list_player_deaths% &8(%list_player_kdr%) &7[%list_player_seen_date%]"),
	
	TRANSLACTION_PLAYER("LANGUAGE.translaction players","players"), 
	TRANSLACTION_IS_ON("LANGUAGE.translaction is on","&a&lOnline"), 
	TRANSLACTION_IS_OFF("LANGUAGE.translaction is off","&c&lOffline"), 
	TRANSLACTION_YES("LANGUAGE.translaction yes","&b&lYES"),
	TRANSLACTION_NO("LANGUAGE.translaction no","&c&lNO"),
	
	
	PLAYER_DONT_LEADER("LANGUAGE.clan dont leader","%tag% &cYou are not the leader of the Clan."),
	PLAYER_DONT_PERMISSION_TO_DEMOTE("LANGUAGE.clan dont permission top demote","%tag% &cYou cannot demote players."), 
	PLAYER_DONT_PERMISSION_TO_PROMOTE("LANGUAGE.clan dont permission top promote","%tag% &cYou cannot promote players."),
	PLAYER_NO_INVITATIONS("LANGUAGE.player no invitation","%tag% &cYou have no invitations."), 
	PLAYER_DONT_MOD_AND_LEADER("LANGUAGE.clan dont mod and leader","%tag% &cYou are not the leader or Mod of the Clan."), 
	PLAYER_DONT_MOD_AND_LEADER_GUI("LANGUAGE.clan dont mod and leader gui","&cRequires &4&lLeader &cor &4&lMod&c!"), 
	PLAYER_DONT_MOD("LANGUAGE.player dont mod","%tag% &cThis player is not a moderator."), 
	PLAYER_IS_MOD("LANGUAGE.player is mod","%tag% &cThis player is already a moderator."), 
	PLAYER_OFFLINE("LANGUAGE.player offline","%tag% &cThe player is offline or does not exist!"),
	PLAYER_CANNOT_EXPEL_LEADER("LANGUAGE.player cannot expel leader","%tag% &cYou cannot expel the Clan Leader."), 
	PLAYER_CANNOT_EXPEL_MOD("LANGUAGE.player cannot expel mod","%tag% &cA moderator cannot expel another from the same position."),
	PLAYER_IS_CLAN_LEADER("LANGUAGE.player is clan leader","%tag% &cYou are the Clan Leader, to leave use &b/clan disband&c and you will delete the Clan ..."), 
	YOU_DONT_HAVE_CLAN("LANGUAGE.you donthave clan","%tag% &cYou dont have a Clan."),
	PLAYER_DONT_HAVE_CLAN("LANGUAGE.player donthave clan","%tag% &cThis player does not have a clan."),
	PLAYER_HAVE_CLAN("LANGUAGE.player have clan","%tag% &cYou already have a clan."), 
	PLAYER_HAS_CLAN("LANGUAGE.player has clan","%tag% &cThis player already has a clan."), 
	PLAYER_IS_YOU("LANGUAGE.player is you","%tag% &cThis player is you."), 
	PLAYER_DONT_HAVE_MONEY("LANGUAGE.player dont have money","%tag% &cYou need to &a$%amount% &cfor this."), 
	PLAYER_DONT_HAVE_MONEY_GUI("LANGUAGE.player dont have money gui","&cYou need to &a$%amount%"), 
	PLAYER_DEBITED_MONEY("LANGUAGE.player debited money","%tag% &aIt was debited &a%amount% &eyour account."), 
	PLAYER_DEPOSITED_MONEY("LANGUAGE.player deposited money","%tag% &a$%amount% &ehas been deposited in your account."), 

	PLAYER_INVITATION_EXPIRED("LANGUAGE.player invitation expired","%tag% &cYour invitation to join the Clan &f%clan_tag% &cehas expired."), 
	PLAYER_INVITATION_DANIED("LANGUAGE.player invitation daniel","%tag% &cThe player denied the invitation."), 

	PLAYER_ALREADY_INVITED("LANGUAGE.player already invited","%tag% &cThere is already an invitation for this player in progress!"), 

	GUI_ERROR("LANGUAGE.gui error","%tag% &cThis menu contains an error and cannot be opened"), 
	PLAYER_TELEPORT_DONT_MOVE("LANGUAGE.player teleport dont move","%tag% &aPreparing teleport, do not move by %sec% sec."), 
	PLAYER_TELEPORT_MOVED("LANGUAGE.player teleport moved","%tag% &cYou moved and the teleport was canceled!!!"), 
	PLAYER_TELEPORT_TRUE("LANGUAGE.player teleport true","%tag% &aYou were teleported!"),
	PLAYER_TELEPORT_FALSE("LANGUAGE.player teleport false","%tag% &cYou have not been teleported for any mistake!"), 
	UNKNOWN_ERROR("LANGUAGE.unknown error","%tag% &cAn unknown error occurred with this, please try again!"),
	NOTHING_HERE("LANGUAGE.nothing here","&cNothing here."), 
	CLAN_EMPTY_NAME("LANGUAGE.clan empty name","&c<Without name!>"),
	CLAN_EMPTY_DESC("LANGUAGE.clan empty desc","&c<Without description!>"),
	
	JSON_ADVANCED_ACTION_CREATE("LANGUAGE.json advanced action create","%tag% &7Type in the chat the name of the new clan you want to create or use &c/clan cancel &r&7to cancel!"),
	JSON_ADVANCED_ACTION_DISBAND("LANGUAGE.json advanced action disband","%tag% &7Type &b&l%confirm_action% &r&7in the chat to confirm or use &c/clan cancel &r&7to cancel!"),
	JSON_ADVANCED_ACTION_CHANGELEADER("LANGUAGE.json advanced action changeleder","%tag% &7Type &b&l%confirm_action% &r&7in the chat to confirm or use &c/clan cancel &r&7to cancel!"),
	JSON_ADVANCED_ACTION_MODTAG("LANGUAGE.json advanced action modtag","%tag% &7Type in the chat the new TAG of the clan or use &c/clan cancel &r&7to cancel!"),
	JSON_ADVANCED_ACTION_DESC("LANGUAGE.json advanced action desc","%tag% &7Type in the chat the new clan description or use &c/clan cancel &r&7to cancel!"),
	JSON_ADVANCED_ACTION_NAME("LANGUAGE.json advanced action name","%tag% &7Type in the chat the new clan name or use &c/clan cancel &r&7to cancel!"),
	JSON_ADVANCED_ACTION_INVITE("LANGUAGE.json advanced action invite","%tag% &7Write in the chat who you want to invite to the clan or use &c/clan cancel &r&7to cancel!"),
	JSON_ADVANCED_INVITE_RECEIVED("LANGUAGE.json simple invite received"," &c&l! &eYou have received an invitation to join the Clan &f%clan_tag%&e, the invitation expires on &b%sec_expires% sec&e. &eUse &b/clan join %clan_tag_nocolor% &eor &b/clan deny %clan_tag_nocolor%"),
	JSON_ADVANCED_HELP_PAGINATION("LANGUAGE.json advanced help pagination"," &cFor next use: &b/clan help [page]"),
	
	JSON_SIMPLE_UNKNOWN_COMMAND("LANGUAGE.json simple command unknown","%tag% &cUnknown command, use &b/uclan help &cto see the list of available commands."),
	JSON_SIMPLE_UNKNOWN_COMMAND_PLAYER("LANGUAGE.json simple command unknown player","%tag% &cUnknown command, use &b/clan help &cto see the list of available commands."),
	JSON_SIMPLE_CLAN_ALLY_RIVAL_LIST_FORMAT("LANGUAGE.json simple clan ally rival list format"," &8%clan_tag% &7- &b%clan_kdr% &7- &b%clan_members_count%"),
	JSON_SIMPLE_CLAN_LISt_FORMAT("LANGUAGE.json simple clan list format"," &a%clan_rank%° &7- &8%clan_tag% &7- &f%clan_desc% &7- &b%clan_kdr% &7- &b%clan_members_count%"),
	JSON_SIMPLE_LIST_NEXT("LANGUAGE.json simple list next"," &bNext page >>"),
	JSON_SIMPLE_LIST_PREV("LANGUAGE.json simple list prev"," << &bPrevious page"),
	JSON_SIMPLE_LIST_CONTROLER("LANGUAGE.json simple list controler"," << &bPrevious page"),
	JSON_SIMPLE_CLAN_DELETED("LANGUAGE.json simple clan deleted"," &a%clan_rank%° &7- &c&mDeleted clan!"), 

	DISABLED_FUNCTION("LANGUAGE.disabled function","%tag% &cThis function/addon appears to be off."), 

	ADMIN_OPENED_CLANCHEST("LANGUAGE.admin opened clanchest","%tag% &cAn admin opened the clan chest."),
	TOP_KDR_FORMAT("LANGUAGE.top kdr format","&b%num%º &7| &a%uclans_tag_color% &7| &fKdr: &b%uclans_clan_kdr%"),
	TOP_KILL_FORMAT("LANGUAGE.top kill format","&b%num%º &7| &a%uclans_tag_color% &7| &fKills: &b%uclans_clan_kills%"),
	TOP_DEATH_FORMAT("LANGUAGE.top death format","&b%num%º &7| &a%uclans_tag_color% &7| &fDeaths: &b%uclans_clan_deaths%"),
	TOP_MEMBER_FORMAT("LANGUAGE.top member format","&b%num%º &7| &a%uclans_tag_color% &7| &fMembers: &b%uclans_count_members%"), 
	TOP_BANK_FORMAT("LANGUAGE.top bank format","&b%num%º &7| &a%uclans_tag_color% &7| &fBank: &b%uclans_bank_balance%"), 
	TOP_LEVEL_FORMAT("LANGUAGE.top level format","&b%num%º &7| &a%uclans_tag_color% &7| &fLV: &b%uclans_level%"), 
	TOP_WAR_FORMAT("LANGUAGE.top war format","&b%num%º &7| &a%uclans_tag_color% &7| &a%uclans_clan_war_win%&7/&4%uclans_clan_war_lose%"), 
	CLAN_NEW_BALANCE("LANGUAGE.clan new balance","%tag% &aThe banks new balance sheet is &a$%uclans_bank_balance%&e, changed by &a%uclans_player%"),
	CLAN_QUEST_CHANGE("LANGUAGE.clan quest change","%tag% &aClan Guest Points is now &b%uclans_quest_points%&e, total finished &b%uclans_quest_finished%"), 
	PLAYER_RESETED_KDR("LANGUAGE.player reseted kdr","%tag% &aThe player &a%player% &ehad the KDR reset!"),
	CLAN_RESETED_KDR("LANGUAGE.clan reseted kdr","%tag% &aThe clan &a%uclans_tag_color% &ehad the KDR reset!"),
	VALUE_GREATER_THAN_ZERO("LANGUAGE.value greater than zero","%tag% &cValue must be greater than zero"), 
	CLAN_LEVEL_CHANGE("LANGUAGE.clan level change","%tag% &aThe &b%clan% &eclan is now at level &b%num%"),
	CLAN_NOT_HAVE_LEVELS("LANGUAGE.clan not have levels","%tag% &cClan does not have levels to remove"), 
	CLAN_HAS_ONLY_LEVELS("LANGUAGE.clan has only levels","%tag% &cThe clan has only &b%num% &clevels"), 
	COMMAND_IN_COOLDOWN("LANGUAGE.command in cooldown","%tag% &cWait for &b%sec% &cto use this command again."), 

	ERROR_LENGTH("LANGUAGE.error length","%tag% &cThe value must have a size between &b%min% &cand &b%max%"), 
	KITS_LIST_HEADER("LANGUAGE.kits list header","&9&lKit List:"), 
	KITS_LIST_EMPTY("LANGUAGE.kits list empty"," &c- No kits to show"), 
	KITS_LIST_FORMAT("LANGUAGE.kits list format"," &a%kit_name% &7- &7%kit_desc% &7- &fDate: &b%kit_creation_date%"), 
	KIT_NOT_EXISTS("LANGUAGE.kit not exists","%tag% &cThere is no kit with this name."), 
	KIT_ALREADY_EXISTS("LANGUAGE.kit already exists","%tag% &cThere is already a kit with this name."), 
	EMPTY_INVENTORY("LANGUAGE.empty inventory","%tag% &cYour inventory cannot be empty."),
	STATE_TRUE("LANGUAGE.state true","&aENABLED"),
	STATE_FALSE("LANGUAGE.state false","&cDISABLED"), 
	ACCEPTED_VALUES("LANGUAGE.accept type","%tag% &cThe type is invalid, use: &b%types%"), 

	CLAN_REGROUP_INVITE_EXPIRED("LANGUAGE.clan regroup invite expired","%tag% &cThe invitation to regroup has expired!"), 
	CLAN_REGROUP_INVITE_DOESNOT_EXIST("LANGUAGE.clan regroup invite doesnot exists","%tag% &cThere is no regroup request sent."), 
	CLAN_REGROUP_INVITE_ALREADY_EXIST("LANGUAGE.clan regroup invite already exists","%tag% &cThere is already a regroup request sent."), 
	CLAN_REGROUP_INVITE_DENY("LANGUAGE.clan regroup invite deny","%tag% &cThe player &a%player% &cdenied your request!"), 
	CLAN_REGROUP_INVITE_ACCEPT("LANGUAGE.clan regroup invite accept","%tag% &cThe player &a%player% &eaccepted your request!"), 
	CLAN_REGROUP_INVITE_ALREADY_DENIED("LANGUAGE.clan regroup invite already denied","%tag% &cYou already denied the request."),
	CLAN_REGROUP_INVITE_ALREADY_ACCEPTED("LANGUAGE.clan regroup invite already accepted","%tag% &cYou already accepted the request."), 
	CLAN_HAS_NO_MEMBERS("LANGUAGE.clan has no members","%tag% &cYour clan has no members."), 
	
	DISABLED_WORLD_REGROUP("LANGUAGE.disabled world regroup","%tag% &cYou cannot send regroup requests in this world."),
	DISABLED_REGION_REGROUP("LANGUAGE.disabled region regroup","%tag% &cYou cannot send regroup requests in this region."), 
	DISABLED_REGION_COMMAND("LANGUAGE.disabled region command","%tag% &cYou cannot use these commands in this region."), 
	
	CLAN_RIVAL_REMOVE_ALREADY_INVITED("LANGUAGE.clan rival remove already invited","%tag% &cThere is already a peace request from your clan or another one in progress to this clan, wait and try again!"),  
	CLAN_RIVAL_REMOVE_ERROR("LANGUAGE.clan rival remove error","%tag% &cThere was an error sending the request!"),  
	CLAN_RIVAL_REMOVE_MODERATION_OFFLINE("LANGUAGE.clan rival remove moderation offline","%tag% &cThere are no moderators or online leaders in the other clan."),
	CLAN_RIVAL_REMOVE_SENDED("LANGUAGE.clan rival remove sended","%tag% &aPeace request sent, wait for the clan to accept or deny."), 
	CLAN_RIVAL_REMOVE_NOT_FOUND("LANGUAGE.clan rival remove not found","%tag% &cThere are no peace requests."),
	CLAN_RIVAL_REMOVE_DENY("LANGUAGE.clan rival remove deny","%tag% &cYou denied the request to remove the rivalry."), 
	CLAN_RIVAL_REMOVE_DENY_RECEIVED("LANGUAGE.clan rival remove deny received","%tag% &cThe other clan denied the request for peace."),
	CLAN_RIVAL_REMOVE_EXPIRED("LANGUAGE.clan rival remove expired","%tag% &cThe invitation to peace has expired!"),
	
	CLAN_ALLY_INVITE_NOT_FOUND("LANGUAGE.clan ally invite not found","%tag% &cThere are no invitations for allies."),
	CLAN_ALLY_INVITE_DENY("LANGUAGE.clan ally invite deny","%tag% &cYou have denied the invitation to the alliance."), 
	CLAN_ALLY_INVITE_ALREADY_INVITED("LANGUAGE.clan ally invite already invited","%tag% &cThere is already an invitation from your clan or another one in progress to this clan, wait and try again!"), 
	CLAN_ALLY_INVITE_ERROR("LANGUAGE.clan ally invite error","%tag% &cThere was an error sending the request!"), 
	CLAN_ALLY_INVITE_MODERATION_OFFLINE("LANGUAGE.clan ally invite moderation offline","%tag% &cThere are no moderators or online leaders in the other clan."), 
	CLAN_ALLY_INVITE_SENDED("LANGUAGE.clan ally invite sended","%tag% &aInvitation sent, wait for the clan to accept or deny."),
	CLAN_ALLY_INVITE_EXPIRED("LANGUAGE.clan ally invite expired","%tag% &cThe invitation to alliance has expired!"), 
	CLAN_ALLY_INVITE_DENY_RECEIVED("LANGUAGE.clan ally invite deny received","%tag% &cThe other clan denied the request for an alliance."), 
	
	CLAN_NOT_HAVE_POINTS("LANGUAGE.clan not have points","%tag% &cClan does not have points to remove"), 
	CLAN_HAS_ONLY_POINTS("LANGUAGE.clan has only points","%tag% &cThe clan has only &b%num% &cpoints"), 
	CLAN_ALLY_IN_LIMIT("LANGUAGE.clan ally in limit","%tag% &cYour clan has reached the allies limit and needs to gain levels to unlock more allies, Your clans current limit is &b&l%uclans_limit_ally%"),
	CLAN_RIVAL_IN_LIMIT("LANGUAGE.clan rival in limit","%tag% &cYour clan has reached the rivalries limit and needs to gain levels to unlock more rivalries, Your clans current limit is &b&l%uclans_limit_rival%"),
	COMMAND_DEPRECATED("LANGUAGE.command deprecated","%tag% &cThis command has been deprecated and can be removed from the settings"), 
	CLAN_DOES_NOT_EXISTS("LANGUAGE.chan does not exists", "%tag% &cThis clan does not exist"),
	NEED_LEVEL_MIN("LANGUAGE.need level min","%tag% &cYour Clan must have at least &b&l%level% &cfor this!"), 
	DISABLED_REGION_CHEST("LANGUAGE.disabled region chest","%tag% &cYou cannot use chests in this region."), 
	PLAYER_LEAVE("LANGUAGE.player_leave","%tag% &cMember &b&l%player% &chas logged out."), 
	PLAYER_JOIN("LANGUAGE.player_join","%tag% &aMember &b&l%player% &ahas just joined."),

	HOME_ALREADY_EXISTS("LANGUAGE.home already exists","%tag% &cThere is already a man with this name."), 
	HOME_CREATE_ERROR("LANGUAGE.home create error","%tag% &cThere was an error creating."), 
	HOME_CREATE_SUCCESS("LANGUAGE.home create success","%tag% &aNew home created successfully!"), 
	HOME_NOT_EXISTS("LANGUAGE.home no exists","%tag% &cThere is no man with that name."), 
	HOME_NOT_EXISTS_GUI("LANGUAGE.home no exists gui","&cThis home has an error."), 
	HOME_DELETE_ERROR("LANGUAGE.home delete error","%tag% &cThere was an error deleting."), 
	HOME_DELETE_ERROR_GUI("LANGUAGE.home delete error gui","&cThere was an error deleting."), 
	HOME_DELETE_SUCCESS("LANGUAGE.home delete success","%tag% &aHome successfully deleted!"), 
	HOME_DELETE_SUCCESS_GUI("LANGUAGE.home delete success gui","&aSuccessfully deleted!"), 
	HOME_NEW_CREATE("LANGUAGE.new create home","%tag% &aA new clan home has been created on the server &b%server% &awith the name &b%name%"), 
	HOME_REMOVED("LANGUAGE.home removed","%tag% &cThe home &b%name% &cof the server &b%server% &cof the clan has been deleted"), 
	DISABLED_WORLD_HOME("LANGUAGE.disabled world command","%tag% &cClan Homes are turned off in this world."),
	DISABLED_REGION_HOME("LANGUAGE.disabled region home","%tag% &cClan Homes are turned off in this region."), 
	HOME_LIMIT("LANGUAGE.home limit","&cThis is the limit (%limit%) for your Clan!"),
	HOME_LIMIT_REACHED("LANGUAGE.home limit reached","%tag% &cThe limit for your clan is %homes% homes."), 
	BANNER_DELETE_ERROR_GUI("LANGUAGE.banner delete error gui","&cError deleting!"), 
	BANNER_DELETE_SUCCESS_GUI("LANGUAGE.banner delete success gui","&bSuccessfully deleted!"), 
	BANNER_DELETE_ERROR("LANGUAGE.banner delete error","%tag% &cAn error occurred when deleting."), 
	BANNER_DELETE_SUCCESS("LANGUAGE.banner delete success","%tag% &aBanner successfully deleted!"), 
	BANNER_EMPTY("LANGUAGE.banner empty","%tag% &cYour Clan has no Banner!"), 
	BANNER_EMPTY_GUI("LANGUAGE.banner empty gui","&cYour Clan has no Banner!"),
	BANNER_EMPTY_ITEM("LANGUAGE.banner empty item","&cThe item must be a banner!"), 
	BANNER_NOT_ITEMSTACK("LANGUAGE.banner not itemstack","&cThe item must be a Banner."), 
	BANNER_NOT_BANNER("LANGUAGE.banner not banner","%tag% &cThe item you are holding must be a banner"), 
	BANNER_HAND_EMPTY("LANGUAGE.banner hand empty","%tag% &cYou need to be holding an item."), 
	BANNER_UPLOAD_ERROR_GUI("LANGUAGE.banner upload error gui","&cError saving banner."), 
	BANNER_UPLOAD_SUCCESS_GUI("LANGUAGE.banner upload success gui","&bNew banner saved!"),  
	NEW_POINT_RECEIVED("LANGUAGE.new point received","%tag% &aYour clan received &b%points% points&a, and now has &b%totalpoints% points"),
	NEW_POINT_REMOVED("LANGUAGE.new point removed","%tag% &cYour clan lost &b%points% points&c, and now has &b%totalpoints% points"),
	NEW_POINT_SET("LANGUAGE.new point set","%tag% &aYour clan points have been changed to &b%totalpoints% points"), 


	

	GUI("GUI", " ", " ", "# TRANSLATIONS OF GUI MENU FILES", " "),
	
	
	General_disband_confirm_title("GUI.General disband_confirm title", "&c&lConfirm deleting the Clan?"),
	General_disband_confirm_items_fill_name("GUI.General disband_confirm items fill name", " "),
	General_disband_confirm_items_fill_lore("GUI.General disband_confirm items fill lore", Arrays.asList()),
	General_disband_confirm_items_confirm_name("GUI.General disband_confirm items confirm name", "&aConfirm"),
	General_disband_confirm_items_confirm_lore("GUI.General disband_confirm items confirm lore", Arrays.asList("", " &cClick to confirm.")),
	General_disband_confirm_items_cancel_name("GUI.General disband_confirm items cancel name", "&aCancel"),
	General_disband_confirm_items_cancel_lore("GUI.General disband_confirm items cancel lore", Arrays.asList("", " &eClick to cancel.")),
	
	General_changeleader_confirm_title("GUI.General changeleader_confirm title", "&c&lCconfirm changing the Clan Leader?"),
	General_changeleader_confirm_items_fill_name("GUI.General changeleader_confirm items fill name", " "),
	General_changeleader_confirm_items_fill_lore("GUI.General changeleader_confirm items fill lore", Arrays.asList()),
	General_changeleader_confirm_items_confirm_name("GUI.General changeleader_confirm items confirm name", "&aConfirm"),
	General_changeleader_confirm_items_confirm_lore("GUI.General changeleader_confirm items confirm lore", Arrays.asList("", " &cClick to confirm.")),
	General_changeleader_confirm_items_cancel_name("GUI.General changeleader_confirm items cancel name", "&aCancel"),
	General_changeleader_confirm_items_cancel_lore("GUI.General changeleader_confirm items cancel lore", Arrays.asList("", " &eClick to cancel.")),
	
	Home_clan_home_title("GUI.Home clan_home title", "&9&lClan Home"),
	Home_clan_home_items_fill_name("GUI.Home clan_home items fill name", " "),
	Home_clan_home_items_fill_lore("GUI.Home clan_home items fill lore", Arrays.asList()),
	Home_clan_home_items_ally_homes_name("GUI.Home clan_home items ally_homes name", "&aView Ally homes"),
	Home_clan_home_items_ally_homes_lore("GUI.Home clan_home items ally_homes lore", Arrays.asList("", " &eClick to open.")),
	Home_clan_home_items_create_name("GUI.Home clan_home items create name", "&aCreate a new Home"),
	Home_clan_home_items_create_lore("GUI.Home clan_home items create lore", Arrays.asList("", " &eClick to create.")),
	Home_clan_home_items_back_name("GUI.Home clan_home items back name", "&cCome back"),
	Home_clan_home_items_back_lore("GUI.Home clan_home items back lore", Arrays.asList("", " &eClick to Come back.")),
	Home_clan_home_items_next_name("GUI.Home clan_home items next name", "&aNext page"),
	Home_clan_home_items_next_lore("GUI.Home clan_home items next lore", Arrays.asList("", " &eClick to proceed.")),
	Home_clan_home_items_previous_name("GUI.Home clan_home items previous name", "&aPrevious page"),
	Home_clan_home_items_previous_lore("GUI.Home clan_home items previous lore", Arrays.asList("", " &eClick to Come back.")),
	Home_clan_home_items_current_name("GUI.Home clan_home items current name", "&aHome %uclans_home:<num>:name%"),
	Home_clan_home_items_current_lore("GUI.Home clan_home items current lore", Arrays.asList("", " &eHome Information", " &7", " &7Server: &a%uclans_home:<num>:server%", " &7Name: &b%uclans_home:<num>:name%", "", " &eLeft-Click to teleport ", " &cRight-Click to delete.")),
	

	Home_clan_delhome_confirm_title("GUI.Home clan_delhome_confirm title", "&c&lConfirm delhome &4&l%home_name% &c?"),
	Home_clan_delhome_confirm_items_fill_name("GUI.Home clan_delhome_confirm items fill name", " "),
	Home_clan_delhome_confirm_items_fill_lore("GUI.Home clan_delhome_confirm items fill lore", Arrays.asList()),
	Home_clan_delhome_confirm_items_confirm_lore("GUI.Home clan_delhome_confirm items confirm lore", Arrays.asList(" ", " &eClick to go confirm.")),
	Home_clan_delhome_confirm_items_cancel_name("GUI.Home clan_delhome_confirm items cancel name", "&aClick to cancel"),
	Home_clan_delhome_confirm_items_cancel_lore("GUI.Home clan_delhome_confirm items cancel lore", Arrays.asList(" ", " &eClick to go cancel.")),
	
	General_noclan_home_title("GUI.General noclan_home title", "&9&lClan &7| &cWithout Clan"),
	General_noclan_home_items_fill_name("GUI.General noclan_home items fill name", " "),
	General_noclan_home_items_fill_lore("GUI.General noclan_home items fill lore", Arrays.asList()),
	General_noclan_home_items_fill2_name("GUI.General noclan_home items fill2 name", " "),
	General_noclan_home_items_fill2_lore("GUI.General noclan_home items fill2 lore", Arrays.asList()),
	General_noclan_home_items_commands_name("GUI.General noclan_home items commands name", "&aCommand List and Help"),
	General_noclan_home_items_commands_lore("GUI.General noclan_home items commands lore", Arrays.asList(" &eClick to see the complete list", "&eof commands for Clans and Land.")),
	General_noclan_home_items_clans_name("GUI.General noclan_home items clans name", "&aAll Clans"),
	General_noclan_home_items_clans_lore("GUI.General noclan_home items clans lore", Arrays.asList(" &eClick to open the clan list menu.")),
	General_noclan_home_items_create_name("GUI.General noclan_home items create name", "&cYou dont have a Clan"),
	General_noclan_home_items_create_lore("GUI.General noclan_home items create lore", Arrays.asList(" &eClick to create a Clan.")),
	
	General_clan_home_title("GUI.General clan_home title", "&9&lClan Menu"),
	General_clan_home_items_fill_name("GUI.General clan_home items fill name", " "),
	General_clan_home_items_fill_lore("GUI.General clan_home items fill lore", Arrays.asList()),
	General_clan_home_items_fill2_name("GUI.General clan_home items fill2 name", " "),
	General_clan_home_items_fill2_lore("GUI.General clan_home items fill2 lore", Arrays.asList()),
	
	General_clan_home_items_info_name("GUI.General clan_home items info name", "&aClan %uclans_tag_color%"),
	General_clan_home_items_info_lore("GUI.General clan_home items info lore", Arrays.asList(" &eClan Information", " &7", " &7Clan Level: &a%uclans_level%"," &7Clan Points: &a%uclans_points%", " &7Bank: &a$%uclans_bank_balance%", " &7", " &7Tag: &b%uclans_tag_color%", " &7Desc: &b%uclans_desc_color%", " ", " &eClick to open a status list.")),
	General_clan_home_items_banner_name("GUI.General clan_home items banner name", "&aClan Banner"),
	General_clan_home_items_banner_lore("GUI.General clan_home items banner lore", Arrays.asList(" ", " &eBanner Information:", "", " &fHas Banner: &b%uclans_hasbanner_formated%"," "," &eThe clan banner is your brand", "&eand your &b&lNEXUS &eused for land marking!", " &eOnly the Leader or Moderators can","&eedit the clan banner" )),
	General_clan_home_items_clans_name("GUI.General clan_home items clans name", "&aAll Clans"),
	General_clan_home_items_clans_lore("GUI.General clan_home items clans lore", Arrays.asList(" &eClick to open the clan list menu.")),
	General_clan_home_items_commands_name("GUI.General clan_home items commands name", "&aCommand List and Help"),
	General_clan_home_items_commands_lore("GUI.General clan_home items commands lore", Arrays.asList(" &eClick to see the complete list", "&eof commands for Clans and Land.")),
	General_clan_home_items_settings_name("GUI.General clan_home items settings name", "&aClan Settings"),
	General_clan_home_items_settings_lore("GUI.General clan_home items settings lore", Arrays.asList(" &eClick to open.")),
	General_clan_home_items_home_name("GUI.General clan_home items home name", "&aOpen home menu."),
	General_clan_home_items_home_lore("GUI.General clan_home items home lore", Arrays.asList(" &eClick to open.")),
	General_clan_home_items_ally_name("GUI.General clan_home items ally name", "&aAlliances"),
	General_clan_home_items_ally_lore("GUI.General clan_home items ally lore", Arrays.asList(" ", " &7Allies: &b%uclans_clan_count_ally%", " "," &eClick to open the alliances menu.")),
	General_clan_home_items_rival_name("GUI.General clan_home items rival name", "&aRivalries"),
	General_clan_home_items_rival_lore("GUI.General clan_home items rival lore", Arrays.asList(" ", " &7Rivals: &b%uclans_clan_count_rival%", " " ," &eClick to open the rivalries menu.")),
	General_clan_home_items_members_name("GUI.General clan_home items members name", "&aClan Members"),
	General_clan_home_items_members_lore("GUI.General clan_home items members lore", Arrays.asList(" "," &7Members: &b%uclans_count_members%", " ", " &eClick to open the members menu.")),

	General_player_profile_title("GUI.General player_profile title", "&9&lProfile &7| &a%uclans_player%"),
	General_player_profile_items_head_name("GUI.General player_profile items head name", "&a%uclans_player%"),
	General_player_profile_items_head_lore("GUI.General player_profile items head lore", Arrays.asList("", " &7Clan: &b%uclans_tag_color%", " &7Leader: &b%uclans_leader%", " ", " &7Nickname: &b%uclans_player%", " &7Kdr: &b%uclans_player_kills%&8/&b%uclans_player_deaths% &8(%uclans_player_kdr%)", " &7Entry into: &b%uclans_player_joindate_formated%", " &7Last Seen: &b%uclans_player_lastsee_formated%" )),
	General_player_profile_items_back_name("GUI.General player_profile items back name", "&cBack home"),
	General_player_profile_items_back_lore("GUI.General player_profile items back lore", Arrays.asList(" &eClick to return to home" )),
	General_player_profile_items_fill_name("GUI.General player_profile items fill name", " "),
	General_player_profile_items_fill_lore("GUI.General player_profile items fill lore", Arrays.asList()),
	
	General_clan_stats_title("GUI.General clan_stats title", "&9&lStats &7| %uclans_tag_color%"),
	General_clan_stats_items_fill_name("GUI.General clan_stats items fill name", " "),
	General_clan_stats_items_fill_lore("GUI.General clan_stats items fill lore", Arrays.asList()),
	General_clan_stats_items_back_name("GUI.General clan_stats items back name", "&cCome back"),
	General_clan_stats_items_back_lore("GUI.General clan_stats items back lore", Arrays.asList(" &eClick to go back" )),
	General_clan_stats_items_limits_name("GUI.General clan_stats items limits name", "&aClan Limits:"),
	General_clan_stats_items_limits_lore("GUI.General clan_stats items limits lore", Arrays.asList(" ", "&eAbout Limits:", " ", " &7Homes: &b%uclans_limit_home%", " &7Allies: &b%uclans_limit_ally%", " &7Rivals: &b%uclans_limit_rival%", " &7Slots: &b%uclans_slots_total%", " ", " &eThe limits are increased as", "&ethe clan gains levels.")),
	General_clan_stats_items_member_rival_ally_name("GUI.General clan_stats items member_rival_ally name", "&aMembers, Rivals and Allies:"),
	General_clan_stats_items_member_rival_ally_lore("GUI.General clan_stats items member_rival_ally lore", Arrays.asList(" ", "&eAbout Members, rivals and allies:", " ", " &7Members: &b%uclans_count_members%", " &7Online Members: &b%uclans_count_onlinemembers%", " &7Allies: &b%uclans_clan_count_ally%", " &7Rivals: &b%uclans_clan_count_rival%")),
	General_clan_stats_items_others_name("GUI.General clan_stats items others name", "&aOthers stats:"),
	General_clan_stats_items_others_lore("GUI.General clan_stats items others lore", Arrays.asList(" ", "&eOthers:", " ", " &7Members Joined: &b%uclans_clan_member_joined%", " &7Members Left: &b%uclans_clan_member_leave%", " &7Members Kicked: &b%uclans_clan_member_kicked%", " &7Tag changes: &b%uclans_clan_tag_changed%")),
	General_clan_stats_items_status_name("GUI.General clan_stats items status name", "&aStatus:"),
	General_clan_stats_items_status_lore("GUI.General clan_stats items status lore", Arrays.asList(" ", "&eAbout the Status:", " "," &7Bank: &a$%uclans_bank_balance%", " &7Level: &b%uclans_level%", " &7Max Level reached: &b%uclans_max_level_reached%", " &7Clan Points: &b%uclans_points%", " &7Quests Finished: &b%uclans_quest_finished%")),
	General_clan_stats_items_war_name("GUI.General clan_stats items war name", "&aWar stats:"),
	General_clan_stats_items_war_lore("GUI.General clan_stats items war lore", Arrays.asList(" ", "&eAbout wars:", " ", " &7War Win: &b%uclans_clan_war_win%", " &7War Lose: &b%uclans_clan_war_lose%", " &7War total: &b%uclans_clan_war_total%")),
	General_clan_stats_items_kdr_name("GUI.General clan_stats items kdr name", "&aKDR:"),
	General_clan_stats_items_kdr_lore("GUI.General clan_stats items kdr lore", Arrays.asList(" ", "&eAbout the kdr:", " ", " &7Kills: &b%uclans_clan_kills%", " &7Deaths: &b%uclans_clan_deaths%", " &7Kdr Total: &b%uclans_clan_kdr%")),
	General_clan_stats_items_banner_name("GUI.General clan_stats items banner name", "&aClan Banner"),
	General_clan_stats_items_banner_lore("GUI.General clan_stats items banner lore", Arrays.asList(" ", " &eBanner Information:", "", " &fHas Banner: &b%uclans_hasbanner_formated%" )),
	General_clan_stats_items_foundation_name("GUI.General clan_stats items foundation name", "&aFoundation:"),
	General_clan_stats_items_foundation_lore("GUI.General clan_stats items foundation lore", Arrays.asList(" ", "&eAbout the foundation:", " ", " &7Leader: &b%uclans_leader%", " &7Creation date: &b%uclans_creation_date_formated%", " &7Is Verified: &f%uclans_verified%", " &7Slots: &f%uclans_slots% &8(+%uclans_slots_extra%)", " ", " &7Moderators (%uclans_count_moderators%):", "  &a%uclans_moderators%" )),
	
	General_clan_settings_title("GUI.General clan_settings title", "&9&lSettings Menu"),
	General_clan_settings_items_fill_name("GUI.General clan_settings items fill name", " "),
	General_clan_settings_items_fill_lore("GUI.General clan_settings items fill lore", Arrays.asList()),
	General_clan_settings_items_back_name("GUI.General clan_settings items back name", "&cCome back"),
	General_clan_settings_items_back_lore("GUI.General clan_settings items back lore", Arrays.asList(" &eClick to go back" )),
	General_clan_settings_items_actions_name("GUI.General clan_settings items actions name", "&aActions"),
	General_clan_settings_items_actions_lore("GUI.General clan_settings items actions lore", Arrays.asList(" &eClick to open.")),
	General_clan_settings_items_delete_name("GUI.General clan_settings items delete name", "&c&lDelete the clan"),
	General_clan_settings_items_delete_lore("GUI.General clan_settings items delete lore", Arrays.asList(" &eClick to delete the clan", " &cOnly the Leader can do this!", " &cThis will remove the protection from your land", " &cThis requires confirmation in CHAT!", " ", " &cCaution, this action cannot be undone!" )),
	General_clan_settings_items_make_banner_name("GUI.General clan_settings items make_banner name", "&aCreate or Edit the Banner"),
	General_clan_settings_items_make_banner_lore("GUI.General clan_settings items make_banner lore", Arrays.asList(" ", " &eClick to Open.")),
	General_clan_settings_items_join_leave_name("GUI.General clan_settings items join_leave name", "&aJoin and Leave"),
	General_clan_settings_items_join_leave_lore("GUI.General clan_settings items join_leave lore", Arrays.asList(" ", " &fState: %uclans_settings_state:JOINLEAVE%", ""," &eClick to toggle ", " ", " &cWhen disabled, your clan does not", "&cwill see more messages when", "&centering or leaving.")),
	General_clan_settings_items_ff_name("GUI.General clan_settings items ff name", "&aFire friend"),
	General_clan_settings_items_ff_lore("GUI.General clan_settings items ff lore", Arrays.asList(" ", " &fState: %uclans_settings_state:CLANFF%", ""," &eClick to toggle ", " ", " &cWhen activated, members can", "&cattack each other.")),
	General_clan_settings_items_allysharedhome_name("GUI.General clan_settings items allysharedhome name", "&aAllied shared Home"),
	General_clan_settings_items_allysharedhome_lore("GUI.General clan_settings items allysharedhome lore", Arrays.asList(" ", " &fState: %uclans_settings_state:ALLYSHAREDHOME%", ""," &eClick to toggle ", " ", " &cWhen disabled, your clan's homes will", "&cnot appear in the allied home list.")),
	General_clan_settings_items_allysharedchat_name("GUI.General clan_settings items allysharedchat name", "&aAllied shared chat"),
	General_clan_settings_items_allysharedchat_lore("GUI.General clan_settings items allysharedchat lore", Arrays.asList(" ", " &fState: %uclans_settings_state:ALLYSHAREDCHAT%", ""," &eClick to toggle ", " ", " &cWhen disabled, your clan does not", "&creceive or send messages from allies.")),
	General_clan_settings_items_warinvite_name("GUI.General clan_settings items warinvite name", "&aWar Invitations"),
	General_clan_settings_items_warinvite_lore("GUI.General clan_settings items warinvite lore", Arrays.asList(" ", " &fState: %uclans_settings_state:WARINVITE%", ""," &eClick to toggle ", " ", " &cWhen disabled, your clan", "&cdoes not receive challenges" )),

	
	General_clan_actions_title("GUI.General clan_actions title", "&9&lActions Menu"),
	General_clan_actions_items_fill_name("GUI.General clan_actions items fill name", " "),
	General_clan_actions_items_fill_lore("GUI.General clan_actions items fill lore", Arrays.asList()),
	General_clan_actions_items_back_name("GUI.General clan_actions items back name", "&cCome back"),
	General_clan_actions_items_back_lore("GUI.General clan_actions items back lore", Arrays.asList(" &eClick to go back" )),
	General_clan_actions_items_sethome_name("GUI.General clan_actions items sethome name", "&aSet the Clan Home"),
	General_clan_actions_items_sethome_lore("GUI.General clan_actions items sethome lore", Arrays.asList(" &eClick to set the Clan Home" )),
	General_clan_actions_items_name_name("GUI.General clan_actions items name name", "&aChanging the Clan Name"),
	General_clan_actions_items_name_lore("GUI.General clan_actions items name lore", Arrays.asList(" &eClick to change the Clan name.")),
	General_clan_actions_items_desc_name("GUI.General clan_actions items desc name", "&aChanging the Clan Description"),
	General_clan_actions_items_desc_lore("GUI.General clan_actions items desc lore", Arrays.asList(" &eClick to change the Clan description.")),
	General_clan_actions_items_modtag_name("GUI.General clan_actions items modtag name", "&aChange the clan Tag"),
	General_clan_actions_items_modtag_lore("GUI.General clan_actions items modtag lore", Arrays.asList(" &eClick to change the Clan tag" )),
	
	General_clan_top_title("GUI.General clan_top title", "&9&lList of Clans &7| %current%"),
	General_clan_top_items_fill_name("GUI.General clan_top items fill name", " "),
	General_clan_top_items_fill_lore("GUI.General clan_top items fill lore", Arrays.asList()),
	General_clan_top_items_active_name("GUI.General clan_top items active name", " &aCurrent"),
	General_clan_top_items_active_lore("GUI.General clan_top items active lore", Arrays.asList()),
	General_clan_top_items_kdr_name("GUI.General clan_top items kdr name", "&cTop KDR"),
	General_clan_top_items_kdr_lore("GUI.General clan_top items kdr lore", Arrays.asList(" &eClick to order", "&elist by KDR ", " ")),
	General_clan_top_items_kill_name("GUI.General clan_top items kill name", "&cTop KILL"),
	General_clan_top_items_kill_lore("GUI.General clan_top items kill lore", Arrays.asList(" &eClick to order", "&elist by KILL ", " ")),
	General_clan_top_items_death_name("GUI.General clan_top items death name", "&cTop DEATH"),
	General_clan_top_items_death_lore("GUI.General clan_top items death lore", Arrays.asList(" &eClick to order", "&elist by DEATH ", " ")),
	General_clan_top_items_bank_name("GUI.General clan_top items bank name", "&cTop BANK"),
	General_clan_top_items_bank_lore("GUI.General clan_top items bank lore", Arrays.asList(" &eClick to order", "&elist by BANK ", " ")),
	General_clan_top_items_member_name("GUI.General clan_top items member name", "&cTop MEMBER"),
	General_clan_top_items_member_lore("GUI.General clan_top items member lore", Arrays.asList(" &eClick to order", "&elist by MEMBER ", " ")),
	General_clan_top_items_level_name("GUI.General clan_top items level name", "&cTop Level"),
	General_clan_top_items_level_lore("GUI.General clan_top items level lore", Arrays.asList(" &eClick to order", "&elist by level ", " ")),
	General_clan_top_items_current_all_name("GUI.General clan_top items current_all name", "&aClan %uclans_tag_color%"),
	General_clan_top_items_current_all_lore("GUI.General clan_top items current_all lore", Arrays.asList("", " &eClan Information", " &7", " &7Creation date: &a%uclans_creation_date_formated%", " &7", " &7Tag: &b%uclans_tag_color%", " &7Leader: &b%uclans_leader%", " &7Members: &b%uclans_count_members%", "", " &eRight-Click to view info.")),
	General_clan_top_items_current_war_name("GUI.General clan_top items current_war name", "&aClan %uclans_tag_color%"),
	General_clan_top_items_current_war_lore("GUI.General clan_top items current_war lore", Arrays.asList("", " &eClan Information", " &7", " &7Wars won: &a%uclans_clan_war_win%", " &7", " &7Tag: &b%uclans_tag_color%", " &7Leader: &b%uclans_leader%", " &7Members: &b%uclans_count_members%", "", " &eRight-Click to view info.")),
	General_clan_top_items_current_bank_name("GUI.General clan_top items current_bank name", "&aClan %uclans_tag_color%"),
	General_clan_top_items_current_bank_lore("GUI.General clan_top items current_bank lore", Arrays.asList("", " &eClan Information", " &7", " &7Bank: &a$%uclans_bank_balance%", " &7", " &7Tag: &b%uclans_tag_color%", " &7Leader: &b%uclans_leader%", " &7Members: &b%uclans_count_members%", "", " &eRight-Click to view info.")),
	General_clan_top_items_current_member_name("GUI.General clan_top items current_member name", "&aClan %uclans_tag_color%"),
	General_clan_top_items_current_member_lore("GUI.General clan_top items current_member lore", Arrays.asList("", " &eClan Information", " &7", " &7Members: &a%uclans_count_members%", " &7", " &7Tag: &b%uclans_tag_color%", " &7Leader: &b%uclans_leader%", " &7Members: &b%uclans_count_members%", "", " &eRight-Click to view info.")),
	General_clan_top_items_current_death_name("GUI.General clan_top items current_death name", "&aClan %uclans_tag_color%"),
	General_clan_top_items_current_death_lore("GUI.General clan_top items current_death lore", Arrays.asList("", " &eClan Information", " &7", " &7Deaths: &a%uclans_clan_deaths%", " &7", " &7Tag: &b%uclans_tag_color%", " &7Leader: &b%uclans_leader%", " &7Members: &b%uclans_count_members%", "", " &eRight-Click to view info.")),
	General_clan_top_items_current_kill_name("GUI.General clan_top items current_kill name", "&aClan %uclans_tag_color%"),
	General_clan_top_items_current_kill_lore("GUI.General clan_top items current_kill lore", Arrays.asList("", " &eClan Information", " &7", " &7Kills: &a%uclans_clan_kills%", " &7", " &7Tag: &b%uclans_tag_color%", " &7Leader: &b%uclans_leader%", " &7Members: &b%uclans_count_members%", "", " &eRight-Click to view info.")),
	General_clan_top_items_current_kdr_name("GUI.General clan_top items current_kdr name", "&aClan %uclans_tag_color%"),
	General_clan_top_items_current_kdr_lore("GUI.General clan_top items current_kdr lore", Arrays.asList("", " &eClan Information", " &7", " &7KDR: &a%uclans_clan_kdr%", " &7", " &7Tag: &b%uclans_tag_color%", " &7Leader: &b%uclans_leader%", " &7Members: &b%uclans_count_members%", "", " &eRight-Click to view info.")),
	General_clan_top_items_current_level_name("GUI.General clan_top items current_level name", "&aClan %uclans_tag_color%"),
	General_clan_top_items_current_level_lore("GUI.General clan_top items current_level lore", Arrays.asList("", " &eClan Information", " &7", " &7Level: &a%uclans_level%", " &7", " &7Tag: &b%uclans_tag_color%", " &7Leader: &b%uclans_leader%", " &7Members: &b%uclans_count_members%", "", " &eRight-Click to view info.")),
	General_clan_top_items_current_name("GUI.General clan_top items current name", "&aClan %uclans_tag_color%"),
	General_clan_top_items_current_lore("GUI.General clan_top items current lore", Arrays.asList("", " &eClan Information", " &7", " &7Level: &a%uclans_level%", " &7", " &7Tag: &b%uclans_tag_color%", " &7Leader: &b%uclans_leader%", " &7Members: &b%uclans_count_members%", "", " &eRight-Click to view info.")),
	General_clan_top_items_war_name("GUI.General clan_top items war name", "&cTop War"),
	General_clan_top_items_war_lore("GUI.General clan_top items war lore", Arrays.asList(" &eClick to order", "&elist by Top War ", " ")),
	General_clan_top_items_all_name("GUI.General clan_top items all name", "&cAll Verified"),
	General_clan_top_items_all_lore("GUI.General clan_top items all lore", Arrays.asList(" &eClick to order", "&elist by all Clans ", " ")),
	General_clan_top_items_next_name("GUI.General clan_top items next name", "&aNext"),
	General_clan_top_items_next_lore("GUI.General clan_top items next lore", Arrays.asList(" &eClick to next" )),
	General_clan_top_items_previous_name("GUI.General clan_top items previous name", "&aPrevious"),
	General_clan_top_items_previous_lore("GUI.General clan_top items previous lore", Arrays.asList(" &eClick to previous" )),
	General_clan_top_items_back_name("GUI.General clan_top items back name", "&cCome back"),
	General_clan_top_items_back_lore("GUI.General clan_top items back lore", Arrays.asList(" &eClick to go back" )),

	General_clan_members_title("GUI.General clan_members title", "&9&lMembers Menu"),
	General_clan_members_items_fill_name("GUI.General clan_members items fill name", " "),
	General_clan_members_items_fill_lore("GUI.General clan_members items fill lore", Arrays.asList()),
	General_clan_members_items_fill2_name("GUI.General clan_members items fill2 name", " "),
	General_clan_members_items_fill2_lore("GUI.General clan_members items fill2 lore", Arrays.asList()),
	General_clan_members_items_back_name("GUI.General clan_members items back name", "&cCome back"),
	General_clan_members_items_back_lore("GUI.General clan_members items back lore", Arrays.asList(" &eClick to go back" )),
	General_clan_members_items_invite_name("GUI.General clan_members items invite name", "&aInvite players"),
	General_clan_members_items_invite_lore("GUI.General clan_members items invite lore", Arrays.asList(" &eClick to invite new members" )),
	General_clan_members_items_list_name("GUI.General clan_members items list name", "&aMember List"),
	General_clan_members_items_list_lore("GUI.General clan_members items list lore", Arrays.asList(" "," &7Members: &b%uclans_count_members%", " ", " &eClick to view the list of members" )),
	
	General_clan_ally_title("GUI.General clan_ally title", "&9&lAlliances Menu"),
	General_clan_ally_items_fill_name("GUI.General clan_ally items fill name", " "),
	General_clan_ally_items_fill_lore("GUI.General clan_ally items fill lore", Arrays.asList()),
	General_clan_ally_items_fill2_name("GUI.General clan_ally items fill2 name", " "),
	General_clan_ally_items_fill2_lore("GUI.General clan_ally items fill2 lore", Arrays.asList()),
	General_clan_ally_items_back_name("GUI.General clan_ally items back name", "&cCome back"),
	General_clan_ally_items_back_lore("GUI.General clan_ally items back lore", Arrays.asList(" &eClick to go back" )),
	General_clan_ally_items_invite_name("GUI.General clan_ally items invite name", "&aAdd or Remove Alliances"),
	General_clan_ally_items_invite_lore("GUI.General clan_ally items invite lore", Arrays.asList(" &eClick to add or remove alliances" )),
	General_clan_ally_items_list_name("GUI.General clan_ally items list name", "&aAlliances List"),
	General_clan_ally_items_list_lore("GUI.General clan_ally items list lore", Arrays.asList(" ", " &7Allies: &b%uclans_clan_count_ally%", " " ," &eClick to view the list of alliances" )),
	
	General_clan_rival_title("GUI.General clan_rival title", "&9&lRivalries Menu"),
	General_clan_rival_items_fill_name("GUI.General clan_rival items fill name", " "),
	General_clan_rival_items_fill_lore("GUI.General clan_rival items fill lore", Arrays.asList()),
	General_clan_rival_items_fill2_name("GUI.General clan_rival items fill2 name", " "),
	General_clan_rival_items_fill2_lore("GUI.General clan_rival items fill2 lore", Arrays.asList()),
	General_clan_rival_items_back_name("GUI.General clan_rival items back name", "&cCome back"),
	General_clan_rival_items_back_lore("GUI.General clan_rival items back lore", Arrays.asList(" &eClick to go back" )),
	General_clan_rival_items_invite_name("GUI.General clan_rival items invite name", "&aAdd or Remove Rivalries"),
	General_clan_rival_items_invite_lore("GUI.General clan_rival items invite lore", Arrays.asList(" &eClick to add or remove rivalries" )),
	General_clan_rival_items_list_name("GUI.General clan_rival items list name", "&aRivalries List"),
	General_clan_rival_items_list_lore("GUI.General clan_rival items list lore", Arrays.asList(" ", " &7Rivals: &b%uclans_clan_count_rival%", " " ," &eClick to view the list of rivalries" )),

	Pagination_rival_title("GUI.Pagination rival title", "&9&lRival List."),
	Pagination_rival_items_fill_name("GUI.Pagination rival items fill name", " "),
	Pagination_rival_items_fill_lore("GUI.Pagination rival items fill lore", Arrays.asList()),
	Pagination_rival_items_back_name("GUI.Pagination rival items back name", "&cCome back"),
	Pagination_rival_items_back_lore("GUI.Pagination rival items back lore", Arrays.asList("", " &eClick to Come back.")),
	Pagination_rival_items_next_name("GUI.Pagination rival items next name", "&aNext page"),
	Pagination_rival_items_next_lore("GUI.Pagination rival items next lore", Arrays.asList("", " &eClick to proceed.")),
	Pagination_rival_items_previous_name("GUI.Pagination rival items previous name", "&aPrevious page"),
	Pagination_rival_items_previous_lore("GUI.Pagination rival items previous lore", Arrays.asList("", " &eClick to Come back.")),
	Pagination_rival_items_current_name("GUI.Pagination rival items current name", "&aClan %uclans_tag_color%"),
	Pagination_rival_items_current_lore("GUI.Pagination rival items current lore", Arrays.asList("", " &eClan Information", " &7", " &7Level: &a%uclans_level%", " &7", " &7Tag: &b%uclans_tag_color%", " &7Leader: &b%uclans_leader%", " &7Members: &b%uclans_count_members%", "", " &eRight-Click to view info.")),
	
	Pagination_ally_title("GUI.Pagination ally title", "&9&lAlly List."),
	Pagination_ally_items_fill_name("GUI.Pagination ally items fill name", " "),
	Pagination_ally_items_fill_lore("GUI.Pagination ally items fill lore", Arrays.asList()),
	Pagination_ally_items_back_name("GUI.Pagination ally items back name", "&cCome back"),
	Pagination_ally_items_back_lore("GUI.Pagination ally items back lore", Arrays.asList("", " &eClick to Come back.")),
	Pagination_ally_items_next_name("GUI.Pagination ally items next name", "&aNext page"),
	Pagination_ally_items_next_lore("GUI.Pagination ally items next lore", Arrays.asList("", " &eClick to proceed.")),
	Pagination_ally_items_previous_name("GUI.Pagination ally items previous name", "&aPrevious page"),
	Pagination_ally_items_previous_lore("GUI.Pagination ally items previous lore", Arrays.asList("", " &eClick to Come back.")),
	Pagination_ally_items_current_name("GUI.Pagination ally items current name", "&aClan %uclans_tag_color%"),
	Pagination_ally_items_current_lore("GUI.Pagination ally items current lore", Arrays.asList("", " &eClan Information", " &7", " &7Level: &a%uclans_level%", " &7", " &7Tag: &b%uclans_tag_color%", " &7Leader: &b%uclans_leader%", " &7Members: &b%uclans_count_members%", "", " &eRight-Click to view info.")),
	
	Pagination_members_title("GUI.Pagination members title", "&9&lMember List."),
	Pagination_members_items_fill_name("GUI.Pagination members items fill name", " "),
	Pagination_members_items_fill_lore("GUI.Pagination members items fill lore", Arrays.asList()),
	Pagination_members_items_back_name("GUI.Pagination members items back name", "&cCome back"),
	Pagination_members_items_back_lore("GUI.Pagination members items back lore", Arrays.asList("", " &eClick to Come back.")),
	Pagination_members_items_next_name("GUI.Pagination members items next name", "&aNext page"),
	Pagination_members_items_next_lore("GUI.Pagination members items next lore", Arrays.asList("", " &eClick to proceed.")),
	Pagination_members_items_previous_name("GUI.Pagination members items previous name", "&aPrevious page"),
	Pagination_members_items_previous_lore("GUI.Pagination members items previous lore", Arrays.asList("", " &eClick to Come back.")),
	Pagination_members_items_current_name("GUI.Pagination members items current name", "&a%uclans_player%"),
	Pagination_members_items_current_lore("GUI.Pagination members items current lore", Arrays.asList("", " &7Leader: &b%uclans_player_leader_yes_no%", " &7Moderators: &b%uclans_player_mod_yes_no%", " &7Nickname: &b%uclans_player%", " &7Kdr: &b%uclans_player_kills%&8/&b%uclans_player_deaths% &8(%uclans_player_kdr%)", " &7Entry into: &b%uclans_player_joindate_formated%", " &7Last Seen: &b%uclans_player_lastsee_formated%", " ", " &eClick to view profile.")),
	
	Pagination_clans_title("GUI.Pagination clans title", "&9&lVerified clans."),
	Pagination_clans_items_fill_name("GUI.Pagination clans items fill name", " "),
	Pagination_clans_items_fill_lore("GUI.Pagination clans items fill lore", Arrays.asList()),
	Pagination_clans_items_back_name("GUI.Pagination clans items back name", "&cCome back"),
	Pagination_clans_items_back_lore("GUI.Pagination clans items back lore", Arrays.asList("", " &eClick to Come back.")),
	Pagination_clans_items_next_name("GUI.Pagination clans items next name", "&aNext page"),
	Pagination_clans_items_next_lore("GUI.Pagination clans items next lore", Arrays.asList("", " &eClick to proceed.")),
	Pagination_clans_items_previous_name("GUI.Pagination clans items previous name", "&aPrevious page"),
	Pagination_clans_items_previous_lore("GUI.Pagination clans items previous lore", Arrays.asList("", " &eClick to Come back.")),
	Pagination_clans_items_current_name("GUI.Pagination clans items current name", "&aClan %uclans_tag_color%"),
	Pagination_clans_items_current_lore("GUI.Pagination clans items current lore", Arrays.asList("", " &eClan Information", " &7", " &7Level: &a%uclans_level%", " &7", " &7Tag: &b%uclans_tag_color%", " &7Leader: &b%uclans_leader%", " &7Members: &b%uclans_count_members%", "", " &eRight-Click to view info.")),

	Home_clan_allyhome_title("GUI.Home clan_allyhome title", "&9&lAllied Houses"),
	Home_clan_allyhome_items_back_name("GUI.Home clan_allyhome items back name", "&cCome back"),
	Home_clan_allyhome_items_back_lore("GUI.Home clan_allyhome items back lore", Arrays.asList("", " &eClick to Come back.")),
	Home_clan_allyhome_items_next_name("GUI.Home clan_allyhome items next name", "&aNext page"),
	Home_clan_allyhome_items_next_lore("GUI.Home clan_allyhome items next lore", Arrays.asList("", " &eClick to proceed.")),
	Home_clan_allyhome_items_previous_name("GUI.Home clan_allyhome items previous name", "&aPrevious page"),
	Home_clan_allyhome_items_previous_lore("GUI.Home clan_allyhome items previous lore", Arrays.asList("", " &eClick to Come back.")),
	Home_clan_allyhome_items_current_name("GUI.Home clan_allyhome items current name", "&aHome %uclans_home:<num>:name% of clan %uclans_tag_color%."),
	Home_clan_allyhome_items_current_lore("GUI.Home clan_allyhome items current lore", Arrays.asList("", " &eHome Information", " &7", " &7Clan: &b%uclans_tag_color%", " &7Server: &a%uclans_home:<num>:server%", " &7Name: &b%uclans_home:<num>:name%", "", " &eLeft-Click to teleport.")),
	Home_clan_allyhome_items_fill_name("GUI.Home clan_allyhome items fill name", " "),
	Home_clan_allyhome_items_fill_lore("GUI.Home clan_allyhome items fill lore", Arrays.asList()),
	
	Banner_banner_home_title("GUI.Banner banner_home title", "&9&lBanner menu"),
	Banner_banner_home_items_fill_name("GUI.Banner banner_home items fill name", " "),
	Banner_banner_home_items_fill_lore("GUI.Banner banner_home items fill lore", Arrays.asList()),
	Banner_banner_home_items_fill2_name("GUI.Banner banner_home items fill2 name", " "),
	Banner_banner_home_items_fill2_lore("GUI.Banner banner_home items fill2 lore", Arrays.asList()),
	Banner_banner_home_items_current_name("GUI.Banner banner_home items current name", "&aCurrent Banner"),
	Banner_banner_home_items_current_lore("GUI.Banner banner_home items current lore", Arrays.asList(" "," &eThe clan banner is your brand","&eand your &b&lNEXUS &eused for land marking!","", " &b&l<< &cUse the buttons on the sides &b&l>>" )),
	Banner_banner_home_items_upload_name("GUI.Banner banner_home items upload name", "&aUpload"),
	Banner_banner_home_items_upload_lore("GUI.Banner banner_home items upload lore", Arrays.asList("", " &eClick to open upload menu.")),
	Banner_banner_home_items_delete_name("GUI.Banner banner_home items delete name", "&aDelete a Banner"),
	Banner_banner_home_items_delete_lore("GUI.Banner banner_home items delete lore", Arrays.asList("", " &eClick to delete the current banner.")),
	Banner_banner_home_items_pre_name("GUI.Banner banner_home items pre name", "&aPre created banners."),
	Banner_banner_home_items_pre_lore("GUI.Banner banner_home items pre lore", Arrays.asList("", " &eClick to open list.")),
	Banner_banner_home_items_back_name("GUI.Banner banner_home items back name", "&cCome back"),
	Banner_banner_home_items_back_lore("GUI.Banner banner_home items back lore", Arrays.asList("", " &eClick to Come back.")),
	
	Banner_banner_delete_title("GUI.Banner banner_delete title", "&cConfirm delete current banner?"),
	Banner_banner_delete_items_fill_name("GUI.Banner banner_delete items fill name", " "),
	Banner_banner_delete_items_fill_lore("GUI.Banner banner_delete items fill lore", Arrays.asList()),
	Banner_banner_delete_items_confirm_name("GUI.Banner banner_delete items confirm name", "&aConfirm"),
	Banner_banner_delete_items_confirm_lore("GUI.Banner banner_delete items confirm lore", Arrays.asList("", " &cClick to confirm.")),
	Banner_banner_delete_items_cancel_name("GUI.Banner banner_delete items cancel name", "&aCancel"),
	Banner_banner_delete_items_cancel_lore("GUI.Banner banner_delete items cancel lore", Arrays.asList("", " &eClick to cancel.")),
	
	Banner_banner_upload_title("GUI.Banner banner_upload title", "&9&lBanner Upload"),
	Banner_banner_upload_items_fill_name("GUI.Banner banner_upload items fill name", " "),
	Banner_banner_upload_items_fill_lore("GUI.Banner banner_upload items fill lore", Arrays.asList()),
	Banner_banner_upload_items_fill2_name("GUI.Banner banner_upload items fill2 name", "&cPlace your new banner here!"),
	Banner_banner_upload_items_fill2_lore("GUI.Banner banner_upload items fill2 lore", Arrays.asList(" ", " &cPlace your new banner here!")),
	Banner_banner_upload_items_back_name("GUI.Banner banner_upload items back name", "&cCome back"),
	Banner_banner_upload_items_back_lore("GUI.Banner banner_upload items back lore", Arrays.asList("", " &cClick to go back.")),
	Banner_banner_upload_items_confirm_name("GUI.Banner banner_upload items confirm name", "&aClick to save."),
	Banner_banner_upload_items_confirm_lore("GUI.Banner banner_upload items confirm lore", Arrays.asList("", " &eClick here to save.")),
	
	
	
	COMMANDS("COMMANDS", " ", " ", " ", " # TRANSLATIONS OF THE COMMANDS", " "),

	//CLAN COMMANDS
	
	COMMANDS_clan_help_show_on_help("COMMANDS.clan help show on_help", " &b/clan help &7-&e Show help menu."),
	COMMANDS_clan_help_show_on_help_json_hover_text("COMMANDS.clan help show on_help_json hover_text", "&aClick to view help of Clans."),
	COMMANDS_clan_help_show_on_success("COMMANDS.clan help show on_success", "%tag% &aYou are seeing the help!"),
	COMMANDS_clan_help_show_on_error("COMMANDS.clan help show on_error", "%tag%&cError to show text."),
	COMMANDS_clan_help_show_on_usage("COMMANDS.clan help show on_usage", "%tag% &cUse &b/clan help"),
	
	COMMANDS_clan_create_show_on_help_json_hover_text("COMMANDS.clan create show on_help_json hover_text", "&aClick to create a new clan."),
	COMMANDS_clan_create_show_on_help("COMMANDS.clan create show on_help", " &b/clan create &7-&e Create a new Clan."),
	COMMANDS_clan_create_show_on_success("COMMANDS.clan create show on_success", "%tag% &aYou have created a new clan!"),
	COMMANDS_clan_create_show_on_error("COMMANDS.clan create show on_error", "%tag% &cError creating a new Clan, try again."),
	COMMANDS_clan_create_show_on_usage("COMMANDS.clan create show on_usage", "%tag% &cUse &b/clan create <tag>"),
	
	COMMANDS_clan_cancel_show_on_help_json_hover_text("COMMANDS.clan cancel show on_help_json hover_text", "&aClick to cancel pending actions."),
	COMMANDS_clan_cancel_show_on_help("COMMANDS.clan cancel show on_help", " &b/clan cancel &7-&e Cancel pending actions."),
	COMMANDS_clan_cancel_show_on_success("COMMANDS.clan cancel show on_success", "%tag% &aSuccessfully canceled!!"),
	COMMANDS_clan_cancel_show_on_error("COMMANDS.clan cancel show on_error", "%tag% &cError canceling"),
	COMMANDS_clan_cancel_show_on_usage("COMMANDS.clan cancel show on_usage", "%tag% &cUse &b/clan cancel"),
	
	COMMANDS_clan_changeleader_show_on_help_json_hover_text("COMMANDS.clan changeleader show on_help_json hover_text", "&aClick to transfer the leadership."),
	COMMANDS_clan_changeleader_show_on_help("COMMANDS.clan changeleader show on_help", " &b/clan changeleader <player> &7-&e Transfer the leadership."),
	COMMANDS_clan_changeleader_show_on_success("COMMANDS.clan changeleader show on_success", "%tag% &aYou have changed clan leadership to %clan_leader%"),
	COMMANDS_clan_changeleader_show_on_error("COMMANDS.clan changeleader show on_error", "%tag% &cError transferring leadership."),
	COMMANDS_clan_changeleader_show_on_usage("COMMANDS.clan changeleader show on_usage", "%tag% &cUse &b/clan changeleader <player>"),
	
	COMMANDS_clan_desc_show_on_help("COMMANDS.clan desc show on_help", " &b/clan desc &7-&e Add desc to Clan."),
	COMMANDS_clan_desc_show_on_help_json_hover_text("COMMANDS.clan desc show on_help_json hover_text", "&aClick to add/change a clan description."),
	COMMANDS_clan_desc_show_on_success("COMMANDS.clan desc show on_success", "%tag% &aYou have changed the description of clan!"),
	COMMANDS_clan_desc_show_on_error("COMMANDS.clan desc show on_error", "%tag% &cError changing the Clan description."),
	COMMANDS_clan_desc_show_on_usage("COMMANDS.clan desc show on_usage", "%tag% &cUse &b/clan desc <description>"),
	
	COMMANDS_clan_disband_show_on_help("COMMANDS.clan disband show on_help", " &b/clan disband &7-&e Delete you Clan."),
	COMMANDS_clan_disband_show_on_help_json_hover_text("COMMANDS.clan disband show on_help_json hover_text", "&aClick to disband a clan."),
	COMMANDS_clan_disband_show_on_success("COMMANDS.clan disband show on_success", "%tag% &aYou have deleted you clan!"),
	COMMANDS_clan_disband_show_on_error("COMMANDS.clan disband show on_error", "%tag% &cError deleting the Clan, try again."),
	COMMANDS_clan_disband_show_on_usage("COMMANDS.clan disband show on_usage", "%tag% &cUse &b/clan disband CONFIRM"),
	
	COMMANDS_clan_leave_show_on_help("COMMANDS.clan leave show on_help", " &b/clan leave &7-&e Leave a Clan."),
	COMMANDS_clan_leave_show_on_help_json_hover_text("COMMANDS.clan leave show on_help_json hover_text", "&aClick to leave to Clan."),
	COMMANDS_clan_leave_show_on_success("COMMANDS.clan leave show on_success", "%tag% &aYou left the Clan!"),
	COMMANDS_clan_leave_show_on_error("COMMANDS.clan leave show on_error", "%tag% &cError when leaving the Clan, try again."),
	COMMANDS_clan_leave_show_on_usage("COMMANDS.clan leave show on_usage", "%tag% &cUse &b/clan leave"),
	
	COMMANDS_clan_invite_show_on_help("COMMANDS.clan invite show on_help", " &b/clan invite <player> &7-&e Invite a Player to your clan."),
	COMMANDS_clan_invite_show_on_help_json_hover_text("COMMANDS.clan invite show on_help_json hover_text", "&aClick to send invite to player"),
	COMMANDS_clan_invite_show_on_success("COMMANDS.clan invite show on_success", "%tag% &aAn invitation has been sent to the player, please wait!"),
	COMMANDS_clan_invite_show_on_error("COMMANDS.clan invite show on_error", "%tag% &cError to invite player."),
	COMMANDS_clan_invite_show_on_usage("COMMANDS.clan invite show on_usage", "%tag% &cUse &b/clan invite <player>"),
	

	COMMANDS_clan_join_show_on_help("COMMANDS.clan join show on_help", " &b/clan join <tag> &7- &eAccept the invitation of a player."),
	COMMANDS_clan_join_show_on_help_json_hover_text("COMMANDS.clan join show on_help_json hover_text", "&aClick to accept invite."),
	COMMANDS_clan_join_show_on_success("COMMANDS.clan join show on_success", "%tag% &aYou have accepted the invitation to enter the clan!"),
	COMMANDS_clan_join_show_on_error("COMMANDS.clan join show on_error", "%tag% &cError entering the clan, try again."),
	COMMANDS_clan_join_show_on_usage("COMMANDS.clan join show on_usage", "%tag% &cUse &b/clan join <tag>"),
	
	COMMANDS_clan_deny_show_on_help("COMMANDS.clan deny show on_help", " &b/clan deny <tag> &7- &eDeny invitation of a player."),
	COMMANDS_clan_deny_show_on_help_json_hover_text("COMMANDS.clan deny show on_help_json hover_text", "&aClick to cancel invite."),
	COMMANDS_clan_deny_show_on_success("COMMANDS.clan deny show on_success", "%tag% &aYou have danied invite!"),
	COMMANDS_clan_deny_show_on_error("COMMANDS.clan deny show on_error", "%tag% &cError declining invitation."),
	COMMANDS_clan_deny_show_on_usage("COMMANDS.clan deny show on_usage", "%tag% &cUse &b/clan deny <tag>"),
	
	COMMANDS_clan_kick_show_on_help("COMMANDS.clan kick show on_help", " &b/clan kick <player> &7-&e Remove player from Clan."),
	COMMANDS_clan_kick_show_on_help_json_hover_text("COMMANDS.clan kick show on_help_json hover_text", "&aClick to remove one player from the Clan."),
	COMMANDS_clan_kick_show_on_success("COMMANDS.clan kick show on_success", "%tag% &aPlayer has been removed from clan."),
	COMMANDS_clan_kick_show_on_error("COMMANDS.clan kick show on_error", "%tag% &cError kicking the player."),
	COMMANDS_clan_kick_show_on_usage("COMMANDS.clan kick show on_usage", "%tag% &cUse &b/clan kick <player>"),
	
	COMMANDS_clan_promote_show_on_help("COMMANDS.clan promote show on_help", " &b/clan promote <player> &7-&e Promote player do Mod."),
	COMMANDS_clan_promote_show_on_help_json_hover_text("COMMANDS.clan promote show on_help_json hover_text", "&aClick to promote player."),
	COMMANDS_clan_promote_show_on_success("COMMANDS.clan promote show on_success", "%tag% &aPlayer as promoted to Mod of clan."),
	COMMANDS_clan_promote_show_on_error("COMMANDS.clan promote show on_error", "%tag% &cError promoting the player, try again."),
	COMMANDS_clan_promote_show_on_usage("COMMANDS.clan promote show on_usage", "%tag% &cUse &b/clan promote <player>"),
	
	COMMANDS_clan_demote_show_on_help("COMMANDS.clan demote show on_help", " &b/clan demote <player> &7-&e Demote player on Clan."),
	COMMANDS_clan_demote_show_on_help_json_hover_text("COMMANDS.clan demote show on_help_json hover_text", "&aClick to demote player."),
	COMMANDS_clan_demote_show_on_success("COMMANDS.clan demote show on_success", "%tag% &aPlayer has been demoted in clan."),
	COMMANDS_clan_demote_show_on_error("COMMANDS.clan demote show on_error", "%tag% &cError demoting this player, try again"),
	COMMANDS_clan_demote_show_on_usage("COMMANDS.clan demote show on_usage", "%tag% &cUse &b/clan demote <player>"),
	
	COMMANDS_clan_home_show_on_help("COMMANDS.clan home show on_help", " &b/clan home <create|delete|list|teleport>  <name> &7-&e Teleport to Clan home."),
	COMMANDS_clan_home_show_on_help_json_hover_text("COMMANDS.clan home show on_help_json hover_text", "&aClick to teleport to home of Clan."),
	COMMANDS_clan_home_show_on_success("COMMANDS.clan home show on_success", "%tag% &aYou have teleported to Clan home!"),
	COMMANDS_clan_home_show_on_error("COMMANDS.clan home show on_error", "%tag% &cError teleport to Clan home."),
	COMMANDS_clan_home_show_on_usage("COMMANDS.clan home show on_usage", "%tag% &cUse &b/clan home <create|delete|list|teleport> <name>"),
	
	COMMANDS_clan_chat_show_on_help("COMMANDS.clan chat show on_help", " &b/clan chat &7-&e Lock chat to Clan or use &b/  <msg>"),
	COMMANDS_clan_chat_show_on_help_json_hover_text("COMMANDS.clan chat show on_help_json hover_text", "&aClick to toggle Clan chat."),
	COMMANDS_clan_chat_show_on_success("COMMANDS.clan chat show on_success", "%tag% &aClan locked chat as now: &b%player_chat%"),
	COMMANDS_clan_chat_show_on_error("COMMANDS.clan chat show on_error", "%tag% &cError to use chat."),
	COMMANDS_clan_chat_show_on_usage("COMMANDS.clan chat show on_usage", "%tag% &cUse &b/clan chat"),
	
	COMMANDS_clan_ff_show_on_help("COMMANDS.clan ff show on_help", " &b/clan ff &7-&e Toggle Friedly Fire on Clan."),
	COMMANDS_clan_ff_show_on_help_json_hover_text("COMMANDS.clan ff show on_help_json hover_text", "&aClick to toggle friendly fire of clan."),
	COMMANDS_clan_ff_show_on_success("COMMANDS.clan ff show on_success", "%tag% &aFriendly Fire of Clan as changed to &b%clan_ff%"),
	COMMANDS_clan_ff_show_on_error("COMMANDS.clan ff show on_error", "%tag% &cError to use ff."),
	COMMANDS_clan_ff_show_on_usage("COMMANDS.clan ff show on_usage", "%tag% &cUse &b/clan ff"),

	COMMANDS_clan_modtag_show_on_help("COMMANDS.clan modtag show on_help", " &b/clan modtag <newtag> &7-&e Change tag of Clan."),
	COMMANDS_clan_modtag_show_on_help_json_hover_text("COMMANDS.clan modtag show on_help_json hover_text", "&aClick to change Tag."),
	COMMANDS_clan_modtag_show_on_success("COMMANDS.clan modtag show on_success", "%tag% &aA tag of Clan as changed to &b%clan_tag%"),
	COMMANDS_clan_modtag_show_on_error("COMMANDS.clan modtag show on_error", "%tag% &cError when changing the clan Tag."),
	COMMANDS_clan_modtag_show_on_usage("COMMANDS.clan modtag show on_usage", "%tag% &cUse &b/clan modtag <newtag>"),
	
	COMMANDS_clan_list_show_on_help("COMMANDS.clan list show on_help", " &b/clan list &7-&e List of all Clans."),
	COMMANDS_clan_list_show_on_help_json_hover_text("COMMANDS.clan list show on_help_json hover_text", "&aClick to list all Clans."),
	COMMANDS_clan_list_show_on_success("COMMANDS.clan list show on_success", "%tag% &aSuccess to use list."),
	COMMANDS_clan_list_show_on_error("COMMANDS.clan list show on_error", "%tag% &cError to use list."),
	COMMANDS_clan_list_show_on_usage("COMMANDS.clan list show on_usage", "%tag% &cUse &b/clan list"),
	
	COMMANDS_clan_info_show_on_help("COMMANDS.clan info show on_help", " &b/clan info [tag] &7-&e Show info of clan."),
	COMMANDS_clan_info_show_on_help_json_hover_text("COMMANDS.clan info show on_help_json hover_text", "&aClick to view info of Clan."),
	COMMANDS_clan_info_show_on_success("COMMANDS.clan info show on_success", ""),
	COMMANDS_clan_info_show_on_error("COMMANDS.clan info show on_error", "%tag% &cError to use info."),
	COMMANDS_clan_info_show_on_usage("COMMANDS.clan info show on_usage", "%tag% &cUse &b/clan info [tag]"),
	
	COMMANDS_clan_profile_show_on_help("COMMANDS.clan profile show on_help", " &b/clan profile [player] &7-&e Show profile of player."),
	COMMANDS_clan_profile_show_on_help_json_hover_text("COMMANDS.clan profile show on_help_json hover_text", "&aClick to show profile."),
	COMMANDS_clan_profile_show_on_success("COMMANDS.clan profile show on_success", "%tag% &aSuccess to use profile."),
	COMMANDS_clan_profile_show_on_error("COMMANDS.clan profile show on_error", "%tag% &cError to use profile."),
	COMMANDS_clan_profile_show_on_usage("COMMANDS.clan profile show on_usage", "%tag% &cUse &b/clan profile [player]"),
	
	COMMANDS_clan_rival_show_on_help("COMMANDS.clan rival show on_help", " &b/clan rival <add/remove> <tag> &7-&e Add Clan to rival."),
	COMMANDS_clan_rival_show_on_help_json_hover_text("COMMANDS.clan rival show on_help_json hover_text", "&aClick to add/remove a Clan rival."),
	COMMANDS_clan_rival_show_on_success("COMMANDS.clan rival show on_success", "%tag% &aList of rivalries is updated."),
	COMMANDS_clan_rival_show_on_error("COMMANDS.clan rival show on_error", "%tag% &cError to use rival."),
	COMMANDS_clan_rival_show_on_usage("COMMANDS.clan rival show on_usage", "%tag% &cUse &b/clan rival <add/remove> <tag>."),
	
	COMMANDS_clan_rivalries_show_on_help("COMMANDS.clan rivalries show on_help", " &b/clan rivalries &7-&e List rivalries"),
	COMMANDS_clan_rivalries_show_on_help_json_hover_text("COMMANDS.clan rivalries show on_help_json hover_text", "&aClick to list rivalries Clan."),
	COMMANDS_clan_rivalries_show_on_success("COMMANDS.clan rivalries show on_success", "%tag% &aSuccess to use rivalries."),
	COMMANDS_clan_rivalries_show_on_error("COMMANDS.clan rivalries show on_error", "%tag% &cError to use rivalries."),
	COMMANDS_clan_rivalries_show_on_usage("COMMANDS.clan rivalries show on_usage", "%tag% &cUse &b/clan rivalries"),
	
	COMMANDS_clan_ally_show_on_help("COMMANDS.clan ally show on_help", " &b/clan ally <add/remove/accept/deny> <tag> &7-&e Add Clan as ally."),
	COMMANDS_clan_ally_show_on_help_json_hover_text("COMMANDS.clan ally show on_help_json hover_text", "&aClick to add/remove a Clan ally."),
	COMMANDS_clan_ally_show_on_success("COMMANDS.clan ally show on_success", "%tag% &aList of alliances is updated."),
	COMMANDS_clan_ally_show_on_error("COMMANDS.clan ally show on_error", "%tag% &cError to use ally."),
	COMMANDS_clan_ally_show_on_usage("COMMANDS.clan ally show on_usage", "%tag% &cUse &b/clan ally <add/remove/accept/deny> <tag>."),
	
	COMMANDS_clan_alliances_show_on_help("COMMANDS.clan alliances show on_help", " &b/clan alliances &7-&e List alliances."),
	COMMANDS_clan_alliances_show_on_help_json_hover_text("COMMANDS.clan alliances show on_help_json hover_text", "&aClick to list alliances of Clan."),
	COMMANDS_clan_alliances_show_on_success("COMMANDS.clan alliances show on_success", "%tag% &aSuccess to use alliances."),
	COMMANDS_clan_alliances_show_on_error("COMMANDS.clan alliances show on_error", "%tag% &cError to use alliances."),
	COMMANDS_clan_alliances_show_on_usage("COMMANDS.clan alliances show on_usage", "%tag% &cUse &b/clan alliances."),
	
	COMMANDS_clan_members_show_on_help("COMMANDS.clan members show on_help", " &b/clan members &7-&e Shows the list of members."),
	COMMANDS_clan_members_show_on_help_json_hover_text("COMMANDS.clan members show on_help_json hover_text", "&aClick to view."),
	COMMANDS_clan_members_show_on_success("COMMANDS.clan members show on_success", "%tag% &aSuccess to use members."),
	COMMANDS_clan_members_show_on_error("COMMANDS.clan members show on_error", "%tag% &cError to use members."),
	COMMANDS_clan_members_show_on_usage("COMMANDS.clan members show on_usage", "%tag% &cUse &6/clan members"),
	
	COMMANDS_clan_settings_show_on_help("COMMANDS.clan settings show on_help", " &b/clan settings <TYPE> <VALUE> &7-&e Change clan settings."),
	COMMANDS_clan_settings_show_on_help_json_hover_text("COMMANDS.clan settings show on_help_json hover_text", "&aClick to change clan settings"),
	COMMANDS_clan_settings_show_on_success("COMMANDS.clan settings show on_success", "%tag% &aClan settings changed to &b%type%&7:&b%value%"),
	COMMANDS_clan_settings_show_on_error("COMMANDS.clan settings show on_error", "%tag% &cAn error occurred while changing clan settings."),
	COMMANDS_clan_settings_show_on_usage("COMMANDS.clan settings show on_usage", "%tag% &cUse &b/clan settings <TYPE> <VALUE>"),
	
	COMMANDS_clan_regroup_show_on_help("COMMANDS.clan regroup show on_help", " &b/clan regroup <send/accept/deny> &7-&e Regroup the clan"),
	COMMANDS_clan_regroup_show_on_help_json_hover_text("COMMANDS.clan regroup show on_help_json hover_text", "&aClick to regroup the clan"),
	COMMANDS_clan_regroup_show_on_success("COMMANDS.clan regroup show on_success", "%tag% &aThe regroup request has been sent."),
	COMMANDS_clan_regroup_show_on_error("COMMANDS.clan regroup show on_error", "%tag% &cAn error occurred when submitting the order."),
	COMMANDS_clan_regroup_show_on_usage("COMMANDS.clan regroup show on_usage", "%tag% &cUse &b/clan regroup <send/accept/deny>"),
	
	COMMANDS_clan_banner_show_on_help("COMMANDS.clan banner show on_help", " &b/clan banner <open|send|delete> &7-&e Clan Banner"),
	COMMANDS_clan_banner_show_on_help_json_hover_text("COMMANDS.clan banner show on_help_json hover_text", "&aClick to change clan banner"),
	COMMANDS_clan_banner_show_on_success("COMMANDS.clan banner show on_success", "%tag% &aThe new banner was successfully saved!"),
	COMMANDS_clan_banner_show_on_error("COMMANDS.clan banner show on_error", "%tag% &cThere was an error saving."),
	COMMANDS_clan_banner_show_on_usage("COMMANDS.clan banner show on_usage", "%tag% &cUse &b/clan banner <open|send|delete>"),
	
	// UCLANS COMMANDS
	COMMANDS_uclan_help_show_on_help("COMMANDS.uclan help show on_help", " &4/uclan help &7-&e Show help menu."),
	COMMANDS_uclan_help_show_on_help_json_hover_text("COMMANDS.uclan help show on_help_json hover_text", "&aClick to view help of Clans."),
	COMMANDS_uclan_help_show_on_success("COMMANDS.uclan help show on_success", "%tag% &aSuccess to use help."),
	COMMANDS_uclan_help_show_on_error("COMMANDS.uclan help show on_error", "%tag% &cError to use help"),
	COMMANDS_uclan_help_show_on_usage("COMMANDS.uclan help show on_usage", "%tag% &cError use &b/uclan help"),
	
	COMMANDS_uclan_chatspy_show_on_help("COMMANDS.uclan chatspy show on_help", " &4/uclan chatspy &7-&e Spy on clan chat"),
	COMMANDS_uclan_chatspy_show_on_help_json_hover_text("COMMANDS.uclan chatspy show on_help_json hover_text", "&aClick to spy on clan chat"),
	COMMANDS_uclan_chatspy_show_on_success("COMMANDS.uclan chatspy show on_success", "%tag% &aChat Spy is now: %state%"),
	COMMANDS_uclan_chatspy_show_on_error("COMMANDS.uclan chatspy show on_error", "%tag% &cAn error occurred while changing."),
	COMMANDS_uclan_chatspy_show_on_usage("COMMANDS.uclan chatspy show on_usage", "%tag% &cUse &4/uclan chatspy"),
	
	COMMANDS_uclan_addslot_show_on_help("COMMANDS.uclan addslot show on_help", " &4/uclan addslot <player|tag> <amount> &7-&e Add slots to the Clan."),
	COMMANDS_uclan_addslot_show_on_help_json_hover_text("COMMANDS.uclan addslot show on_help_json hover_text", "&aClick to add slots to the clan"),
	COMMANDS_uclan_addslot_show_on_success("COMMANDS.uclan addslot show on_success", "%tag% &aYou have added %num% slots to the %clan% clan"),
	COMMANDS_uclan_addslot_show_on_error("COMMANDS.uclan addslot show on_error", "%tag% &cThere was an error adding."),
	COMMANDS_uclan_addslot_show_on_usage("COMMANDS.uclan addslot show on_usage", "%tag% &cUse &4/uclan addslot <player|tag> <amount>"),
	
	COMMANDS_uclan_setslot_show_on_help("COMMANDS.uclan setslot show on_help", " &4/uclan setslot <player|tag> <amount> &7-&e Set slots to the Clan."),
	COMMANDS_uclan_setslot_show_on_help_json_hover_text("COMMANDS.uclan setslot show on_help_json hover_text", "&aClick to set slots to the clan"),
	COMMANDS_uclan_setslot_show_on_success("COMMANDS.uclan setslot show on_success", "%tag% &aYou have set %num% slots to the %clan% clan"),
	COMMANDS_uclan_setslot_show_on_error("COMMANDS.uclan setslot show on_error", "%tag% &cThere was an error adding."),
	COMMANDS_uclan_setslot_show_on_usage("COMMANDS.uclan setslot show on_usage", "%tag% &cUse &4/uclan setslot <player|tag> <amount>"),
	
	COMMANDS_uclan_removeslot_show_on_help("COMMANDS.uclan removeslot show on_help", " &4/uclan removeslot <player|tag> <amount> &7-&e Remove slots to the Clan."),
	COMMANDS_uclan_removeslot_show_on_help_json_hover_text("COMMANDS.uclan removeslot show on_help_json hover_text", "&aClick to remove slots to the clan"),
	COMMANDS_uclan_removeslot_show_on_success("COMMANDS.uclan removeslot show on_success", "%tag% &aYou have removed %num% slots to the %clan% clan"),
	COMMANDS_uclan_removeslot_show_on_error("COMMANDS.uclan removeslot show on_error", "%tag% &cThere was an error adding."),
	COMMANDS_uclan_removeslot_show_on_usage("COMMANDS.uclan removeslot show on_usage", "%tag% &cUse &4/uclan removeslot <player|tag> <amount>"),
	
	COMMANDS_uclan_addpoints_show_on_help("COMMANDS.uclan addpoints show on_help", " &4/uclan addpoints <player|tag> <amount> &7-&e Add points to the Clan."),
	COMMANDS_uclan_addpoints_show_on_help_json_hover_text("COMMANDS.uclan addpoints show on_help_json hover_text", "&aClick to add points to the clan"),
	COMMANDS_uclan_addpoints_show_on_success("COMMANDS.uclan addpoints show on_success", "%tag% &aYou have added %num% points to the %clan% clan"),
	COMMANDS_uclan_addpoints_show_on_error("COMMANDS.uclan addpoints show on_error", "%tag% &cThere was an error adding."),
	COMMANDS_uclan_addpoints_show_on_usage("COMMANDS.uclan addpoints show on_usage", "%tag% &cUse &4/uclan addpoints <player|tag> <amount>"),
	
	COMMANDS_uclan_setpoints_show_on_help("COMMANDS.uclan setpoints show on_help", " &4/uclan setpoints <player|tag> <amount> &7-&e set points to the Clan."),
	COMMANDS_uclan_setpoints_show_on_help_json_hover_text("COMMANDS.uclan setpoints show on_help_json hover_text", "&aClick to set points to the clan"),
	COMMANDS_uclan_setpoints_show_on_success("COMMANDS.uclan setpoints show on_success", "%tag% &aYou have set %num% points to the %clan% clan"),
	COMMANDS_uclan_setpoints_show_on_error("COMMANDS.uclan setpoints show on_error", "%tag% &cThere was an error adding."),
	COMMANDS_uclan_setpoints_show_on_usage("COMMANDS.uclan setpoints show on_usage", "%tag% &cUse &4/uclan setpoints <player|tag> <amount>"),
	
	COMMANDS_uclan_removepoints_show_on_help("COMMANDS.uclan removepoints show on_help", " &4/uclan removepoints <player|tag> <amount> &7-&e Remove points to the Clan."),
	COMMANDS_uclan_removepoints_show_on_help_json_hover_text("COMMANDS.uclan removepoints show on_help_json hover_text", "&aClick to remove points to the clan"),
	COMMANDS_uclan_removepoints_show_on_success("COMMANDS.uclan removepoints show on_success", "%tag% &aYou have removed %num% points to the %clan% clan"),
	COMMANDS_uclan_removepoints_show_on_error("COMMANDS.uclan removepoints show on_error", "%tag% &cThere was an error remove."),
	COMMANDS_uclan_removepoints_show_on_usage("COMMANDS.uclan removepoints show on_usage", "%tag% &cUse &4/uclan removepoints <player|tag> <amount>"),
	
	
	COMMANDS_uclan_changetag_show_on_help("COMMANDS.uclan changetag show on_help", " &4/uclan changetag <tag> <newtag> &7-&e Changing a clan tag."),
	COMMANDS_uclan_changetag_show_on_help_json_hover_text("COMMANDS.uclan changetag show on_help_json hover_text", "&aCLick to changing a clan tag."),
	COMMANDS_uclan_changetag_show_on_success("COMMANDS.uclan changetag show on_success", "%tag% &aThe clan tag &b%clan% &ahas been changed to &b%newtag%"),
	COMMANDS_uclan_changetag_show_on_error("COMMANDS.uclan changetag show on_error", "%tag% &cAn error occurred while changing the tag."),
	COMMANDS_uclan_changetag_show_on_usage("COMMANDS.uclan changetag show on_usage", "%tag% &cErro use &4/uclan changetag <tag> <newtag>"),
	
	COMMANDS_uclan_resetplayerkdr_show_on_help("COMMANDS.uclan resetplayerkdr show on_help", " &4/uclan resetplayerkdr <player> &7-&e Reset Player KDR."),
	COMMANDS_uclan_resetplayerkdr_show_on_help_json_hover_text("COMMANDS.uclan resetplayerkdr show on_help_json hover_text", "&aClick to reset player KDR"),
	COMMANDS_uclan_resetplayerkdr_show_on_success("COMMANDS.uclan resetplayerkdr show on_success", "%tag% &aYou have reset the KDR of the player &a%player%"),
	COMMANDS_uclan_resetplayerkdr_show_on_error("COMMANDS.uclan resetplayerkdr show on_error", "%tag% &cAn error occurred while resetting"),
	COMMANDS_uclan_resetplayerkdr_show_on_usage("COMMANDS.uclan resetplayerkdr show on_usage", "%tag% &cUse &4/uclan resetplayerkdr <player>"),
	
	COMMANDS_uclan_resetclankdr_show_on_help("COMMANDS.uclan resetclankdr show on_help", " &4/uclan resetclankdr <tag> &7-&e Reset Clan KDR."),
	COMMANDS_uclan_resetclankdr_show_on_help_json_hover_text("COMMANDS.uclan resetclankdr show on_help_json hover_text", "&aClick to reset Clan KDR"),
	COMMANDS_uclan_resetclankdr_show_on_success("COMMANDS.uclan resetclankdr show on_success", "%tag% &aYou have reset the KDR of the clan &a%uclans_tag_color%"),
	COMMANDS_uclan_resetclankdr_show_on_error("COMMANDS.uclan resetclankdr show on_error", "%tag% &cAn error occurred while resetting"),
	COMMANDS_uclan_resetclankdr_show_on_usage("COMMANDS.uclan resetclankdr show on_usage", "%tag% &cUse &4/uclan resetclankdr <tag>"),
	
	COMMANDS_uclan_globalff_show_on_help("COMMANDS.uclan globalff show on_help", " &4/uclan globalff &7-&e Change a global ff."),
	COMMANDS_uclan_globalff_show_on_help_json_hover_text("COMMANDS.uclan globalff show on_help_json hover_text", "&aClick change global FF"),
	COMMANDS_uclan_globalff_show_on_success("COMMANDS.uclan globalff show on_success", "%tag% &aYou have changed a global ff to &b%globalff%"),
	COMMANDS_uclan_globalff_show_on_error("COMMANDS.uclan globalff show on_error", "%tag% &cError to use globaff."),
	COMMANDS_uclan_globalff_show_on_usage("COMMANDS.uclan globalff show on_usage", "%tag% &cUse &4/uclan globalff"),
	
	COMMANDS_uclan_delete_show_on_help("COMMANDS.uclan delete show on_help", " &4/uclan delete <tag> &7-&e Delete a new Clan."),
	COMMANDS_uclan_delete_show_on_help_json_hover_text("COMMANDS.uclan delete show on_help_json hover_text", "&aClick to delete one Clan."),
	COMMANDS_uclan_delete_show_on_success("COMMANDS.uclan delete show on_success", "%tag% &aYou have deleted a clan!"),
	COMMANDS_uclan_delete_show_on_error("COMMANDS.uclan delete show on_error", "%tag% &cError deleting the clan."),
	COMMANDS_uclan_delete_show_on_usage("COMMANDS.uclan delete show on_usage", "%tag% &cUse &4/uclan delete <tag>"),
	
	COMMANDS_uclan_forcejoin_show_on_help("COMMANDS.uclan forcejoin show on_help", " &4/uclan forcejoin <player> <tag> &7-&e Adds a player to a clan."),
	COMMANDS_uclan_forcejoin_show_on_help_json_hover_text("COMMANDS.uclan forcejoin show on_help_json hover_text", "&aClick to adds a player to a clan."),
	COMMANDS_uclan_forcejoin_show_on_success("COMMANDS.uclan forcejoin show on_success", "%tag% &aYou added the player!"),
	COMMANDS_uclan_forcejoin_show_on_error("COMMANDS.uclan forcejoin show on_error", "%tag% &cError adding player."),
	COMMANDS_uclan_forcejoin_show_on_usage("COMMANDS.uclan forcejoin show on_usage", "%tag% &cUse &4/uclan forcejoin <player> <tag>"),
	
	COMMANDS_uclan_verify_show_on_help("COMMANDS.uclan verify show on_help", " &4/uclan verify <tag> &7-&e Verify a Clan."),
	COMMANDS_uclan_verify_show_on_help_json_hover_text("COMMANDS.uclan verify show on_help_json hover_text", "&aClick to verify one Clan."),
	COMMANDS_uclan_verify_show_on_success("COMMANDS.uclan verify show on_success", "%tag% &aYou have toggled clan verification!"),
	COMMANDS_uclan_verify_show_on_error("COMMANDS.uclan verify show on_error", "%tag% &cError checking the clan."),
	COMMANDS_uclan_verify_show_on_usage("COMMANDS.uclan verify show on_usage", "%tag% &cUse &4/uclan verify <tag>"),
	
	COMMANDS_uclan_reload_show_on_help("COMMANDS.uclan reload show on_help", " &4/uclan reload &7-&e Reload the plugin."),
	COMMANDS_uclan_reload_show_on_help_json_hover_text("COMMANDS.uclan reload show on_help_json hover_text", "&aClick to reload plugin configurations."),
	COMMANDS_uclan_reload_show_on_success("COMMANDS.uclan reload show on_success", "%tag% &aPlugin reloaded successfully &7(%time%)."),
	COMMANDS_uclan_reload_show_on_error("COMMANDS.uclan reload show on_error", "%tag% &cError reloading settings."),
	COMMANDS_uclan_reload_show_on_usage("COMMANDS.uclan reload show on_usage", "%tag% &cUse &4/uclan reload"), 
	
	COMMANDS_uclan_reloadaddons_show_on_help("COMMANDS.uclan reloadaddons show on_help", " &4/uclan reloadaddons &7-&e Reload the addons."),
	COMMANDS_uclan_reloadaddons_show_on_help_json_hover_text("COMMANDS.uclan reloadaddons show on_help_json hover_text", "&aClick to reload addons."),
	COMMANDS_uclan_reloadaddons_show_on_success("COMMANDS.uclan reloadaddons show on_success", "%tag% &aAddons successfully reloaded! &7(%time%)."),
	COMMANDS_uclan_reloadaddons_show_on_error("COMMANDS.uclan reloadaddons show on_error", "%tag% &cError reloading addons."),
	COMMANDS_uclan_reloadaddons_show_on_usage("COMMANDS.uclan reloadaddons show on_usage", "%tag% &cUse &4/uclan reloadaddons"), 

	;
	
	private String path;
    private Object defaultValue;
    private String[] comments; 

    Lang(String path, Object defaultValue, String... comments) {
        this.path = path;
        this.defaultValue = defaultValue;
        this.comments = comments;
    }

    @Override
    public String getPath() {
    	
        return path;
    }

    @Override
    public Object getDefaultValue() {
        return defaultValue;
    }

    @Override
    public String[] getComments() {
        return comments;
    }

    
}